/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface MDARSessionObserver : NSObject <ARSessionDelegate> {
    NSObject<OS_dispatch_queue> * _delegateQueue;
    struct ARSessionObserver { int (**x1)(); } * _observer;
    ARSession * _session;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) ARSession *session;
@property (readonly) Class superclass;

- (id)initWithObserver:(struct ARSessionObserver { int (**x1)(); }*)arg1 onQueue:(id)arg2;
- (id)session;
- (void)session:(id)arg1 didChangeGeoTrackingStatus:(id)arg2;
- (void)session:(id)arg1 didUpdateAnchors:(id)arg2;
- (void)session:(id)arg1 didUpdateFrame:(id)arg2;
- (void)setSession:(id)arg1;

@end
