/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKARWalkingFeatureDidUpdateInfo : NSObject {
    struct _retain_ptr<VKARWalkingFeature *, geo::_retain_objc, geo::_release_objc, geo::_hash_objc, geo::_equal_objc> { 
        int (**_vptr$_retain_ptr)(); 
        VKARWalkingFeature *_obj; 
        struct _retain_objc { } _retain; 
        struct _release_objc { } _release; 
    }  _feature;
    struct _retain_ptr<VKARWalkingFeatureSet *, geo::_retain_objc, geo::_release_objc, geo::_hash_objc, geo::_equal_objc> { 
        int (**_vptr$_retain_ptr)(); 
        VKARWalkingFeatureSet *_obj; 
        struct _retain_objc { } _retain; 
        struct _release_objc { } _release; 
    }  _featureSet;
    bool  _isDirectlyBehind;
    bool  _isVisible;
    struct { 
        double latitude; 
        double longitude; 
        double altitude; 
    }  _labelPosition;
    struct Unit<DegreeUnitDescription, double> { 
        double _value; 
    }  _screenHeading;
    long long  _updateTypes;
}

@property (nonatomic, readonly) VKARWalkingFeature *feature;
@property (nonatomic, readonly) VKARWalkingFeatureSet *featureSet;
@property (nonatomic, readonly) bool isDirectlyBehind;
@property (nonatomic, readonly) bool isVisible;
@property (nonatomic, readonly) struct { double x1; double x2; double x3; } labelPosition;
@property (nonatomic, readonly) double screenHeading;
@property (nonatomic, readonly) long long updateTypes;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)description;
- (id)feature;
- (id)featureSet;
- (id)initWithFeature:(id)arg1 featureSet:(id)arg2 labelPosition:(const void*)arg3 updateTypes:(long long)arg4 isVisible:(bool)arg5 isDirectlyBehind:(bool)arg6 screenHeading:(struct Unit<DegreeUnitDescription, double> { double x1; })arg7;
- (bool)isDirectlyBehind;
- (bool)isVisible;
- (struct { double x1; double x2; double x3; })labelPosition;
- (double)screenHeading;
- (id)stringForUpdateTypes;
- (long long)updateTypes;

@end
