/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKLogicDebugInfo : NSObject {
    unsigned long long  _identifier;
    NSString * _name;
}

@property (nonatomic, readonly) unsigned long long identifier;
@property (nonatomic, readonly, copy) NSString *name;

- (void)dealloc;
- (unsigned long long)identifier;
- (id)initWithName:(id)arg1 identifier:(unsigned long long)arg2;
- (id)name;

@end
