/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKRouteAnnotation : VKTrafficFeature {
    GEOStyleAttributes * _originalStyleAttributes;
    GEOComposedRouteAnnotation * _routeAnnotation;
}

@property (nonatomic, readonly) GEOMiniCard *infoCard;
@property (getter=_originalStyleAttributes, nonatomic, readonly) GEOStyleAttributes *originalStyleAttributes;

- (id)_originalStyleAttributes;
- (void)dealloc;
- (id)infoCard;
- (id)initWithRouteAnnotation:(id)arg1 onRoute:(id)arg2;
- (void)populateDebugNode:(void*)arg1;

@end
