/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKTrafficSignalFeature : VKTrafficFeature {
    long long  _type;
}

@property (nonatomic, readonly) long long type;

+ (id)stringForTrafficSignalType:(long long)arg1;

- (id)initWithTrafficSignal:(id)arg1 onRoute:(id)arg2;
- (id)initWithTrafficSignalType:(long long)arg1 uniqueIdentifier:(id)arg2 routeOffset:(struct PolylineCoordinate { unsigned int x1; float x2; })arg3 onRoute:(id)arg4;
- (void)populateDebugNode:(void*)arg1;
- (long long)type;

@end
