/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ExtensionFoundation.framework/ExtensionFoundation
 */

@interface _EXDefaults : NSObject

@property (readonly) bool allowSimulatedJetsam;
@property (readonly) bool allowsAppleInternalComponents;
@property (readonly) bool appleInternal;
@property (readonly) bool enforceLegacyExtensionPointAllowList;
@property (readonly) NSSet *errorTypes;
@property (readonly) bool hostRequiresEntitlements;
@property (readonly) bool implementsNSExtension;
@property (readonly) NSSet *plistAndValueTypes;
@property (readonly) NSSet *plistTypes;
@property (readonly) bool preferInProcessDiscovery;
@property (readonly) bool queryPredicatesEvaluatedOutOfProcess;
@property (readonly) bool rejectExtensionRequestsWithInsecureInputItems;
@property (readonly) bool requiresLoadOperatorSecureDecoding;
@property (readonly) bool supportExtensionKitConfigPath;
@property (readonly) bool useLSDExtensionKitServiceForDiscovery;
@property (readonly) bool useLSDExtensionKitServiceForLaunch;

+ (id)sharedInstance;

- (id)_init;
- (bool)allowSimulatedJetsam;
- (bool)allowsAppleInternalComponents;
- (bool)appleInternal;
- (bool)enforceLegacyExtensionPointAllowList;
- (id)errorTypes;
- (bool)hostRequiresEntitlements;
- (bool)implementsNSExtension;
- (id)plistAndValueTypes;
- (id)plistTypes;
- (bool)preferInProcessDiscovery;
- (bool)queryPredicatesEvaluatedOutOfProcess;
- (bool)rejectExtensionRequestsWithInsecureInputItems;
- (bool)requiresLoadOperatorSecureDecoding;
- (bool)supportExtensionKitConfigPath;
- (bool)useLSDExtensionKitServiceForDiscovery;
- (bool)useLSDExtensionKitServiceForLaunch;

@end
