/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ExtensionFoundation.framework/ExtensionFoundation
 */

@interface _EXExtensionRecordRep : _EXExtensionRep {
    LSExtensionPointRecord * _extensionPoint;
    LSApplicationExtensionRecord * _record;
}

@property (readonly) LSExtensionPointRecord *extensionPoint;
@property (readonly) LSApplicationExtensionRecord *record;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)UUID;
- (id)attributes;
- (id)bundleIdentifier;
- (Class)classForCoder;
- (id)containingURL;
- (id)entitlementNamed:(id)arg1 ofClass:(Class)arg2;
- (id)entitlements;
- (id)extensionDictionary;
- (id)extensionPoint;
- (id)extensionPointIdentifier;
- (id)initWithApplicationExtensionRecord:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPlugInKitProxy:(id)arg1;
- (id)localizedName;
- (unsigned int)platform;
- (id)record;
- (id)sdkDictionary;
- (id)url;

@end
