/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ExtensionFoundation.framework/ExtensionFoundation
 */

@interface _EXQuery : NSObject <NSCopying, NSSecureCoding> {
    NSString * _extensionPointIdentifier;
    unsigned int  _platform;
    NSPredicate * _predicate;
}

@property (retain) NSString *extensionPointIdentifier;
@property unsigned int platform;
@property (retain) NSPredicate *predicate;

+ (id)allExtensionsQuery;
+ (id)asyncQueryQueue;
+ (id)executeQueries:(id)arg1;
+ (void)executeQueries:(id)arg1 completionHandler:(id /* block */)arg2;
+ (id)executeQuery:(id)arg1;
+ (void)executeQuery:(id)arg1 completionHandler:(id /* block */)arg2;
+ (id)extensionPointIdentifierQuery:(id)arg1;
+ (id)extensionPointIdentifierQuery:(id)arg1 platform:(unsigned int)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)extensionPointIdentifier;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToQuery:(id)arg1;
- (bool)matches:(id)arg1;
- (bool)matchesRecord:(id)arg1;
- (unsigned int)platform;
- (id)predicate;
- (void)setExtensionPointIdentifier:(id)arg1;
- (void)setPlatform:(unsigned int)arg1;
- (void)setPredicate:(id)arg1;

@end
