/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemoteTextInput.framework/RemoteTextInput
 */

@interface RTIUtilities : NSObject

+ (id)_attributedStringWithoutDefaultAttributes:(id)arg1;
+ (id)_filteredAttributedString:(id)arg1 validAttributes:(id)arg2;

@end
