/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MDMClientLibrary.framework/MDMClientLibrary
 */

@interface MDMConfiguration : NSObject {
    NSString * _easEnrollmentID;
    NSString * _enrollmentID;
    NSString * _enrollmentMode;
    bool  _isUserEnrollment;
    NSObject<OS_dispatch_queue> * _memberQueue;
    int  _memberQueueAccessRights;
    NSArray * _memberQueueCheckInPinnedSecCertificateRefs;
    NSURL * _memberQueueCheckInURL;
    struct __SecIdentity { } * _memberQueueIdentity;
    NSDictionary * _memberQueueMDMOptions;
    NSString * _memberQueueManagingProfileIdentifier;
    NSDictionary * _memberQueueOrganizationInfo;
    bool  _memberQueuePinningRevocationCheckRequired;
    NSNumber * _memberQueuePollingInterval;
    NSString * _memberQueuePushMagic;
    NSURL * _memberQueueServerURL;
    bool  _memberQueueSignMessage;
    NSString * _memberQueueTopic;
    bool  _memberQueueUseDevelopmentAPNS;
    NSString * _personaID;
    NSString * _rmAccountID;
}

@property (nonatomic, retain) NSString *easEnrollmentID;
@property (nonatomic, retain) NSString *enrollmentID;
@property (nonatomic, retain) NSString *enrollmentMode;
@property (nonatomic) bool isUserEnrollment;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *memberQueue;
@property (nonatomic) int memberQueueAccessRights;
@property (nonatomic, retain) NSArray *memberQueueCheckInPinnedSecCertificateRefs;
@property (nonatomic, retain) NSURL *memberQueueCheckInURL;
@property (nonatomic) struct __SecIdentity { }*memberQueueIdentity;
@property (nonatomic, retain) NSDictionary *memberQueueMDMOptions;
@property (nonatomic, retain) NSString *memberQueueManagingProfileIdentifier;
@property (nonatomic, retain) NSDictionary *memberQueueOrganizationInfo;
@property (nonatomic) bool memberQueuePinningRevocationCheckRequired;
@property (nonatomic, retain) NSNumber *memberQueuePollingInterval;
@property (nonatomic, retain) NSString *memberQueuePushMagic;
@property (nonatomic, retain) NSURL *memberQueueServerURL;
@property (nonatomic) bool memberQueueSignMessage;
@property (nonatomic, retain) NSString *memberQueueTopic;
@property (nonatomic) bool memberQueueUseDevelopmentAPNS;
@property (nonatomic, retain) NSString *personaID;
@property (nonatomic, retain) NSString *rmAccountID;

+ (id)sharedConfiguration;

- (void).cxx_destruct;
- (id)easEnrollmentID;
- (id)enrollmentID;
- (id)enrollmentMode;
- (id)init;
- (bool)isUserEnrollment;
- (id)memberQueue;
- (int)memberQueueAccessRights;
- (id)memberQueueCheckInPinnedSecCertificateRefs;
- (id)memberQueueCheckInURL;
- (void)memberQueueForgetCurrentConfiguration;
- (struct __SecIdentity { }*)memberQueueIdentity;
- (id)memberQueueMDMOptions;
- (id)memberQueueManagingProfileIdentifier;
- (id)memberQueueOrganizationInfo;
- (bool)memberQueuePinningRevocationCheckRequired;
- (id)memberQueuePollingInterval;
- (id)memberQueuePushMagic;
- (id)memberQueueServerURL;
- (bool)memberQueueSignMessage;
- (id)memberQueueTopic;
- (bool)memberQueueUseDevelopmentAPNS;
- (id)personaID;
- (bool)readConfigurationOutError:(id*)arg1;
- (void)refreshDetailsFromDisk;
- (id)rmAccountID;
- (void)setEasEnrollmentID:(id)arg1;
- (void)setEnrollmentID:(id)arg1;
- (void)setEnrollmentMode:(id)arg1;
- (void)setIsUserEnrollment:(bool)arg1;
- (void)setMemberQueue:(id)arg1;
- (void)setMemberQueueAccessRights:(int)arg1;
- (void)setMemberQueueCheckInPinnedSecCertificateRefs:(id)arg1;
- (void)setMemberQueueCheckInURL:(id)arg1;
- (void)setMemberQueueIdentity:(struct __SecIdentity { }*)arg1;
- (void)setMemberQueueMDMOptions:(id)arg1;
- (void)setMemberQueueManagingProfileIdentifier:(id)arg1;
- (void)setMemberQueueOrganizationInfo:(id)arg1;
- (void)setMemberQueuePinningRevocationCheckRequired:(bool)arg1;
- (void)setMemberQueuePollingInterval:(id)arg1;
- (void)setMemberQueuePushMagic:(id)arg1;
- (void)setMemberQueueServerURL:(id)arg1;
- (void)setMemberQueueSignMessage:(bool)arg1;
- (void)setMemberQueueTopic:(id)arg1;
- (void)setMemberQueueUseDevelopmentAPNS:(bool)arg1;
- (void)setPersonaID:(id)arg1;
- (void)setRmAccountID:(id)arg1;

@end
