/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MDMClientLibrary.framework/MDMClientLibrary
 */

@interface MDMDeclarativeManagement : NSObject

+ (id)_createUnsupportedFeatureError;
+ (void)executeRequestForEndpoint:(id)arg1 requestData:(id)arg2 completionHandler:(id /* block */)arg3;
+ (void)fetchDataAtURL:(id)arg1 completionHandler:(id /* block */)arg2;

@end
