/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MDMClientLibrary.framework/MDMClientLibrary
 */

@interface MDMDeviceQueryUtilities : NSObject

+ (id)allowedDeviceQueriesForAccessRights:(int)arg1;
+ (id)allowedDeviceQueriesOnUserChannelForAccessRights:(int)arg1;
+ (id)allowedDeviceQueriesWithUserEnrollment;

@end
