/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalPerformanceShadersGraph.framework/MetalPerformanceShadersGraph
 */

@interface MPSGraphExecutableExecutionDescriptor : NSObject {
    bool  _breakUpMetalEncoders;
    id /* block */  _completionHandler;
    bool  _enableCommitAndContinue;
    bool  _enableProfilingOpNames;
    id /* block */  _scheduledHandler;
    bool  _waitUntilCompleted;
}

@property bool breakUpMetalEncoders;
@property (copy) id /* block */ completionHandler;
@property bool enableCommitAndContinue;
@property bool enableProfilingOpNames;
@property (copy) id /* block */ scheduledHandler;
@property bool waitUntilCompleted;

- (void).cxx_destruct;
- (bool)breakUpMetalEncoders;
- (id /* block */)completionHandler;
- (bool)enableCommitAndContinue;
- (bool)enableProfilingOpNames;
- (id)init;
- (id /* block */)scheduledHandler;
- (void)setBreakUpMetalEncoders:(bool)arg1;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)setEnableCommitAndContinue:(bool)arg1;
- (void)setEnableProfilingOpNames:(bool)arg1;
- (void)setScheduledHandler:(id /* block */)arg1;
- (void)setWaitUntilCompleted:(bool)arg1;
- (bool)waitUntilCompleted;

@end
