/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalPerformanceShadersGraph.framework/MetalPerformanceShadersGraph
 */

@interface MPSGraphCompilationDescriptor : NSObject {
    unsigned long long  _aneCompilerSpatialSplitting;
    bool  _compileANEInMemory;
    unsigned long long  _compilerOptions;
}

@property unsigned long long aneCompilerSpatialSplitting;
@property bool compileANEInMemory;
@property unsigned long long compilerOptions;

- (unsigned long long)aneCompilerSpatialSplitting;
- (bool)compileANEInMemory;
- (unsigned long long)compilerOptions;
- (void)disableTypeInference;
- (void)enableFileBackedConstants;
- (id)init;
- (void)setAneCompilerSpatialSplitting:(unsigned long long)arg1;
- (void)setCompileANEInMemory:(bool)arg1;
- (void)setCompilerOptions:(unsigned long long)arg1;

@end
