/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAnalytics.framework/SiriAnalytics
 */

@interface AssistantSiriAnalyticsService : NSObject {
    AssistantSiriAnalyticsClockWatcher * _clockWatcher;
    <SiriAnalyticsServiceHostDelegate> * _delegate;
    SiriAnalyticsInternalTelemetry * _internalTelemetry;
    SiriAnalyticsLargeMessageStorage * _largeMessageStorage;
    <SiriAnalyticsMessageStorage> * _localStorageProvider;
    SiriAnalyticsMessageResolutionPipeline * _messageResolutionPipeline;
    AssistantSiriAnalyticsMessageTailing * _messageTailing;
    SiriAnalyticsMessageObserverStream * _postTransformStream;
    SiriAnalyticsPreferences * _preferences;
    NSObject<OS_dispatch_queue> * _queue;
    SiriAnalyticsXPCServiceListener * _siriAnalyticsListener;
    SiriAnalyticsTimePeriodBuffer * _storageBuffer;
    <SiriAnalyticsMessageStorage> * _storageProvider;
    SiriAnalyticsWhiteRose * _whiteRose;
}

@property (readonly) <SiriAnalyticsObservableMessages> *postTransformationStream;

- (void).cxx_destruct;
- (bool)_analyticsEnabled;
- (id)_applyTransformationsToMessage:(id)arg1;
- (id)_applyTransformationsToMessages:(id)arg1;
- (id)initWithQueue:(id)arg1;
- (id)initWithQueue:(id)arg1 delegate:(id)arg2;
- (id)initWithQueue:(id)arg1 storageProvider:(id)arg2 localStorageProvider:(id)arg3 largeMessageStorage:(id)arg4 delegate:(id)arg5;
- (void)listener:(id)arg1 largeMessageReceivedWithPath:(id)arg2 messageWrapper:(id)arg3 completion:(id /* block */)arg4;
- (void)listener:(id)arg1 messagesReceived:(id)arg2;
- (void)listener:(id)arg1 unresolvedMessagesReceived:(id)arg2;
- (id)postTransformationStream;
- (void)registerMessageResolver:(id)arg1;

@end
