/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAnalytics.framework/SiriAnalytics
 */

@interface AssistantSiriAnalytics : SiriAnalyticsClient {
    bool  _isInternalInstall;
}

+ (id)derivedIdentifierForComponent:(int)arg1 fromSourceIdentifier:(id)arg2;
+ (void)derivedIdentifierForComponent:(int)arg1 fromSourceIdentifier:(id)arg2 completion:(id /* block */)arg3;
+ (id)sharedAnalytics;
+ (id)sharedStream;

- (bool)clientMessageStream:(id)arg1 shouldEmitMessage:(id)arg2 timestamp:(unsigned long long)arg3 isolatedStreamUUID:(id)arg4;
- (id)init;

@end
