/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnitEnergy : NSDimension <NSSecureCoding>

// Image: /System/Library/Frameworks/Foundation.framework/Foundation

+ (id)_measurementWithNaturalScale:(id)arg1 system:(unsigned long long)arg2;
+ (id)baseUnit;
+ (id)calories;
+ (id)foodcalories;
+ (id)icuType;
+ (void)initialize;
+ (id)joules;
+ (id)kilocalories;
+ (id)kilojoules;
+ (id)kilowattHours;

// Image: /System/Library/Frameworks/Intents.framework/Intents

- (id)_intents_stringRepresentation;

// Image: /usr/lib/swift/libswiftFoundation.dylib

+ (bool)supportsRegionalPreference;

@end
