/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnitAcceleration : NSDimension <NSSecureCoding>

+ (id)baseUnit;
+ (id)gravity;
+ (id)icuType;
+ (void)initialize;
+ (id)metersPerSecondSquared;

@end
