/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TimeSync.framework/TimeSync
 */

@interface TSClockManager : NSObject {
    NSMutableArray * _clockPersonalities;
    IOKConnection * _connection;
    TSClock * _timeSyncClock;
    unsigned long long  _timeSyncTimeClockIdentifier;
    bool  _timeSyncTimeIsMachAbsoluteTime;
    struct mach_timebase_info { 
        unsigned int numer; 
        unsigned int denom; 
    }  _timebaseInfo;
    TSClock * _translationClock;
    unsigned long long  _translationClockIdentifier;
}

@property (nonatomic, readonly) TSClock *timeSyncClock;
@property (nonatomic, readonly) unsigned long long timeSyncTimeClockIdentifier;
@property (nonatomic, readonly) bool timeSyncTimeIsMachAbsoluteTime;
@property (nonatomic, readonly) TSClock *translationClock;
@property (nonatomic, readonly) unsigned long long translationClockIdentifier;

+ (id)clockManager;
+ (id)defaultClockPersonalities;
+ (id)diagnosticDescriptionForClockService:(id)arg1 withIndent:(id)arg2;
+ (id)diagnosticDescriptionForService:(id)arg1 withIndent:(id)arg2;
+ (id)diagnosticInfoForClockService:(id)arg1;
+ (id)diagnosticInfoForService:(id)arg1;
+ (void)notifyWhenClockManagerIsAvailable:(id /* block */)arg1;
+ (id)sharedClockManager;
+ (id)sharedClockManagerSyncWithTimeout:(unsigned long long)arg1;
+ (id)timeSyncAudioClockDeviceUIDForClockIdentifier:(unsigned long long)arg1;

- (void).cxx_destruct;
- (void)addClockPersonality:(id)arg1;
- (bool)addMappingFromClockID:(unsigned long long)arg1 toCoreAudioClockDomain:(unsigned int*)arg2 error:(id*)arg3;
- (bool)addTSNCaptureServicesWithError:(id*)arg1;
- (unsigned long long)addUserFilteredClockWithMachInterval:(unsigned long long)arg1 domainInterval:(unsigned long long)arg2 usingFilterShift:(unsigned char)arg3 isAdaptive:(bool)arg4 error:(id*)arg5;
- (bool)addgPTPServicesWithError:(id*)arg1;
- (id)availableClockIdentifiers;
- (id)clockWithClockIdentifier:(unsigned long long)arg1;
- (bool)getTimeSyncTimeClockID:(unsigned long long*)arg1 error:(id*)arg2;
- (bool)getTimeSyncTimeIsMachAbsolute:(bool*)arg1 error:(id*)arg2;
- (id)init;
- (unsigned long long)machAbsoluteNanosecondsToTicks:(unsigned long long)arg1;
- (unsigned long long)machAbsoluteTicksToNanoseconds:(unsigned long long)arg1;
- (unsigned long long)machAbsoluteToNanoseconds:(unsigned long long)arg1;
- (unsigned long long)nanosecondsToMachAbsolute:(unsigned long long)arg1;
- (bool)nextAvailableDynamicClockID:(unsigned long long*)arg1 error:(id*)arg2;
- (bool)releaseDynamicClockID:(unsigned long long)arg1 error:(id*)arg2;
- (void)removeClockPersonality:(id)arg1;
- (bool)removeMappingFromClockIDToCoreAudioClockDomainForClockID:(unsigned long long)arg1 error:(id*)arg2;
- (bool)removeTSNCaptureServicesWithError:(id*)arg1;
- (bool)removeUserFilteredClockWithIdentifier:(unsigned long long)arg1 error:(id*)arg2;
- (bool)removegPTPServicesWithError:(id*)arg1;
- (id)timeSyncClock;
- (unsigned long long)timeSyncTimeClockIdentifier;
- (bool)timeSyncTimeIsMachAbsoluteTime;
- (id)translationClock;
- (unsigned long long)translationClockIdentifier;

@end
