/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VirtualGarage.framework/VirtualGarage
 */

@interface VGExternalAccessoryModelFilter : NSObject {
    NSArray * _denylist;
    NSArray * _modelIdAllowlist;
}

- (void).cxx_destruct;
- (void)_initializeAllowAndDenylists;
- (bool)allowsVehicleWithModelId:(id)arg1 firmwareId:(id)arg2 year:(id)arg3 model:(id)arg4;
- (id)init;

@end
