/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CMKappaInternal : NSObject {
    id /* block */  fHandler;
    NSObject<OS_dispatch_queue> * fInternalQueue;
    void * fLocationdConnection;
    bool  fStartedUpdates;
}

- (void)_startKappaUpdatesForItem:(long long)arg1 withHandler:(id /* block */)arg2;
- (void)_stopKappaUpdates;
- (void)_teardown;
- (void)dealloc;
- (id)init;

@end
