/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Seeding.framework/Seeding
 */

@interface SDBetaManager : NSObject {
    NSArray * _cachedPrograms;
}

@property (nonatomic, retain) NSArray *cachedPrograms;

- (void).cxx_destruct;
- (id)cachedPrograms;
- (void)setCachedPrograms:(id)arg1;

@end
