/* Generated by RuntimeBrowser
   Image: /private/preboot/33FD5B12CB8382D8963CCA89BDF6ED3140E6264C13B157852B3EDED19A9499FFEE6D5C2AE20FAFD9095066EC6B7250C3/dopamine-xRaxOc/procursus/usr/lib/libellekit.dylib
 */

@interface ellekit.cbz : _TtCs12_SwiftObject {
    void value;
}

@end
