/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
 */

@interface ATAudioTap : NSObject {
    ATAudioTapDescription * _tapDescription;
}

@property (nonatomic, readonly) ATAudioTapDescription *tapDescription;

- (void).cxx_destruct;
- (id)initWithTapDescription:(id)arg1;
- (id)tapDescription;

@end
