/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
 */

@interface ATPhasePlatform : NSObject <PHASEPlatform> {
    struct unique_ptr<Phase::ServerManager, std::default_delete<Phase::ServerManager>> { 
        struct __compressed_pair<Phase::ServerManager *, std::default_delete<Phase::ServerManager>> { 
            struct ServerManager {} *__value_; 
        } __ptr_; 
    }  _serverManager;
    id  _sessionInterface;
}

@property (nonatomic, readonly) unsigned int bufferFrameSize;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool running;
@property (nonatomic, readonly) double sampleRate;
@property (nonatomic, readonly) <PHASESessionInterface> *sessionInterface;
@property (readonly) Class superclass;

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned int)bufferFrameSize;
- (void)dealloc;
- (unsigned int)deviceLatencyInFramesForDirection:(unsigned char)arg1;
- (bool)enableIO:(bool)arg1 direction:(unsigned char)arg2;
- (id)init;
- (void*)lazyInitServerManager;
- (id)lazyInitSessionInterface;
- (unsigned int)numberOfStreamsForDirection:(unsigned char)arg1;
- (bool)registerIOBlock:(id /* block */)arg1;
- (bool)registerOverloadNotification:(id /* block */)arg1;
- (bool)registerRouteChangeNotification:(id /* block */)arg1;
- (bool)running;
- (double)sampleRate;
- (id)sessionInterface;
- (bool)start;
- (bool)stop;
- (id)streamInfoForIndex:(unsigned int)arg1 direction:(unsigned char)arg2;

@end
