/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSDeviceOffersStore : NSObject <AMSDeviceOffersTracking> {
    AMSStorageDatabase * _database;
}

@property (nonatomic, retain) NSArray *cachedRegistrationGroups;
@property (nonatomic, readonly) NSArray *companionSerialNumbers;
@property (nonatomic, readonly) AMSStorageDatabase *database;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSDictionary *deviceOfferEligibility;
@property (nonatomic, retain) NSArray *deviceOffers;
@property (nonatomic, retain) NSArray *deviceRegistrationBlacklist;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)serialsBySubtractingAGroups:(id)arg1 fromBGroups:(id)arg2;
+ (id)serialsFromGroups:(id)arg1;
+ (id)splitGroups:(id)arg1 byItem:(id)arg2;

- (void).cxx_destruct;
- (void)_dbSetNullableValue:(id)arg1 forKey:(id)arg2 error:(id*)arg3;
- (id)_initWithDatabase:(id)arg1;
- (id)cachedRegistrationGroups;
- (id)companionSerialNumbers;
- (id)database;
- (id)deviceOfferEligibility;
- (id)deviceOffers;
- (id)deviceRegistrationBlacklist;
- (id)init;
- (void)removeCachedRegistrationItem:(id)arg1;
- (void)setCachedRegistrationGroups:(id)arg1;
- (void)setDeviceOfferEligibility:(id)arg1;
- (void)setDeviceOffers:(id)arg1;
- (void)setDeviceRegistrationBlacklist:(id)arg1;

@end
