/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSFraudScoreService : NSObject

+ (id)cacheFraudScore:(id)arg1 forPurchaseInfo:(id)arg2;
+ (id)cachedFraudScoreForPurchaseInfo:(id)arg1;
+ (id)didConsumeFraudScoreForPurchaseInfo:(id)arg1;
+ (id)generateFraudScoreForAction:(unsigned long long)arg1 account:(id)arg2 purchaseIdentifier:(id)arg3 logKey:(id)arg4;

@end
