/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSGenerateFraudScoreTask : AMSTask {
    ACAccount * _account;
    unsigned long long  _action;
    <AMSBagProtocol> * _bag;
    NSString * _logKey;
    NSNumber * _purchaseIdentifier;
}

@property (nonatomic, readonly) ACAccount *account;
@property (nonatomic, readonly) unsigned long long action;
@property (nonatomic, readonly) <AMSBagProtocol> *bag;
@property (nonatomic, readonly) bool deviceSupportsFraudScores;
@property (nonatomic, readonly) bool deviceSupportsFraudScoresV2;
@property (nonatomic, readonly) NSString *logKey;
@property (nonatomic, readonly) NSNumber *purchaseIdentifier;

+ (bool)deviceSupportsFraudScoresV2WithBag:(id)arg1 logKey:(id)arg2;

- (void).cxx_destruct;
- (id)account;
- (unsigned long long)action;
- (id)bag;
- (bool)deviceSupportsFraudScores;
- (bool)deviceSupportsFraudScoresV2;
- (id)initWithAction:(unsigned long long)arg1 account:(id)arg2 purchaseIdentifier:(id)arg3 bag:(id)arg4 logKey:(id)arg5;
- (id)initWithPurchaseInfo:(id)arg1 bag:(id)arg2;
- (id)logKey;
- (id)purchaseIdentifier;
- (id)runTask;

@end
