/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMImaging.framework/CMImaging
 */

@interface FigRegWarpPPGPU : NSObject {
    struct { 
        struct { 
            unsigned int x; 
            unsigned int y; 
            unsigned int width; 
            unsigned int height; 
        } roi; 
        struct { 
            float normX[2]; 
            float normY[2]; 
            float inverseX[2]; 
            float inverseY[2]; 
        } normCoef; 
        float minNCCThreshold; 
        short minCornerResponseThreshold; 
    }  _cornerMatchingParams;
    unsigned int  _imageHeight;
    unsigned int  _imageWidth;
    float  _inlierThreshold;
    FigMetalContext * _metal;
    <MTLBuffer> * _nonReferencePyramidCorners;
    <MTLTexture> * _nonReferencePyramidImage;
    struct { 
        float normX[2]; 
        float normY[2]; 
        float inverseX[2]; 
        float inverseY[2]; 
    }  _normCoefs;
    unsigned int  _numPyrLevels;
    struct { 
        unsigned int w; 
        unsigned int h; 
    }  _pyramidLevelsDim;
    struct { 
        unsigned int x; 
        unsigned int y; 
        unsigned int width; 
        unsigned int height; 
    }  _pyramidLevelsRoi;
    <MTLBuffer> * _referencePyramidCorners;
    <MTLTexture> * _referencePyramidImage;
    struct { 
        unsigned int x; 
        unsigned int y; 
        unsigned int width; 
        unsigned int height; 
    }  _roi;
    FigRegWarpPPGPUShaders * _shaders;
    bool  _skipInitialDownsample;
}

- (void).cxx_destruct;
- (int)_constructPyramid:(id*)arg1 withTexture:(id)arg2 mapping:(struct { unsigned char x1[256]; }*)arg3 level0Only:(bool)arg4;
- (int)_convertTransform:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[3]; })arg1 toGPUTransform:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[3]; }*)arg2;
- (int)_detectCorners:(id)arg1 roi:(struct { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; })arg2 corners:(id)arg3;
- (int)_setDefaultCornerMatchingParams;
- (int)_setNormCoefs:(struct { float x1[2]; float x2[2]; float x3[2]; float x4[2]; }*)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3;
- (int)_updatePyramidRoi;
- (int)_verifyInputPixelFormat:(unsigned long long)arg1;
- (int)allocateResourcesWithWidth:(unsigned int)arg1 height:(unsigned int)arg2;
- (void)dealloc;
- (id)initWithMetalContext:(id)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3 skipInitialDownsample:(bool)arg4;
- (int)processNonReference:(id)arg1 outputTransform:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[3]; }*)arg2 mapping:(struct { unsigned char x1[256]; }*)arg3;
- (int)processReference:(id)arg1 regionOfInterest:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg2 numKeypoints:(unsigned int*)arg3 mapping:(struct { unsigned char x1[256]; }*)arg4;

@end
