/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
 */

@interface AKPrivateEmailContext : NSObject <NSSecureCoding> {
    NSString * _altDSID;
    NSString * _key;
    NSString * _proxiedAppID;
    NSString * _proxiedAppName;
    NSString * _proxiedBundleIdentifier;
    NSString * _upgradeBundleIdentifier;
}

@property (nonatomic, readonly, copy) NSString *altDSID;
@property (nonatomic, readonly, copy) NSString *key;
@property (nonatomic, copy) NSString *proxiedAppID;
@property (nonatomic, copy) NSString *proxiedAppName;
@property (nonatomic, copy) NSString *proxiedBundleIdentifier;
@property (nonatomic, readonly, copy) NSString *upgradeBundleIdentifier;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)altDSID;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithContext:(id)arg1 bundleID:(id)arg2;
- (id)initWithContext:(id)arg1 client:(id)arg2;
- (id)initWithKey:(id)arg1;
- (id)initWithKey:(id)arg1 altDSID:(id)arg2;
- (id)key;
- (id)proxiedAppID;
- (id)proxiedAppName;
- (id)proxiedBundleIdentifier;
- (void)setProxiedAppID:(id)arg1;
- (void)setProxiedAppName:(id)arg1;
- (void)setProxiedBundleIdentifier:(id)arg1;
- (id)upgradeBundleIdentifier;

@end
