/* Generated by RuntimeBrowser.
 */

@protocol _UIKeyShortcutHUDViewControllerDelegate

@required

- (void)keyShortcutHUDViewController:(_UIKeyShortcutHUDViewController *)arg1 didSelectKeyCommand:(UIKeyCommand *)arg2 withOriginalTarget:(id)arg3;
- (void)keyShortcutHUDViewControllerDidBeginTypeAheadSearch:(_UIKeyShortcutHUDViewController *)arg1;
- (void)keyShortcutHUDViewControllerDidRequestDismissal:(_UIKeyShortcutHUDViewController *)arg1;

@end
