/* Generated by RuntimeBrowser.
 */

@protocol _UITextContent <NSObject>

@required

- (NSTextContainer *)textContainer;
- (_UITextLayoutController *)textLayoutController;
- (NSTextStorage *)textStorage;

@end
