/* Generated by RuntimeBrowser.
 */

@protocol AATrustedContactPresenterHostProtocol <NSObject>

@required

- (void)trustedContactRequestFinishedWithError:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 7: NSError *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
