/* Generated by RuntimeBrowser.
 */

@protocol BWDeferredProcessorControllerDelegate <BWStillImageProcessorControllerDelegate>

@required

- (void)processorController:(BWDeferredProcessorController *)arg1 didDetermineReferenceFrame:(struct opaqueCMSampleBuffer { }*)arg2 processorInput:(BWDeferredProcessorControllerInput *)arg3 err:(int)arg4;
- (void)processorController:(BWDeferredProcessorController *)arg1 didProcessInferencesForSkinMask:(const void*)arg2 skyMask:(const void*)arg3 lowResPersonMask:(const void*)arg4 personMask:(const void*)arg5 lowResPersonInstanceMasks:(id)arg6 lowResPersonInstanceConfidences:(id)arg7 lowResPersonInstanceBoundingBoxes:(id)arg8 skinToneClassifications:(id)arg9 inferenceAttachedMediaMetadata:(NSDictionary *)arg10 faceObservations:(id)arg11 processorInput:(BWDeferredProcessorControllerInput *)arg12 err:(int)arg13;

@end
