/* Generated by RuntimeBrowser.
 */

@protocol CARPFObject <NSObject>

@required

+ (NSString *)carpf_shortDescription;

- (NSString *)carpf_privateDescription;
- (NSString *)carpf_shortDescription;

@optional

- (NSArray *)attributeDescriptions;
- (NSString *)propertyDescription;

@end
