/* Generated by RuntimeBrowser.
 */

@protocol LSInstallationServiceProtocol <NSObject>

@required

- (void)performInstallCall:(void *)arg1 withOptions:(void *)arg2 installType:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 11: <LSMIInstallCall> *, NSDictionary *, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, LSRecordPromise *, NSError *, void*
- (void)performUninstallCall:(void *)arg1 withOptions:(void *)arg2 uninstallType:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: <LSMIUninstallCall> *, NSDictionary *, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*

@end
