/* Generated by RuntimeBrowser.
 */

@protocol MNVirtualGarageProvider <NSObject>

@required

- (void)setVirtualGarageDelegate:(id <MNVirtualGarageProviderDelegate>)arg1;
- (void)startVirtualGarageUpdates;
- (void)stopVirtualGarageUpdates;
- (<MNVirtualGarageProviderDelegate> *)virtualGarageDelegate;

@end
