/* Generated by RuntimeBrowser.
 */

@protocol NWURLSessionResponseConsumer <NSObject>

@required

- (void)deliverData:(void *)arg1 complete:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 7: NSObject<OS_dispatch_data> *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (void)deliverResponse:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: NSURLResponse *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, long long, void*
- (NSURLResponse *)response;

@end
