/* Generated by RuntimeBrowser.
 */

@protocol SHSheetSessionDelegate <NSObject>

@required

- (void)sessionConfigurationDidChangeForSession:(SHSheetSession *)arg1;
- (void)wantsObjectManipulationDidChangeForSession:(SHSheetSession *)arg1;

@end
