/* Generated by RuntimeBrowser.
 */

@protocol SHSheetContentViewInterface <NSObject>

@required

- (double)customViewControllerVerticalInset;
- (LPLinkMetadata *)headerMetadata;
- (UIViewController *)photosCarouselViewController;
- (<SHSheetContentPresenterInterface> *)presenter;
- (void)refreshContent;
- (void)reloadActivity:(UIActivity *)arg1;
- (void)setCustomViewControllerVerticalInset:(double)arg1;
- (void)setPhotosCarouselViewController:(UIViewController *)arg1;
- (void)setPresenter:(id <SHSheetContentPresenterInterface>)arg1;
- (void)setWantsObjectManipulation:(bool)arg1;
- (void)updateContentWithPeopleProxies:(NSArray *)arg1 shareProxies:(NSArray *)arg2 actionProxies:(NSArray *)arg3 activitiesByUUID:(NSDictionary *)arg4 nearbyCountSlotID:(NSNumber *)arg5 animated:(bool)arg6 reloadData:(bool)arg7;
- (void)updateHeaderMetadata;
- (void)updateHeaderSize;
- (void)updateProgress:(double)arg1 withTopText:(NSNumber *)arg2 bottomText:(NSNumber *)arg3 forNodeWithIdentifier:(NSUUID *)arg4 shouldPulse:(bool)arg5 animated:(bool)arg6;
- (void)updateWithViewModel:(id <SHSheetViewModelInterface>)arg1;
- (bool)wantsObjectManipulation;

@end
