/* Generated by RuntimeBrowser.
 */

@protocol SHSheetUIPeopleSuggestion <NSObject>

@required

- (NSArray *)contacts;
- (NSString *)displayName;
- (INImage *)donatedImage;
- (NSString *)identifier;
- (bool)isRestricted;
- (NSArray *)recipientsHandles;
- (NSString *)transportBundleIdentifier;

@end
