/* Generated by RuntimeBrowser.
 */

@protocol SHSheetViewModelInterface <NSObject>

@required

- (NSArray *)activities;
- (NSString *)customOptionsTitle;
- (NSArray *)metadataValues;
- (NSArray *)peopleSuggestions;
- (NSArray *)restrictedActivityTypes;
- (void)setCustomOptionsTitle:(NSString *)arg1;
- (void)setRestrictedActivityTypes:(NSArray *)arg1;
- (bool)showOptions;

@end
