/* Generated by RuntimeBrowser.
 */

@protocol SiriAnalyticsXPCService <NSObject>

@required

- (oneway void)publishLargeMessage:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: SiriAnalyticsXPCLargeMessageEnvelope *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (oneway void)publishMessages:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 6: NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (oneway void)resolveMessages:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 6: NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*

@end
