/* Generated by RuntimeBrowser.
 */

@protocol UISDrawing <NSObject>

@required

- (void)drawInContext:(struct CGContext { }*)arg1 atPoint:(struct CGPoint { double x1; double x2; })arg2;
- (struct CGSize { double x1; double x2; })drawingSize;

@end
