/* Generated by RuntimeBrowser.
 */

@protocol VKPuckAnimatorDelegate <NSObject>

@required

- (void)puckAnimator:(VKPuckAnimator *)arg1 getElevation:(double*)arg2 withCoordinate:(const void*)arg3;
- (void)puckAnimator:(VKPuckAnimator *)arg1 runAnimation:(VKAnimation *)arg2;
- (void)puckAnimator:(VKPuckAnimator *)arg1 updatedPosition:(const void*)arg2 course:(const void*)arg3;
- (void)puckAnimator:(VKPuckAnimator *)arg1 updatedTargetPosition:(const void*)arg2;
- (void)puckAnimatorDidStop:(VKPuckAnimator *)arg1;

@end
