/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CallKit.framework/CallKit
 */

@interface CXJoinCallAction : CXCallAction {
    CXHandle * _callerID;
    NSString * _conversationProviderIdentifier;
    NSDate * _dateStarted;
    NSUUID * _groupUUID;
    CXJoinCallActivity * _joinCallActivity;
    bool  _joiningConversationWithLink;
    bool  _letMeIn;
    NSString * _messagesGroupName;
    NSUUID * _messagesGroupUUID;
    NSDictionary * _notificationStylesByHandleType;
    NSSet * _otherInvitedHandles;
    NSString * _pseudonym;
    NSData * _publicKey;
    bool  _relay;
    NSSet * _remoteMembers;
    NSSet * _remotePushTokens;
    bool  _shouldSuppressInCallUI;
    bool  _upgrade;
    NSUUID * _upgradeSessionUUID;
    bool  _uplinkMuted;
    bool  _video;
    bool  _videoEnabled;
    bool  _wantsStagingArea;
}

@property (nonatomic, copy) CXHandle *callerID;
@property (nonatomic, copy) NSString *conversationProviderIdentifier;
@property (nonatomic, copy) NSDate *dateStarted;
@property (nonatomic, copy) NSUUID *groupUUID;
@property (nonatomic, copy) CXJoinCallActivity *joinCallActivity;
@property (getter=isJoiningConversationWithLink, nonatomic) bool joiningConversationWithLink;
@property (getter=isLetMeIn, nonatomic) bool letMeIn;
@property (nonatomic, copy) NSString *messagesGroupName;
@property (nonatomic, copy) NSUUID *messagesGroupUUID;
@property (nonatomic, copy) NSDictionary *notificationStylesByHandleType;
@property (nonatomic, copy) NSSet *otherInvitedHandles;
@property (nonatomic, copy) NSString *pseudonym;
@property (nonatomic, copy) NSData *publicKey;
@property (getter=isRelay, nonatomic) bool relay;
@property (nonatomic, copy) NSSet *remoteMembers;
@property (nonatomic, copy) NSSet *remotePushTokens;
@property (nonatomic) bool shouldSuppressInCallUI;
@property (getter=isUpgrade, nonatomic) bool upgrade;
@property (nonatomic, copy) NSUUID *upgradeSessionUUID;
@property (getter=isUplinkMuted, nonatomic) bool uplinkMuted;
@property (getter=isVideo, nonatomic) bool video;
@property (getter=isVideoEnabled, nonatomic) bool videoEnabled;
@property (nonatomic) bool wantsStagingArea;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)callerID;
- (id)conversationProviderIdentifier;
- (id)customDescription;
- (id)dateStarted;
- (void)encodeWithCoder:(id)arg1;
- (void)fulfill;
- (void)fulfillWithDateStarted:(id)arg1;
- (id)groupUUID;
- (id)initWithCallUUID:(id)arg1 groupUUID:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (bool)isJoiningConversationWithLink;
- (bool)isLetMeIn;
- (bool)isRelay;
- (bool)isUpgrade;
- (bool)isUplinkMuted;
- (bool)isVideo;
- (bool)isVideoEnabled;
- (id)joinCallActivity;
- (id)messagesGroupName;
- (id)messagesGroupUUID;
- (id)notificationStylesByHandleType;
- (id)otherInvitedHandles;
- (id)pseudonym;
- (id)publicKey;
- (id)remoteMembers;
- (id)remotePushTokens;
- (id)sanitizedCopyWithZone:(struct _NSZone { }*)arg1;
- (void)setCallerID:(id)arg1;
- (void)setConversationProviderIdentifier:(id)arg1;
- (void)setDateStarted:(id)arg1;
- (void)setGroupUUID:(id)arg1;
- (void)setJoinCallActivity:(id)arg1;
- (void)setJoiningConversationWithLink:(bool)arg1;
- (void)setLetMeIn:(bool)arg1;
- (void)setMessagesGroupName:(id)arg1;
- (void)setMessagesGroupUUID:(id)arg1;
- (void)setNotificationStylesByHandleType:(id)arg1;
- (void)setOtherInvitedHandles:(id)arg1;
- (void)setPseudonym:(id)arg1;
- (void)setPublicKey:(id)arg1;
- (void)setRelay:(bool)arg1;
- (void)setRemoteMembers:(id)arg1;
- (void)setRemotePushTokens:(id)arg1;
- (void)setShouldSuppressInCallUI:(bool)arg1;
- (void)setUpgrade:(bool)arg1;
- (void)setUpgradeSessionUUID:(id)arg1;
- (void)setUplinkMuted:(bool)arg1;
- (void)setVideo:(bool)arg1;
- (void)setVideoEnabled:(bool)arg1;
- (void)setWantsStagingArea:(bool)arg1;
- (bool)shouldSuppressInCallUI;
- (void)updateAsFulfilledWithDateStarted:(id)arg1;
- (void)updateCopy:(id)arg1 withZone:(struct _NSZone { }*)arg2;
- (id)upgradeSessionUUID;
- (bool)wantsStagingArea;

@end
