/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface _TIPreference : NSObject {
    id  _currentValue;
    id  _defaultValue;
    NSString * _domain;
    NSString * _fallbackKey;
    bool  _isAnalyzed;
    NSString * _key;
}

@property (nonatomic, readonly) NSString *analyzedAtKey;
@property (nonatomic, readonly) NSString *buildAtChangeKey;
@property (nonatomic, readonly) NSString *changedAtKey;
@property (nonatomic, retain) id currentValue;
@property (nonatomic, retain) id defaultValue;
@property (nonatomic, retain) NSString *domain;
@property (nonatomic, retain) NSString *fallbackKey;
@property (nonatomic) bool isAnalyzed;
@property (nonatomic, retain) NSString *key;
@property (nonatomic, readonly) NSString *previousValueKey;

+ (id)preferenceWithKey:(id)arg1 domain:(id)arg2 defaultValue:(id)arg3;
+ (id)preferenceWithKey:(id)arg1 domain:(id)arg2 defaultValue:(id)arg3 fallbackKey:(id)arg4;
+ (id)preferenceWithKey:(id)arg1 domain:(id)arg2 defaultValue:(id)arg3 fallbackKey:(id)arg4 isAnalyzed:(bool)arg5;

- (void).cxx_destruct;
- (id)analyzedAtKey;
- (id)buildAtChangeKey;
- (id)changedAtKey;
- (id)currentValue;
- (id)defaultValue;
- (id)domain;
- (id)fallbackKey;
- (bool)isAnalyzed;
- (id)key;
- (id)previousValueKey;
- (void)setCurrentValue:(id)arg1;
- (void)setDefaultValue:(id)arg1;
- (void)setDomain:(id)arg1;
- (void)setFallbackKey:(id)arg1;
- (void)setIsAnalyzed:(bool)arg1;
- (void)setKey:(id)arg1;

@end
