/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TITraceLogCandidate : NSObject <TITraceLogCandidateExportRepresenting> {
    double  _contextProbability;
    NSString * _filterName;
    NSString * _lexiconLocaleIdentifier;
    NSString * _metadataString;
    double  _probability;
    NSString * _token;
    unsigned int  _wordId;
}

@property (nonatomic) double contextProbability;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDictionary *dictionaryRepresentation;
@property (nonatomic, retain) NSString *filterName;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *lexiconLocaleIdentifier;
@property (nonatomic, retain) NSString *metadataString;
@property (nonatomic) double probability;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSString *token;
@property (nonatomic) unsigned int wordId;

+ (id)candidateFromCandidateString:(id)arg1;
+ (id)candidateFromFinalCandidateString:(id)arg1;
+ (id)candidateFromRemovedCandidateString:(id)arg1;

- (void).cxx_destruct;
- (double)contextProbability;
- (id)dictionaryRepresentation;
- (id)filterName;
- (id)lexiconLocaleIdentifier;
- (id)metadataString;
- (double)probability;
- (void)setContextProbability:(double)arg1;
- (void)setFilterName:(id)arg1;
- (void)setLexiconLocaleIdentifier:(id)arg1;
- (void)setMetadataString:(id)arg1;
- (void)setProbability:(double)arg1;
- (void)setToken:(id)arg1;
- (void)setWordId:(unsigned int)arg1;
- (id)token;
- (unsigned int)wordId;

@end
