/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TITraceLogRecord : NSObject {
    NSArray * _finalAutocorrectionCandidates;
    NSArray * _finalCompletionCandidates;
    NSArray * _finalPredictionCandidates;
    NSMutableArray * _parsedSections;
    NSArray * _rawAutocorrectionCandidates;
    NSArray * _rawCompletionCandidates;
    NSArray * _rawPredictionCandidates;
    NSString * _recordType;
    NSUUID * _recordUUID;
    NSArray * _removedAutocorrectionCandidates;
    NSArray * _removedCompletionCandidates;
    NSArray * _removedPredictionCandidates;
    NSString * _typedString;
}

@property (nonatomic, retain) NSArray *finalAutocorrectionCandidates;
@property (nonatomic, retain) NSArray *finalCompletionCandidates;
@property (nonatomic, retain) NSArray *finalPredictionCandidates;
@property (nonatomic, readonly, retain) NSArray *parsedSections;
@property (nonatomic, retain) NSArray *rawAutocorrectionCandidates;
@property (nonatomic, retain) NSArray *rawCompletionCandidates;
@property (nonatomic, retain) NSArray *rawPredictionCandidates;
@property (nonatomic, retain) NSString *recordType;
@property (nonatomic, retain) NSUUID *recordUUID;
@property (nonatomic, retain) NSArray *removedAutocorrectionCandidates;
@property (nonatomic, retain) NSArray *removedCompletionCandidates;
@property (nonatomic, retain) NSArray *removedPredictionCandidates;
@property (nonatomic, retain) NSString *typedString;

- (void).cxx_destruct;
- (void)addParsedSection:(id)arg1;
- (id)finalAutocorrectionCandidates;
- (id)finalCompletionCandidates;
- (id)finalPredictionCandidates;
- (id)initWithRecordUUID:(id)arg1;
- (id)parsedSections;
- (id)rawAutocorrectionCandidates;
- (id)rawCompletionCandidates;
- (id)rawPredictionCandidates;
- (id)recordType;
- (id)recordUUID;
- (id)removedAutocorrectionCandidates;
- (id)removedCompletionCandidates;
- (id)removedPredictionCandidates;
- (void)setFinalAutocorrectionCandidates:(id)arg1;
- (void)setFinalCompletionCandidates:(id)arg1;
- (void)setFinalPredictionCandidates:(id)arg1;
- (void)setRawAutocorrectionCandidates:(id)arg1;
- (void)setRawCompletionCandidates:(id)arg1;
- (void)setRawPredictionCandidates:(id)arg1;
- (void)setRecordType:(id)arg1;
- (void)setRecordUUID:(id)arg1;
- (void)setRemovedAutocorrectionCandidates:(id)arg1;
- (void)setRemovedCompletionCandidates:(id)arg1;
- (void)setRemovedPredictionCandidates:(id)arg1;
- (void)setTypedString:(id)arg1;
- (id)typedString;

@end
