/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@interface CTCellularQoSFlow : NSObject <NSCopying, NSSecureCoding> {
    unsigned long long  _flowId;
    CTQoS * _rxQos;
    CTQoS * _txQos;
}

@property (nonatomic) unsigned long long flowId;
@property (nonatomic, retain) CTQoS *rxQos;
@property (nonatomic, retain) CTQoS *txQos;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)flowId;
- (id)initWithCoder:(id)arg1;
- (id)rxQos;
- (void)setFlowId:(unsigned long long)arg1;
- (void)setRxQos:(id)arg1;
- (void)setTxQos:(id)arg1;
- (id)txQos;

@end
