/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OSAnalytics.framework/OSAnalytics
 */

@interface OSASafeCreateDirectoryOptions : NSObject {
    bool  _createIntermediates;
    bool  _fileProtectionNone;
    NSNumber * _groupID;
}

@property bool createIntermediates;
@property bool fileProtectionNone;
@property (copy) NSNumber *groupID;

- (void).cxx_destruct;
- (bool)createIntermediates;
- (bool)fileProtectionNone;
- (id)groupID;
- (void)setCreateIntermediates:(bool)arg1;
- (void)setFileProtectionNone:(bool)arg1;
- (void)setGroupID:(id)arg1;

@end
