/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEAppInfoCache : NSObject {
    NSObject<OS_dispatch_queue> * _cacheQueue;
    NSMutableDictionary * _cachedSourceAppInfo;
    <NEAppInfoCacheLookupDelegate> * _lookupDelegate;
}

@property (readonly) NSObject<OS_dispatch_queue> *cacheQueue;
@property (retain) NSMutableDictionary *cachedSourceAppInfo;
@property <NEAppInfoCacheLookupDelegate> *lookupDelegate;

+ (id)sharedAppInfoCache;

- (void).cxx_destruct;
- (void)addAppInfoToCache:(id)arg1;
- (bool)appInfo:(id)arg1 mismatchedWithUUID:(id)arg2 andBundleID:(id)arg3;
- (bool)appInfo:(id)arg1 shouldOverwriteAppInfo:(id)arg2;
- (void)appInfoForPid:(int)arg1 UUID:(id)arg2 bundleID:(id)arg3 completionHandler:(id /* block */)arg4;
- (bool)bundleID:(id)arg1 matchesBundleID:(id)arg2;
- (id)bundleIDWithoutTeamID:(id)arg1;
- (id)cacheQueue;
- (id)cachedSourceAppInfo;
- (id)init;
- (id)lookupAppInfoForPid:(int)arg1 bundleID:(id)arg2;
- (id)lookupDelegate;
- (void)performCustomLookupIfNecessaryForPid:(int)arg1 UUID:(id)arg2 bundleID:(id)arg3 completionHandler:(id /* block */)arg4;
- (bool)setAppInfo:(id)arg1 forUUID:(id)arg2;
- (void)setCachedSourceAppInfo:(id)arg1;
- (void)setLookupDelegate:(id)arg1;

@end
