/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NETrie : NSObject {
    bool  _partialSearchAllowed;
    BOOL  _partialSearchTerminator;
    bool  _reverse;
    struct ne_trie { 
        unsigned long long magic; 
        unsigned long long version; 
        struct ne_trie_node {} *nodes; 
        unsigned short *child_maps; 
        char *bytes; 
        void *memory; 
        unsigned short nodes_count; 
        unsigned short child_maps_count; 
        unsigned short bytes_count; 
        unsigned short nodes_free_next; 
        unsigned short child_maps_free_next; 
        unsigned short bytes_free_next; 
        unsigned short root; 
        unsigned long long trie_memory_size; 
        unsigned long long nodes_mem_size; 
        unsigned long long child_maps_mem_size; 
        unsigned long long bytes_mem_size; 
        bool is_mmap; 
        double timestamp; 
    }  _trie;
}

@property bool partialSearchAllowed;
@property BOOL partialSearchTerminator;
@property bool reverse;
@property struct ne_trie { unsigned long long x1; unsigned long long x2; struct ne_trie_node {} *x3; unsigned short *x4; char *x5; void *x6; unsigned short x7; unsigned short x8; unsigned short x9; unsigned short x10; unsigned short x11; unsigned short x12; unsigned short x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; bool x18; double x19; } trie;

- (void)dealloc;
- (id)initWithDomains:(id)arg1 reverse:(bool)arg2 partialSearchAllowed:(bool)arg3 partialSearchTerminator:(BOOL)arg4;
- (bool)partialSearchAllowed;
- (BOOL)partialSearchTerminator;
- (bool)reverse;
- (bool)search:(const char *)arg1 length:(int)arg2;
- (bool)searchWithString:(id)arg1;
- (void)setPartialSearchAllowed:(bool)arg1;
- (void)setPartialSearchTerminator:(BOOL)arg1;
- (void)setReverse:(bool)arg1;
- (void)setTrie:(struct ne_trie { unsigned long long x1; unsigned long long x2; struct ne_trie_node {} *x3; unsigned short *x4; char *x5; void *x6; unsigned short x7; unsigned short x8; unsigned short x9; unsigned short x10; unsigned short x11; unsigned short x12; unsigned short x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; bool x18; double x19; })arg1;
- (struct ne_trie { unsigned long long x1; unsigned long long x2; struct ne_trie_node {} *x3; unsigned short *x4; char *x5; void *x6; unsigned short x7; unsigned short x8; unsigned short x9; unsigned short x10; unsigned short x11; unsigned short x12; unsigned short x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; bool x18; double x19; })trie;

@end
