/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKLogicalDeviceContext : NSObject {
    CKLogicalDeviceScopedDaemonProxy * _deviceScopedDaemonProxy;
    CKLogicalDeviceScopedStateManager * _deviceScopedStateManager;
    CKTestDevice * _testDevice;
    CKTestDeviceReference * _testDeviceReference;
    CKThrottleManager * _throttleManager;
}

@property (nonatomic, retain) CKLogicalDeviceScopedDaemonProxy *deviceScopedDaemonProxy;
@property (nonatomic, retain) CKLogicalDeviceScopedStateManager *deviceScopedStateManager;
@property (nonatomic, retain) CKTestDevice *testDevice;
@property (nonatomic, readonly) CKTestDeviceReference *testDeviceReference;
@property (nonatomic, retain) CKThrottleManager *throttleManager;
@property (nonatomic, readonly) bool wantsFlowControl;

+ (id)defaultContext;
+ (id)deviceContextForTestDeviceReference:(id)arg1;

- (void).cxx_destruct;
- (id)_initWithTestDeviceReference:(id)arg1;
- (id)deviceScopedDaemonProxy;
- (id)deviceScopedStateManager;
- (void)setDeviceScopedDaemonProxy:(id)arg1;
- (void)setDeviceScopedStateManager:(id)arg1;
- (void)setTestDevice:(id)arg1;
- (void)setThrottleManager:(id)arg1;
- (id)testDevice;
- (id)testDeviceReference;
- (id)throttleManager;
- (bool)wantsFlowControl;

@end
