/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKRecordZoneID : NSObject <CKPropertiesDescription, CKSQLiteItem, CKXPCSuitableString, NSCopying, NSSecureCoding> {
    NSString * _anonymousCKUserID;
    NSString * _ownerName;
    NSString * _zoneName;
}

@property (nonatomic, copy) NSString *anonymousCKUserID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSString *ownerName;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSString *zoneName;

+ (id)cachedRecordZoneIDWithName:(id)arg1 ownerName:(id)arg2 anonymousCKUserID:(id)arg3;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)CKDescribePropertiesUsing:(id)arg1;
- (id)CKShortDescriptionRedact:(bool)arg1;
- (id)CKXPCSuitableString;
- (id)_initWithZoneName:(id)arg1 ownerName:(id)arg2 anonymousCKUserID:(id)arg3;
- (id)anonymousCKUserID;
- (id)ckShortDescription;
- (void)ck_bindInStatement:(id)arg1 atIndex:(unsigned long long)arg2;
- (long long)compareToRecordZoneID:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithSqliteRepresentation:(id)arg1;
- (id)initWithZoneName:(id)arg1 ownerName:(id)arg2;
- (id)initWithZoneName:(id)arg1 ownerName:(id)arg2 anonymousCKUserID:(id)arg3;
- (bool)isDefaultRecordZoneID;
- (bool)isEqual:(id)arg1;
- (bool)isSystemRecordZoneID;
- (id)ownerName;
- (id)redactedDescription;
- (void)setAnonymousCKUserID:(id)arg1;
- (id)sqliteRepresentation;
- (id)zoneName;

@end
