/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKRecordID : NSObject <CKPropertiesDescription, CKSQLiteItem, CKXPCSuitableString, NSCopying, NSSecureCoding> {
    NSString * _recordName;
    CKRecordZoneID * _zoneID;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSString *recordName;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) CKRecordZoneID *zoneID;

+ (bool)isValidRecordName:(id)arg1 outError:(id*)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)CKDescribePropertiesUsing:(id)arg1;
- (id)CKShortDescriptionRedact:(bool)arg1;
- (id)CKXPCSuitableString;
- (void)_nilOutRecordName;
- (id)ckShortDescription;
- (void)ck_bindInStatement:(id)arg1 atIndex:(unsigned long long)arg2;
- (long long)compareToRecordID:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithRecordName:(id)arg1;
- (id)initWithRecordName:(id)arg1 zoneID:(id)arg2;
- (id)initWithSqliteRepresentation:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualIgnoringAnonymousUserIDsToRecordID:(id)arg1;
- (id)recordName;
- (id)redactedDescription;
- (id)sqliteRepresentation;
- (id)zoneID;

@end
