/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKSubscription : NSObject <NSCopying, NSSecureCoding> {
    CKNotificationInfo * _notificationInfo;
    NSString * _recordType;
    NSString * _subscriptionID;
    long long  _subscriptionType;
}

@property (nonatomic, copy) CKNotificationInfo *notificationInfo;
@property (nonatomic, copy) NSString *recordType;
@property (nonatomic, copy) NSString *subscriptionID;
@property (nonatomic) long long subscriptionType;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_initWithSubscriptionID:(id)arg1 subscriptionType:(long long)arg2 recordType:(id)arg3;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)debugDescription;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithRecordType:(id)arg1 predicate:(id)arg2 options:(unsigned long long)arg3;
- (id)initWithRecordType:(id)arg1 predicate:(id)arg2 subscriptionID:(id)arg3 options:(unsigned long long)arg4;
- (id)initWithZoneID:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithZoneID:(id)arg1 subscriptionID:(id)arg2 options:(unsigned long long)arg3;
- (bool)isEqual:(id)arg1;
- (id)notificationInfo;
- (id)predicate;
- (id)recordType;
- (void)setNotificationInfo:(id)arg1;
- (void)setRecordType:(id)arg1;
- (void)setSubscriptionID:(id)arg1;
- (void)setSubscriptionType:(long long)arg1;
- (id)subscriptionID;
- (unsigned long long)subscriptionOptions;
- (long long)subscriptionType;
- (id)zoneID;

@end
