/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKSyncEngineConfiguration : NSObject <CKPropertiesDescription> {
    NSString * _apsMachServiceName;
    bool  _automaticSyncingEnabled;
    <CKSyncEngineDataSource> * _dataSource;
    CKDatabase * _database;
    NSString * _databaseSubscriptionIDOverride;
    bool  _ignoreSystemConditions;
    NSData * _metadata;
    long long  _priority;
    bool  _useUniqueActivityIdentifiers;
    NSObject<OS_xpc_object> * _xpcActivityCriteriaOverrides;
}

@property (nonatomic, retain) NSString *apsMachServiceName;
@property (nonatomic) bool automaticSyncingEnabled;
@property (nonatomic) <CKSyncEngineDataSource> *dataSource;
@property (nonatomic, retain) CKDatabase *database;
@property (nonatomic, retain) NSString *databaseSubscriptionIDOverride;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool ignoreSystemConditions;
@property (nonatomic, retain) NSData *metadata;
@property (nonatomic) long long priority;
@property (readonly) Class superclass;
@property (nonatomic) bool useUniqueActivityIdentifiers;
@property (nonatomic, retain) NSObject<OS_xpc_object> *xpcActivityCriteriaOverrides;

- (void).cxx_destruct;
- (void)CKDescribePropertiesUsing:(id)arg1;
- (id)apsMachServiceName;
- (bool)automaticSyncingEnabled;
- (id)dataSource;
- (id)database;
- (id)databaseSubscriptionIDOverride;
- (id)description;
- (bool)ignoreSystemConditions;
- (id)init;
- (id)initWithDatabase:(id)arg1 dataSource:(id)arg2 metadata:(id)arg3;
- (id)metadata;
- (long long)priority;
- (id)redactedDescription;
- (void)setApsMachServiceName:(id)arg1;
- (void)setAutomaticSyncingEnabled:(bool)arg1;
- (void)setDataSource:(id)arg1;
- (void)setDatabase:(id)arg1;
- (void)setDatabaseSubscriptionIDOverride:(id)arg1;
- (void)setIgnoreSystemConditions:(bool)arg1;
- (void)setMetadata:(id)arg1;
- (void)setPriority:(long long)arg1;
- (void)setUseUniqueActivityIdentifiers:(bool)arg1;
- (void)setXpcActivityCriteriaOverrides:(id)arg1;
- (bool)useUniqueActivityIdentifiers;
- (id)xpcActivityCriteriaOverrides;

@end
