/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface _SFPBResponseWrapperCardSection : PBCodable <NSSecureCoding, _SFPBResponseWrapperCardSection> {
    _SFPBCATModel * _catModel;
    NSData * _visualCATOutput;
}

@property (nonatomic, retain) _SFPBCATModel *catModel;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSData *visualCATOutput;

- (void).cxx_destruct;
- (id)catModel;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFacade:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setCatModel:(id)arg1;
- (void)setVisualCATOutput:(id)arg1;
- (id)visualCATOutput;
- (void)writeTo:(id)arg1;

@end
