/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFFeatureFlags : NSObject

+ (void)dump;
+ (id)featureFlags;
+ (bool)isAnnounceEnabled;
+ (bool)isAnnounceGroupFaceTimeInviteEnabled;
+ (bool)isAnnounceMessagesInCarPlayEnabled;
+ (bool)isAnnounceNotificationsEnabled;
+ (bool)isAnnounceTelephonyEnabled;
+ (bool)isAudioSessionCoordinationEnabled;
+ (bool)isCrossDeviceTVControlEnabled;
+ (bool)isCrossDeviceVoiceFollowUpEnabled;
+ (bool)isDictationVoiceTriggerEnabled;
+ (bool)isHintsEnabled;
+ (bool)isHomeAutomationBackgroundRequestEnabled;
+ (bool)isLassoEnabled;
+ (bool)isListeningOnBothStereoPairUnitsEnabled;
+ (bool)isLocationSearchContinuityEnabled;
+ (bool)isMyriadNonSpeakerRawScoreThresholdEnabled;
+ (bool)isRemoraEnabled;
+ (bool)isSiriRequestDispatcherEnabled;
+ (bool)isSiriUODAvailableForLanguage:(id)arg1;
+ (bool)isSiriXEnabled;
+ (bool)isThemisABEnabled;
+ (bool)isTimerAlarmCoordinationEnabled;
+ (bool)isTrialDictationAssetDeliveryEnabled;
+ (void)setLocationSearchContinuityEnabled:(bool)arg1;
+ (id)sharedInstance;

@end
