/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFUserNotificationAnnouncementSpeakingStateObserver : NSObject <AFInvalidating> {
    <AFUserNotificationAnnouncementSpeakingStateDelegate> * _delegate;
    NSMutableSet * _observingNotifications;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_receivedNotificationForSpeakingStateChange:(id)arg1;
- (void)_removeObserverForNotificationRequestIdentifier:(id)arg1;
- (void)_startObservingNotificationWithRequestIdentifier:(id)arg1;
- (void)_tearDown;
- (void)dealloc;
- (id)initWithQueue:(id)arg1 delegate:(id)arg2;
- (void)invalidate;
- (void)receivedNotificationForSpeakingStateChange:(id)arg1;
- (void)startObservingNotificationWithRequestIdentifier:(id)arg1;
- (void)stopObservingNotificationWithRequestIdentifier:(id)arg1;

@end
