/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
 */

@interface CBAdvertiser : NSObject <CBActivatable, CBErrorReporting, CBInterruptable, CBLabelable, CBStateReporting, CBXPCReceivable, CUXPCCodable> {
    bool  _activateCalled;
    id /* block */  _activateCompletion;
    int  _advertiseRate;
    long long  _bluetoothState;
    id /* block */  _bluetoothStateChangedHandler;
    bool  _changesPending;
    unsigned int  _clientID;
    bool  _direct;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id /* block */  _errorHandler;
    unsigned int  _internalFlags;
    id /* block */  _interruptionHandler;
    bool  _invalidateCalled;
    bool  _invalidateDone;
    id /* block */  _invalidationHandler;
    NSString * _label;
    unsigned int  _nearbyActionFlags;
    unsigned char  _nearbyActionType;
    unsigned int  _nearbyActionV2Flags;
    NSData * _nearbyActionV2TargetData;
    unsigned char  _nearbyActionV2Type;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory {} *x8; struct LogOutput {} *x9; struct LogOutput {} *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
    NSObject<OS_xpc_object> * _xpcCnx;
    NSObject<OS_xpc_object> * _xpcListenerEndpoint;
}

@property (nonatomic) int advertiseRate;
@property (nonatomic, readonly) long long bluetoothState;
@property (nonatomic, copy) id /* block */ bluetoothStateChangedHandler;
@property (nonatomic) unsigned int clientID;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id /* block */ errorHandler;
@property (nonatomic) unsigned int internalFlags;
@property (nonatomic, copy) id /* block */ interruptionHandler;
@property (nonatomic, copy) id /* block */ invalidationHandler;
@property (nonatomic, copy) NSString *label;
@property (nonatomic) unsigned int nearbyActionFlags;
@property (nonatomic) unsigned char nearbyActionType;
@property (nonatomic) unsigned int nearbyActionV2Flags;
@property (nonatomic, copy) NSData *nearbyActionV2TargetData;
@property (nonatomic) unsigned char nearbyActionV2Type;
@property (nonatomic, retain) NSObject<OS_xpc_object> *xpcListenerEndpoint;

- (void).cxx_destruct;
- (void)_activate;
- (void)_activateDirectStart;
- (void)_activateXPCCompleted:(id)arg1;
- (void)_activateXPCStart:(bool)arg1;
- (id)_ensureXPCStarted;
- (void)_interrupted;
- (void)_invalidateDirect;
- (void)_invalidated;
- (void)_update;
- (void)_updateIfNeededWithBlock:(id /* block */)arg1;
- (void)_xpcReceivedMessage:(id)arg1;
- (void)_xpcReceivedPowerStateChanged:(id)arg1;
- (void)activateWithCompletion:(id /* block */)arg1;
- (int)advertiseRate;
- (long long)bluetoothState;
- (id /* block */)bluetoothStateChangedHandler;
- (unsigned int)clientID;
- (void)dealloc;
- (id)description;
- (id)descriptionWithLevel:(int)arg1;
- (id)dispatchQueue;
- (void)encodeWithXPCObject:(id)arg1;
- (id /* block */)errorHandler;
- (id)init;
- (id)initWithXPCObject:(id)arg1 error:(id*)arg2;
- (unsigned int)internalFlags;
- (id /* block */)interruptionHandler;
- (void)invalidate;
- (id /* block */)invalidationHandler;
- (id)label;
- (unsigned int)nearbyActionFlags;
- (unsigned char)nearbyActionType;
- (unsigned int)nearbyActionV2Flags;
- (id)nearbyActionV2TargetData;
- (unsigned char)nearbyActionV2Type;
- (void)setAdvertiseRate:(int)arg1;
- (void)setBluetoothStateChangedHandler:(id /* block */)arg1;
- (void)setClientID:(unsigned int)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setErrorHandler:(id /* block */)arg1;
- (void)setInternalFlags:(unsigned int)arg1;
- (void)setInterruptionHandler:(id /* block */)arg1;
- (void)setInvalidationHandler:(id /* block */)arg1;
- (void)setLabel:(id)arg1;
- (void)setNearbyActionFlags:(unsigned int)arg1;
- (void)setNearbyActionType:(unsigned char)arg1;
- (void)setNearbyActionV2Flags:(unsigned int)arg1;
- (void)setNearbyActionV2TargetData:(id)arg1;
- (void)setNearbyActionV2Type:(unsigned char)arg1;
- (void)setXpcListenerEndpoint:(id)arg1;
- (bool)updateWithCBAdvertiser:(id)arg1;
- (id)xpcListenerEndpoint;
- (void)xpcReceivedMessage:(id)arg1;

@end
