/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
 */

@interface CBDeviceSettings : NSObject <CUXPCCodable> {
    BOOL  _aclPriority;
    BOOL  _allowsAutoRoute;
    BOOL  _audioRouteHidden;
    unsigned long long  _deviceFlagsMask;
    unsigned long long  _deviceFlagsValue;
    BOOL  _doubleTapActionLeft;
    BOOL  _doubleTapActionRight;
    BOOL  _microphoneMode;
    NSString * _name;
    BOOL  _placementMode;
    BOOL  _relinquishAudioRoute;
    BOOL  _smartRoutingMode;
}

@property (nonatomic) BOOL aclPriority;
@property (nonatomic) BOOL allowsAutoRoute;
@property (nonatomic) BOOL audioRouteHidden;
@property (nonatomic) unsigned long long deviceFlagsMask;
@property (nonatomic) unsigned long long deviceFlagsValue;
@property (nonatomic) BOOL doubleTapActionLeft;
@property (nonatomic) BOOL doubleTapActionRight;
@property (nonatomic) BOOL microphoneMode;
@property (nonatomic, copy) NSString *name;
@property (nonatomic) BOOL placementMode;
@property (nonatomic) BOOL relinquishAudioRoute;
@property (nonatomic) BOOL smartRoutingMode;

- (void).cxx_destruct;
- (BOOL)aclPriority;
- (BOOL)allowsAutoRoute;
- (BOOL)audioRouteHidden;
- (id)description;
- (unsigned long long)deviceFlagsMask;
- (unsigned long long)deviceFlagsValue;
- (BOOL)doubleTapActionLeft;
- (BOOL)doubleTapActionRight;
- (void)encodeWithXPCObject:(id)arg1;
- (id)initWithXPCObject:(id)arg1 error:(id*)arg2;
- (BOOL)microphoneMode;
- (id)name;
- (BOOL)placementMode;
- (BOOL)relinquishAudioRoute;
- (void)setAclPriority:(BOOL)arg1;
- (void)setAllowsAutoRoute:(BOOL)arg1;
- (void)setAudioRouteHidden:(BOOL)arg1;
- (void)setDeviceFlagsMask:(unsigned long long)arg1;
- (void)setDeviceFlagsValue:(unsigned long long)arg1;
- (void)setDoubleTapActionLeft:(BOOL)arg1;
- (void)setDoubleTapActionRight:(BOOL)arg1;
- (void)setMicrophoneMode:(BOOL)arg1;
- (void)setName:(id)arg1;
- (void)setPlacementMode:(BOOL)arg1;
- (void)setRelinquishAudioRoute:(BOOL)arg1;
- (void)setSmartRoutingMode:(BOOL)arg1;
- (BOOL)smartRoutingMode;

@end
