/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManagerCore.framework/DocumentManagerCore
 */

@interface DOCAXIdentifier : NSObject

+ (id)browsingModeTabBar;
+ (id)browsingRoot;
+ (id)browsingRootIdentifierForSourceIdentifier:(id)arg1;
+ (id)fullNavBar;
+ (id)groupByMenuButtonForGrouping:(id)arg1;
+ (id)idBase;
+ (id)inlineRenameField;
+ (id)itemCollectionMenuButtonShowing:(id)arg1;
+ (id)itemCollectionView;
+ (id)itemInfoNavigationRoot;
+ (Class)itemInfoView;
+ (id)searchMenuButtonShowing:(id)arg1;
+ (Class)sidebar;
+ (id)sortByMenuButtonForSortIdentifier:(id)arg1 ascending:(bool)arg2 active:(bool)arg3;
+ (id)tagEditorContainer;
+ (Class)viewStyleSelector;

@end
