/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManagerCore.framework/DocumentManagerCore
 */

@interface DOCFeature : NSObject

+ (id)DSCopyEngine;
+ (id)configurableWidget;
+ (id)copyProgressIndeterminateUI;
+ (id)denseIconGrid;
+ (id)goToFolder;
+ (id)goToFolderBlurAnimation;
+ (id)groupHorizontalScrolling;
+ (id)groupItems;
+ (id)inlineRename;
+ (id)keyboardSelection;
+ (id)quickLookMultiWindow;
+ (id)shapeTagsSupported;
+ (id)shortcutsActions;
+ (id)useBlastDoorThumbnails;

@end
