/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Trial.framework/Trial
 */

@interface TRIClientGuardedData : NSObject {
    TRIExcessiveStaleFactorsUsageTimer * excessiveStaleFactorUsageTimer;
    NSMutableDictionary * namespaceCallbacks;
    NSMutableDictionary * namespaceUpdateHandlerTokens;
    TRITrackingId * trackingId;
}

- (void).cxx_destruct;

@end
