/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebAccessibilityObjectWrapperBase : NSObject {
    unsigned long long  _identifier;
    void * m_axObject;
}

@property (nonatomic) unsigned long long identifier;

+ (void)accessibilitySetShouldRepostNotifications:(bool)arg1;

- (id)_accessibilityWebDocumentView;
- (bool)_prepareAccessibilityCall;
- (id)accessibilityMathPostscriptPairs;
- (id)accessibilityMathPrescriptPairs;
- (id)accessibilityPlatformMathSubscriptKey;
- (id)accessibilityPlatformMathSuperscriptKey;
- (void)accessibilityPostedNotification:(id)arg1;
- (void)accessibilityPostedNotification:(id)arg1 userInfo:(id)arg2;
- (id)ariaLandmarkRoleDescription;
- (void)attachAXObject:(void*)arg1;
- (id)attachmentView;
- (void*)axBackingObject;
- (id)baseAccessibilityDescription;
- (id)baseAccessibilityHelpText;
- (id)baseAccessibilityResolvedEditingStyles;
- (id)baseAccessibilitySpeechHint;
- (id)contentForSimpleRange:(const void*)arg1 attributed:(bool)arg2;
- (struct CGPath { }*)convertPathToScreenSpace:(const void*)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })convertRectToSpace:(const struct FloatRect { struct FloatPoint { float x_1_1_1; float x_1_1_2; } x1; struct FloatSize { bool x_2_1_1; bool x_2_1_2; float x_2_1_3; float x_2_1_4; } x2; }*)arg1 space:(int)arg2;
- (void)detach;
- (unsigned long long)identifier;
- (id)initWithAccessibilityObject:(void*)arg1;
- (id)innerHTML;
- (bool)isIsolatedObject;
- (id)lineRectsAndText;
- (id)outerHTML;
- (void)setIdentifier:(unsigned long long)arg1;

@end
