/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface GEOEncyclopedicInfoUserLocation : NSObject <GEOEncyclopedicInfo> {
    bool  _isUserLocation;
    MKMapItem * _mapItem;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) GEOMapItemAttribution *encyclopedicAttribution;
@property (nonatomic, readonly) NSArray *factoids;
@property (nonatomic, readonly) bool hasPairOfFactoids;
@property (nonatomic, readonly) bool hasStandAloneFactoids;
@property (nonatomic, readonly) bool hasTextBlock;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) MKMapItem *mapItem;
@property (nonatomic, readonly) NSArray *placeSummaryFactoids;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSString *textBlockText;
@property (nonatomic, readonly) NSString *textBlockTitle;

- (void).cxx_destruct;
- (bool)canBeDisplayedInPlaceSummary;
- (id)encyclopedicAttribution;
- (id)factoidAtIndex:(int)arg1;
- (id)factoids;
- (id)firstFactoidForSemantic:(int)arg1;
- (bool)hasPairOfFactoids;
- (bool)hasStandAloneFactoids;
- (bool)hasTextBlock;
- (id)initWithMapItem:(id)arg1 isUserLocation:(bool)arg2;
- (id)mapItem;
- (id)placeSummaryFactoids;
- (void)setMapItem:(id)arg1;
- (id)textBlockText;
- (id)textBlockTitle;

@end
