/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceCardActionsRowView : UIView <MKActionRowItemViewDelegate> {
    NSArray * _actionButtons;
    <MKPlaceActionManagerProtocol> * _actionManager;
    NSArray * _actionRowsArray;
    Class  _buttonBackgroundViewClass;
    NSArray * _constraints;
    NSArray * _items;
    unsigned long long  _maxButtonsPerRow;
    <_MKPlaceViewControllerDelegate> * _placeViewControllerDelegate;
    unsigned long long  _style;
}

@property (nonatomic, readonly) NSArray *actionButtons;
@property (nonatomic) <MKPlaceActionManagerProtocol> *actionManager;
@property (nonatomic) Class buttonBackgroundViewClass;
@property (nonatomic, copy) NSArray *items;
@property (nonatomic) <_MKPlaceViewControllerDelegate> *placeViewControllerDelegate;

- (void).cxx_destruct;
- (void)actionButtonPressed:(id)arg1;
- (id)actionButtons;
- (id)actionManager;
- (void)actionRowSelected:(id)arg1;
- (Class)buttonBackgroundViewClass;
- (void)createActionViews;
- (void)createActions;
- (void)createConstraints;
- (void)infoCardThemeChanged;
- (id)initWithStyle:(unsigned long long)arg1;
- (void)invalidateActionButtons;
- (id)items;
- (void)layoutButtons;
- (unsigned long long)maxButtonsPerRow;
- (id)placeViewControllerDelegate;
- (void)setActionManager:(id)arg1;
- (void)setButtonBackgroundViewClass:(Class)arg1;
- (void)setItems:(id)arg1;
- (void)setPlaceViewControllerDelegate:(id)arg1;

@end
