/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlacePhotoGalleryAttributionView : UIView <MKActivityObserving> {
    UIButton * _accessoryButton;
    <MUPlacePhotoGalleryAttributionViewDelegate> * _delegate;
    UIVisualEffectView * _effectView;
    UILabel * _primaryLabel;
    NSArray * _primaryLabelOnlyConstraints;
    NSArray * _regularConstraints;
    UILabel * _secondaryLabel;
    MKPlacePhotoGalleryAttributionViewModel * _viewModel;
}

@property (nonatomic, retain) UIButton *accessoryButton;
@property (nonatomic, readonly) UIView *accessoryView;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MUPlacePhotoGalleryAttributionViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIVisualEffectView *effectView;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UILabel *primaryLabel;
@property (nonatomic, retain) NSArray *primaryLabelOnlyConstraints;
@property (nonatomic, retain) NSArray *regularConstraints;
@property (nonatomic, retain) UILabel *secondaryLabel;
@property (readonly) Class superclass;
@property (nonatomic, retain) MKPlacePhotoGalleryAttributionViewModel *viewModel;

- (void).cxx_destruct;
- (void)_accessoryViewTapped;
- (void)_updateAppearance;
- (id)accessoryButton;
- (id)accessoryView;
- (void)beginAnimatingActivityIndicator;
- (long long)blurEffectWithStyle:(long long)arg1;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (id)delegate;
- (id)effectView;
- (void)endAnimatingActivityIndicatorWithError:(id)arg1;
- (id)init;
- (id)primaryLabel;
- (id)primaryLabelOnlyConstraints;
- (id)regularConstraints;
- (id)secondaryLabel;
- (void)setAccessoryButton:(id)arg1;
- (void)setAttributionLogoImage:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDescription:(id)arg1 license:(id)arg2;
- (void)setEffectView:(id)arg1;
- (void)setPrimaryLabel:(id)arg1;
- (void)setPrimaryLabelOnlyConstraints:(id)arg1;
- (void)setRegularConstraints:(id)arg1;
- (void)setSecondaryLabel:(id)arg1;
- (void)setViewModel:(id)arg1;
- (void)setupSubviews;
- (void)updateFonts;
- (void)updateStyle:(long long)arg1;
- (id)viewModel;

@end
