/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlacePhotoGalleryAttributionViewModel : NSObject {
    long long  _accessoryStyle;
    NSString * _subtitleText;
    NSString * _titleText;
}

@property (nonatomic) long long accessoryStyle;
@property (nonatomic, retain) NSString *subtitleText;
@property (nonatomic, retain) NSString *titleText;

+ (id)viewModelFromMapItem:(id)arg1 photo:(id)arg2;

- (void).cxx_destruct;
- (long long)accessoryStyle;
- (void)setAccessoryStyle:(long long)arg1;
- (void)setSubtitleText:(id)arg1;
- (void)setTitleText:(id)arg1;
- (id)subtitleText;
- (id)titleText;

@end
