/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSFocusModesHomeScreenSettingsRequest : NSObject <BSDescriptionProviding, BSXPCSecureCoding> {
    NSString * _focusModeIdentifier;
    NSArray * _listsToAdd;
    NSArray * _listsToRemove;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *focusModeIdentifier;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSArray *listsToAdd;
@property (nonatomic, retain) NSArray *listsToRemove;
@property (readonly) Class superclass;

+ (bool)supportsBSXPCSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)encodeWithBSXPCCoder:(id)arg1;
- (id)focusModeIdentifier;
- (id)initWithBSXPCCoder:(id)arg1;
- (id)initWithFocusModeIdentifier:(id)arg1;
- (id)listsToAdd;
- (id)listsToRemove;
- (void)setListsToAdd:(id)arg1;
- (void)setListsToRemove:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
