/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSFocusModesHomeScreenSettingsService : NSObject

+ (id)activateConnection;
+ (void)homeScreenSnapshotsWithRequest:(id)arg1 completion:(id /* block */)arg2;
+ (void)updateFocusModeHomeScreenSettingsWithRequest:(id)arg1;

@end
