/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSMedusaApplicationShortcutService : SBSAbstractApplicationService

- (void)fetchSupportedMedusaShortcutActionsForBundleIdentifier:(id)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)performMedusaShortcutAction:(long long)arg1 forBundleIdentifier:(id)arg2;

@end
