/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSSystemNotesSnapshotManifest : NSObject <NSSecureCoding> {
    NSArray * _snapshots;
}

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSnapshots:(id)arg1;
- (id)snapshotForPresentationMode:(long long)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
