/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CARPFoundation.framework/CARPFoundation
 */

@interface __CARPFBlockMessageHandler : __CARPFMessageHandler {
    id /* block */  _handler;
}

@property (readonly, copy) id /* block */ handler;

- (void).cxx_destruct;
- (id /* block */)handler;
- (bool)invokeWithMessage:(id)arg1;

@end
