/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CARPFoundation.framework/CARPFoundation
 */

@interface __CARPFBooleanFalse : CARPFBoolean

+ (id)new;

- (bool)boolValue;

@end
