/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CARPFoundation.framework/CARPFoundation
 */

@interface _CARPFLogBackendSession : NSObject <CARPFLogBackendSession, CARPFLogging> {
    <_CARPFLogBackendSessionDelegate> * _delegate;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSMutableArray * _queuedEvents;
    NSString * _serviceName;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <_CARPFLogBackendSessionDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *serviceName;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)_flushQueuedEvents;
- (void)activateWithSession;
- (void)dealloc;
- (id)delegate;
- (id)initWithSession:(id)arg1 delegate:(id)arg2;
- (bool)sendMessage:(id)arg1;
- (id)serviceName;
- (void)setDelegate:(id)arg1;

@end
