/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CARPFoundation.framework/CARPFoundation
 */

@interface CARPFMessage : CARPFObject <NSCopying, NSMutableCopying, NSSecureCoding> {
    CARPFMessageInternal * _internal;
}

@property (nonatomic, readonly) CARPFActivity *activity;
@property (nonatomic, retain) CARPFMessageDestination *destination;
@property (nonatomic, readonly, copy) NSDictionary *headers;
@property (nonatomic, copy) NSUUID *identifier;
@property (nonatomic, readonly) CARPFMessageInternal *internal;
@property (nonatomic, readonly) CARPFLogEventSession *logEventSession;
@property (nonatomic, copy) NSDictionary *messagePayload;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly) long long qualityOfService;
@property (nonatomic, copy) id /* block */ responseHandler;
@property (nonatomic, readonly) double timeout;
@property (nonatomic, readonly) CARPFMessageTransport *transport;
@property (nonatomic, readonly, copy) NSDictionary *userInfo;

+ (id)activityNameWithMessageName:(id)arg1;
+ (id)carpf_shortDescription;
+ (id)messageWithMessage:(id)arg1 messagePayload:(id)arg2;
+ (id)messageWithMessage:(id)arg1 messagePayload:(id)arg2 responseHandler:(id /* block */)arg3;
+ (id)messageWithName:(id)arg1 destination:(id)arg2 payload:(id)arg3;
+ (id)messageWithName:(id)arg1 identifier:(id)arg2 messagePayload:(id)arg3;
+ (id)messageWithName:(id)arg1 messagePayload:(id)arg2;
+ (id)messageWithName:(id)arg1 messagePayload:(id)arg2 responseHandler:(id /* block */)arg3;
+ (id)messageWithName:(id)arg1 qualityOfService:(long long)arg2 destination:(id)arg3 payload:(id)arg4;
+ (id)supportedClasses;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)URLForKey:(id)arg1;
- (void)__initWithInternalMessage:(id)arg1;
- (id)activity;
- (id)arrayForKey:(id)arg1;
- (id)arrayOfDateComponentsForKey:(id)arg1;
- (bool)boolForKey:(id)arg1;
- (bool)boolForKey:(id)arg1 keyPresent:(bool*)arg2;
- (id)calendarForKey:(id)arg1;
- (id)carpf_shortDescription;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dataForKey:(id)arg1;
- (id)dateComponentsForKey:(id)arg1;
- (id)dateForKey:(id)arg1;
- (id)debugDescription;
- (id)description;
- (id)descriptionWithPointer:(bool)arg1;
- (id)destination;
- (id)dictionaryForKey:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)errorForKey:(id)arg1;
- (id)headers;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithInternalMessage:(id)arg1;
- (id)initWithName:(id)arg1 destination:(id)arg2 payload:(id)arg3;
- (id)initWithName:(id)arg1 identifier:(id)arg2 messagePayload:(id)arg3 responseHandler:(id /* block */)arg4;
- (id)initWithName:(id)arg1 qualityOfService:(long long)arg2 destination:(id)arg3 payload:(id)arg4;
- (id)initWithName:(id)arg1 qualityOfService:(long long)arg2 destination:(id)arg3 userInfo:(id)arg4 headers:(id)arg5 payload:(id)arg6;
- (id)internal;
- (id)logEventSession;
- (id)messagePayload;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)name;
- (id)nullForKey:(id)arg1;
- (id)numberForKey:(id)arg1;
- (id)predicateForKey:(id)arg1;
- (long long)qualityOfService;
- (bool)respondWithError:(id)arg1;
- (bool)respondWithPayload:(id)arg1;
- (bool)respondWithPayload:(id)arg1 error:(id)arg2;
- (bool)respondWithSuccess;
- (id /* block */)responseHandler;
- (void)setDestination:(id)arg1;
- (id)setForKey:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setLogEventSession:(id)arg1;
- (void)setMessagePayload:(id)arg1;
- (void)setResponseHandler:(id /* block */)arg1;
- (id)stringForKey:(id)arg1;
- (id)timeZoneForKey:(id)arg1;
- (double)timeout;
- (id)transport;
- (id)unarchivedObjectForKey:(id)arg1 ofClasses:(id)arg2;
- (id)userInfo;
- (id)uuidForKey:(id)arg1;

@end
