/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNHapticResourceController : NSObject {
    <MNHapticControllerDelegate> * _delegate;
    bool  _isVibrating;
    int  _vibratorNotificationToken;
}

@property (nonatomic) <MNHapticControllerDelegate> *delegate;
@property (nonatomic, readonly) bool vibrating;

- (void).cxx_destruct;
- (void)_registerForObservation;
- (void)_updateVibratingFromState:(unsigned long long)arg1;
- (void)dealloc;
- (id)delegate;
- (id)init;
- (bool)playHapticSound:(unsigned long long)arg1 andReport:(out id*)arg2;
- (void)setDelegate:(id)arg1;
- (void)stopVibrating;
- (bool)triggerVibration;
- (bool)vibrating;

@end
