/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNSessionUpdateResponseInfo : NSObject {
    NSError * _error;
    GEOETATrafficUpdateRequest * _request;
    GEOETATrafficUpdateResponse * _response;
    double  _responseTime;
}

@property (nonatomic, retain) NSError *error;
@property (nonatomic, retain) GEOETATrafficUpdateRequest *request;
@property (nonatomic, retain) GEOETATrafficUpdateResponse *response;
@property (nonatomic) double responseTime;

- (void).cxx_destruct;
- (id)error;
- (id)request;
- (id)response;
- (double)responseTime;
- (void)setError:(id)arg1;
- (void)setRequest:(id)arg1;
- (void)setResponse:(id)arg1;
- (void)setResponseTime:(double)arg1;

@end
