/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNTimeAndDistanceUpdater : NSObject {
    <MNTimeAndDistanceUpdaterDelegate> * _delegate;
    MNLocation * _location;
    MNActiveRouteInfo * _mainRoute;
    NSTimer * _minuteTimer;
    NSArray * _routes;
}

@property (nonatomic) <MNTimeAndDistanceUpdaterDelegate> *delegate;

- (void).cxx_destruct;
- (void)_startTimerToNextMinute;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)setLocation:(id)arg1 notificationType:(unsigned long long)arg2;
- (void)setRoutes:(id)arg1 mainRoute:(id)arg2 location:(id)arg3 notificationType:(unsigned long long)arg4;
- (void)startUpdating;
- (void)stopUpdating;
- (void)updateDisplayETAForRoute:(id)arg1 notificationType:(unsigned long long)arg2;

@end
