/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNTurnByTurnLocationTracker : MNLocationTracker <MNArrivalUpdaterDelegate, MNEVChargingStateMonitorDelegate> {
    MNArrivalUpdater * _arrivalUpdater;
    unsigned long long  _consecutiveOffRouteCount;
    MNEVChargingStateMonitor * _evChargingStateMonitor;
    bool  _isNavigatingInLowGuidance;
    unsigned long long  _lastArrivalLegIndex;
    MNLocation * _lastKnownGoodLocationOnRoute;
    GEONavigationMapMatcher * _mapMatcher;
    struct { 
        double latitude; 
        double longitude; 
    }  _originCoordinate;
    GEOPathMatcher * _pathMatcher;
    MNLocation * _previousRerouteLocation;
    unsigned long long  _recalculationNetworkUnreachableCount;
    NSTimer * _recalculationRetryTimer;
    GEODirectionsRequest * _request;
    NSMutableArray * _rerouteDates;
    unsigned long long  _rerouteReason;
    <GEODirectionServiceTicket> * _rerouteTicket;
    long long  _responseErrorCode;
    unsigned long long  _responseErrorCount;
    NSData * _serverSessionState;
    NSDate * _startDate;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSData *serverSessionState;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_allowRerouteForLocation:(id)arg1 outError:(out id*)arg2;
- (bool)_allowSwitchToTransportType:(int)arg1 forLocation:(id)arg2;
- (id)_alternateRouteForOffRouteLocation:(id)arg1;
- (int)_detectedMotionForLocation:(id)arg1;
- (void)_failedToRecalculateRouteWithError:(id)arg1;
- (void)_handleOffRouteForLocation:(id)arg1;
- (bool)_hasArrivedAtFinalDestination;
- (bool)_isCameraTestMode;
- (bool)_isRoadFeatureInOppositeDirection:(id)arg1 ofCoordinate:(struct { double x1; double x2; })arg2 course:(double)arg3;
- (id)_matchedLocationForLocation:(id)arg1;
- (id)_matchedLocationForMatchResult:(id)arg1 originalLocation:(id)arg2;
- (id)_newMapMatcherForRoute:(id)arg1;
- (id)_overrideLocationForLocation:(id)arg1;
- (void)_recalculationRetryTimerFired:(id)arg1;
- (void)_requestDirectionsForLocation:(id)arg1 destination:(id)arg2 transportType:(int)arg3 handler:(id /* block */)arg4;
- (void)_reroute:(id)arg1 rerouteReason:(unsigned long long)arg2 request:(id)arg3 response:(id)arg4;
- (id)_rerouteTicketForLocation:(id)arg1 transportType:(int)arg2;
- (void)_retryLastRouteRecalculation;
- (int)_routeHintTypeForTransportType:(int)arg1;
- (void)_sendRouteHintForLocation:(id)arg1;
- (void)_setIsNavigatingInLowGuidance:(bool)arg1;
- (bool)_shouldAdvanceGuidanceToRouteMatch:(id)arg1;
- (void)_startMonitoringBatteryChargeForLegIndex:(unsigned long long)arg1;
- (void)_submitRerouteTicketWithHandler:(id /* block */)arg1;
- (id)_ticketForNewDestination:(id)arg1 fromLocation:(id)arg2 transportType:(int)arg3;
- (void)_updateForArrivalAtLegIndex:(unsigned long long)arg1;
- (void)_updateForDepartureAtLegIndex:(unsigned long long)arg1;
- (void)_updateForLocation:(id)arg1;
- (void)_updateForReroute:(id)arg1 rerouteReason:(unsigned long long)arg2 request:(id)arg3 response:(id)arg4;
- (void)_updateStateForLocation:(id)arg1;
- (void)_updateSwitchTransportTypeForLocation:(id)arg1;
- (void)arrivalUpdater:(id)arg1 didArriveAtEndOfLegAtIndex:(unsigned long long)arg2;
- (void)arrivalUpdater:(id)arg1 didEnterPreArrivalStateForLegIndex:(unsigned long long)arg2;
- (void)arrivalUpdater:(id)arg1 isApproachingEndOfLegAtIndex:(unsigned long long)arg2;
- (void)arrivalUpdaterDidTimeoutInArrivalRegion:(id)arg1;
- (void)dealloc;
- (void)evChargingStateMonitor:(id)arg1 didChangeChargingState:(bool)arg2;
- (void)evChargingStateMonitor:(id)arg1 didReachTargetBatteryCharge:(id)arg2;
- (void)evChargingStateMonitorShouldShowChargingInfo:(id)arg1;
- (void)forceOnRoute:(id)arg1 atLocation:(id)arg2;
- (void)forceReroute;
- (id)initForTestingWithRoute:(id)arg1;
- (id)initWithNavigationSession:(id)arg1;
- (bool)isRerouting;
- (void)reroute:(id)arg1 reason:(unsigned long long)arg2;
- (id)serverSessionState;
- (void)setServerSessionState:(id)arg1;
- (void)startTracking;
- (void)stopTracking;
- (void)traceJumpedInTime;
- (void)updateDestination:(id)arg1 finishedHandler:(id /* block */)arg2;
- (void)updateLocation:(id)arg1;

@end
