/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FamilyCircle.framework/FamilyCircle
 */

@interface FANetworkService : NSObject {
    ACAccount * _account;
    <FADeviceInfoProtocol> * _deviceInfo;
    <FAURLProvider> * _urlProvider;
    AAURLSession * _urlSession;
}

@property (nonatomic, readonly) ACAccount *account;
@property (nonatomic, readonly) <FADeviceInfoProtocol> *deviceInfo;
@property (nonatomic, readonly) <FAURLProvider> *urlProvider;
@property (nonatomic, readonly) AAURLSession *urlSession;

- (void).cxx_destruct;
- (id)account;
- (id)dataWithRequest:(id)arg1;
- (id)deviceInfo;
- (id)ensureAccount;
- (id)ensureDeviceUnlockedSinceBoot;
- (id)initWithAccount:(id)arg1 deviceInfo:(id)arg2 urlProvider:(id)arg3 urlSession:(id)arg4;
- (id)plistWithRequest:(id)arg1;
- (id)plistWithResponse:(id)arg1;
- (id)signedRequestWithEndpoint:(id)arg1;
- (id)signedRequestWithEndpoint:(id)arg1 method:(id)arg2 headers:(id)arg3 plistBody:(id)arg4;
- (id)signedRequestWithURL:(id)arg1;
- (id)signedRequestWithURL:(id)arg1 method:(id)arg2 headers:(id)arg3 plistBody:(id)arg4;
- (id)standardPlistRequestWithEndpoint:(id)arg1;
- (id)standardPlistRequestWithEndpoint:(id)arg1 method:(id)arg2 plistBody:(id)arg3;
- (id)urlProvider;
- (id)urlSession;

@end
