/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNUIContactSaveConfiguration : NSObject {
    CNContact * _contact;
    CNContactStore * _contactStore;
    CNUIContainerContext * _containerContext;
    NSMutableArray * _editingLinkedContacts;
    bool  _ignoresParentalRestrictions;
    CNMutableContact * _mutableContact;
    CNContainer * _parentContainer;
    CNGroup * _parentGroup;
    bool  _saveWasAuthorized;
    CNMutableContact * _shadowCopyOfReadonlyContact;
}

@property (nonatomic, readonly) CNContact *contact;
@property (nonatomic, readonly) CNContactStore *contactStore;
@property (nonatomic, readonly) CNUIContainerContext *containerContext;
@property (nonatomic, readonly) NSMutableArray *editingLinkedContacts;
@property (nonatomic, readonly) bool ignoresParentalRestrictions;
@property (nonatomic, readonly) CNMutableContact *mutableContact;
@property (nonatomic, readonly) CNContainer *parentContainer;
@property (nonatomic, readonly) CNGroup *parentGroup;
@property (nonatomic, readonly) bool saveWasAuthorized;
@property (nonatomic, readonly) CNMutableContact *shadowCopyOfReadonlyContact;

- (void).cxx_destruct;
- (id)contact;
- (id)contactStore;
- (id)containerContext;
- (id)copyWithEditingLinkedContacts:(id)arg1;
- (id)editingLinkedContacts;
- (bool)ignoresParentalRestrictions;
- (id)initWithContact:(id)arg1 mutableContact:(id)arg2 shadowCopyOfReadonlyContact:(id)arg3 editingLinkedContacts:(id)arg4 contactStore:(id)arg5 parentGroup:(id)arg6 parentContainer:(id)arg7 containerContext:(id)arg8 ignoresParentalRestrictions:(bool)arg9 saveWasAuthorized:(bool)arg10;
- (id)mutableContact;
- (id)parentContainer;
- (id)parentGroup;
- (bool)saveWasAuthorized;
- (id)shadowCopyOfReadonlyContact;

@end
