/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLCompileFunctionRequestData : NSObject {
    struct { 
        unsigned char key[32]; 
    }  _archiveHashKey;
    NSArray * _binaryArchives;
    <MTLBinaryArchive> * _destinationBinaryArchive;
    NSObject<OS_dispatch_data> * _driverKeyData;
    NSObject<OS_dispatch_data> * _frameworkData;
    MTLFunction * _function;
    unsigned long long  _functionOptions;
    <MTLPipelineCache> * _pipelineCache;
    unsigned long long  _pipelineOptions;
    NSArray * _privateVisibleFunctions;
    bool  _sync;
    NSDictionary * _visibleFunctionGroups;
    NSArray * _visibleFunctions;
}

@property (nonatomic) struct { unsigned char x1[32]; } archiveHashKey;
@property (nonatomic, copy) NSArray *binaryArchives;
@property (nonatomic, retain) <MTLBinaryArchive> *destinationBinaryArchive;
@property (nonatomic) NSObject<OS_dispatch_data> *driverKeyData;
@property (nonatomic) NSObject<OS_dispatch_data> *frameworkData;
@property (nonatomic, retain) MTLFunction *function;
@property (nonatomic) unsigned long long functionOptions;
@property (nonatomic, retain) <MTLPipelineCache> *pipelineCache;
@property (nonatomic) unsigned long long pipelineOptions;
@property (nonatomic, copy) NSArray *privateVisibleFunctions;
@property (nonatomic) bool sync;
@property (nonatomic, copy) NSDictionary *visibleFunctionGroups;
@property (nonatomic, copy) NSArray *visibleFunctions;

+ (id)newVisibleRequestWithFunction:(id)arg1 descriptor:(id)arg2;

- (struct { unsigned char x1[32]; })archiveHashKey;
- (id)binaryArchives;
- (void)dealloc;
- (id)destinationBinaryArchive;
- (id)driverKeyData;
- (id)frameworkData;
- (id)function;
- (unsigned long long)functionOptions;
- (id)pipelineCache;
- (unsigned long long)pipelineOptions;
- (id)privateVisibleFunctions;
- (void)setArchiveHashKey:(struct { unsigned char x1[32]; })arg1;
- (void)setBinaryArchives:(id)arg1;
- (void)setDestinationBinaryArchive:(id)arg1;
- (void)setDriverKeyData:(id)arg1;
- (void)setFrameworkData:(id)arg1;
- (void)setFunction:(id)arg1;
- (void)setFunctionOptions:(unsigned long long)arg1;
- (void)setPipelineCache:(id)arg1;
- (void)setPipelineOptions:(unsigned long long)arg1;
- (void)setPrivateVisibleFunctions:(id)arg1;
- (void)setSync:(bool)arg1;
- (void)setVisibleFunctionGroups:(id)arg1;
- (void)setVisibleFunctions:(id)arg1;
- (bool)sync;
- (id)visibleFunctionGroups;
- (id)visibleFunctions;

@end
