/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLResourceList : NSObject {
    struct { 
        int chunkEntryCapacity; 
        struct MTLResourceListChunk { 
            int currentEntry; 
            void **entries; 
            struct MTLResourceListChunk {} *nextChunk; 
        } currentChunk; 
        MTLResourceListPool *pool; 
        struct { 
            MTLResourceList *tqe_next; 
            id *tqe_prev; 
        } entry; 
        unsigned long long time_added; 
    }  _listPriv;
}

- (void)dealloc;
- (id)initWithCapacity:(int)arg1;
- (void)releaseAllObjectsAndReset;

@end
