/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _NSDiffableDataSourceSectionSnapshotState : NSObject <NSCopying> {
    NSOrderedSet * _identifiers;
    _UITreeDataSourceSnapshotter * _snapshotter;
    struct { 
        unsigned int identifiersHaveGuaranteedPerformance : 1; 
    }  _stateFlags;
}

@property (nonatomic, readonly) NSOrderedSet *identifiers;
@property (nonatomic, readonly) _UITreeDataSourceSnapshotter *snapshotter;

- (void).cxx_destruct;
- (bool)containsIdentifier:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)identifiers;
- (long long)indexOfIdentifier:(id)arg1;
- (id)init;
- (id)initWithSnapshotter:(id)arg1 identifiers:(id)arg2;
- (id)initWithSnapshotter:(id)arg1 identifiers:(id)arg2 identifiersHaveGuaranteedPerformance:(bool)arg3;
- (bool)isEqual:(id)arg1;
- (id)snapshotter;

@end
