/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIBackgroundHitTestWindow : UIWindow

+ (bool)_isSystemWindow;

- (id)_roleHint;

@end
