/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICollectionLayoutSolveResult : NSObject <_UICollectionLayoutSolveResult> {
    struct CGPoint { 
        double x; 
        double y; 
    }  _contentOffsetAdjustment;
    NSMutableDictionary * _invalidatedAuxillaryIndexesDict;
    NSMutableIndexSet * _invalidatedIndexes;
}

@property (nonatomic) struct CGPoint { double x1; double x2; } contentOffsetAdjustment;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSSet *invalidatedAuxillaryKinds;
@property (nonatomic, readonly) NSIndexSet *invalidatedIndexes;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (struct CGPoint { double x1; double x2; })contentOffsetAdjustment;
- (id)indexesForInvalidatedAuxillariesOfKind:(id)arg1;
- (id)init;
- (id)invalidatedAuxillaryKinds;
- (id)invalidatedAuxillaryOffsets;
- (id)invalidatedIndexes;
- (void)setContentOffsetAdjustment:(struct CGPoint { double x1; double x2; })arg1;

@end
