/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICollectionViewOrthogonalScrollerEmbeddedScrollView : UIScrollView <_UICollectionViewOrthogonalScrollView> {
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _baseContentInsets;
    UICollectionView * _collectionView;
    long long  _section;
    UIFocusContainerGuide * _sectionFocusContainerGuide;
}

@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } baseContentInsets;
@property (nonatomic) UICollectionView *collectionView;
@property (nonatomic, readonly) struct CGPoint { double x1; double x2; } contentOffset;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } contentSize;
@property (readonly, copy) NSString *debugDescription;
@property (getter=isDecelerating, nonatomic, readonly) bool decelerating;
@property (readonly, copy) NSString *description;
@property (getter=isDragging, nonatomic, readonly) bool dragging;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long section;
@property (readonly) Class superclass;
@property (getter=isTracking, nonatomic, readonly) bool tracking;

- (void).cxx_destruct;
- (id)_childFocusRegionsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inCoordinateSpace:(id)arg2;
- (unsigned long long)_edgesPropagatingSafeAreaInsetsToDescendants;
- (void)_focusedItem:(id)arg1 isMinX:(bool*)arg2 isMaxX:(bool*)arg3 isMinY:(bool*)arg4 isMaxY:(bool*)arg5;
- (struct CGPoint { double x1; double x2; })_panGestureLocationInView:(id)arg1;
- (struct CGPoint { double x1; double x2; })_panGestureVelocityInView:(id)arg1;
- (struct CGPoint { double x1; double x2; })_pointByApplyingBaseContentInsetsToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGPoint { double x1; double x2; })_pointByRemovingBaseContentInsetsFromPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })baseContentInsets;
- (id)collectionView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (long long)section;
- (void)setBaseContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setCollectionView:(id)arg1;
- (void)setSection:(long long)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end
