/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICollectionLayoutSupplementaryRegistrar : NSObject <_UICollectionLayoutSupplementaryEnrolling> {
    NSMutableOrderedSet * _enrollmentIdentifiers;
    NSMutableDictionary * _enrollmentsDict;
    NSMutableDictionary * _kindEnrollmentsDict;
    NSMutableSet * _uncommittedEnrollmentIdentifiers;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)commitEnrollment:(id)arg1;
- (long long)countForKind:(id)arg1;
- (id)description;
- (id)enrollSupplementaryForKind:(id)arg1;
- (id)init;
- (long long)kindIndexForEnrollmentIdentifier:(id)arg1;
- (void)pruneUncommitedEnrollments;

@end
