/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICollectionViewVerifier : NSObject {
    UICollectionView * _collectionView;
    bool  _enabled;
    NSTimer * _timer;
}

@property (nonatomic) bool enabled;

- (void).cxx_destruct;
- (void)dealloc;
- (bool)enabled;
- (void)prefsChanged:(id)arg1;
- (void)setEnabled:(bool)arg1;

@end
