/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIFocusTreeLock : NSObject {
    NSMapTable * _lockedEnvironmentHistogram;
    NSCountedSet * _lockedEnvironments;
    NSTimer * _validationTimer;
}

@property (nonatomic, readonly) NSMapTable *lockedEnvironmentHistogram;
@property (nonatomic, readonly) NSCountedSet *lockedEnvironments;
@property (nonatomic, readonly) NSTimer *validationTimer;

- (void).cxx_destruct;
- (void)_validateLockedEnvironments;
- (id)description;
- (id)init;
- (bool)isEnvironmentLocked:(id)arg1;
- (void)lockEnvironmentTree:(id)arg1;
- (id)lockedEnvironmentHistogram;
- (id)lockedEnvironments;
- (bool)unlockEnvironmentTree:(id)arg1;
- (id)validationTimer;

@end
