/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyShortcutHUDToolbarCategoryCell : _UIKeyShortcutHUDCell

- (id)_defaultContentConfigurationWithCategory:(id)arg1;
- (void)configureForDisplayingInHUDWithCategory:(id)arg1;
- (void)configureForMetricsCalculationsWithCategory:(id)arg1;
- (void)updateConfigurationUsingState:(id)arg1;

@end
