/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyShortcutHUDLargeMetrics : _UIKeyShortcutHUDMetrics

- (double)menuBaseVerticalContentInset;
- (double)menuCellHorizontalContentMargin;
- (unsigned long long)menuPanelCornerMask;
- (double)minimumBottomScreenEdgeDistance;
- (double)minimumScreenEdgeDistance;
- (double)searchModeStandardHUDWidth;
- (bool)shouldExtendToolbarThroughSafeArea;
- (double)standardHUDWidth;
- (double)standardMenuPadding;
- (double)standardMenuToolbarSpacing;
- (double)toolbarContentInset;
- (unsigned long long)toolbarPanelCornerMask;
- (bool)toolbarStylesCategoriesAsPageControl;

@end
