/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyShortcutHUDShortcut : _UIKeyShortcutHUDMenuElement {
    UICommandAlternate * _alternateForBaseShortcut;
    NSMutableDictionary * _alternatesMap;
    _UIKeyShortcutHUDShortcut * _baseShortcutForAlternate;
    UIKeyCommand * _discoverabilityUIKeyCommand;
    id  _originalTarget;
}

@property (nonatomic) UICommandAlternate *alternateForBaseShortcut;
@property (nonatomic, readonly) NSMutableDictionary *alternatesMap;
@property (nonatomic, readonly) unsigned long long attributes;
@property (nonatomic) _UIKeyShortcutHUDShortcut *baseShortcutForAlternate;
@property (nonatomic, readonly) NSString *discoverabilityTitle;
@property (nonatomic, retain) UIKeyCommand *discoverabilityUIKeyCommand;
@property (nonatomic, readonly) NSString *hudTitle;
@property (nonatomic, readonly) NSString *input;
@property (nonatomic, readonly) long long modifierFlags;
@property (nonatomic) id originalTarget;
@property (nonatomic, readonly) NSArray *shortcutAlternates;
@property (nonatomic, readonly) UIKeyCommand *uiKeyCommand;

+ (id)shortcutWithUIKeyCommand:(id)arg1;

- (void).cxx_destruct;
- (void)_acceptMenuVisit:(id /* block */)arg1 shortcutVisit:(id /* block */)arg2;
- (id)alternateForBaseShortcut;
- (id)alternatesMap;
- (unsigned long long)attributes;
- (id)baseShortcutForAlternate;
- (id)discoverabilityTitle;
- (id)discoverabilityUIKeyCommand;
- (id)hudTitle;
- (id)input;
- (long long)modifierFlags;
- (id)originalTarget;
- (void)setAlternateForBaseShortcut:(id)arg1;
- (void)setBaseShortcutForAlternate:(id)arg1;
- (void)setDiscoverabilityUIKeyCommand:(id)arg1;
- (void)setOriginalTarget:(id)arg1;
- (id)shortcutAlternates;
- (id)shortcutToDisplayForModifierFlags:(long long)arg1;
- (id)uiKeyCommand;

@end
