/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyShortcutHUDConfiguration : NSObject {
    UIEvent * _event;
    bool  _searching;
    long long  _shortcutType;
}

@property (nonatomic, retain) UIEvent *event;
@property (getter=isSearching, nonatomic) bool searching;
@property (nonatomic) long long shortcutType;

- (void).cxx_destruct;
- (id)event;
- (bool)isSearching;
- (void)setEvent:(id)arg1;
- (void)setSearching:(bool)arg1;
- (void)setShortcutType:(long long)arg1;
- (long long)shortcutType;

@end
