/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyShortcutHUDContext : NSObject {
    UIWindow * _keyWindow;
}

@property (nonatomic) UIWindow *keyWindow;

- (void).cxx_destruct;
- (id)keyWindow;
- (void)setKeyWindow:(id)arg1;

@end
