/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyboardFeedbackGenerator : UIFeedbackGenerator {
    double  _lastNonReleaseActionTimestamp;
    double  _lastTypedKeyTimestamp;
    bool  _usesKeyHaptics;
}

@property (getter=_keyboardConfiguration, nonatomic, readonly) _UIKeyboardFeedbackGeneratorConfiguration *keyboardConfiguration;
@property (nonatomic) double lastNonReleaseActionTimestamp;
@property (getter=_lastTypedKeyTimestamp, setter=_setLastTypedKeyTimestamp:, nonatomic) double lastTypedKeyTimestamp;
@property (nonatomic) bool usesKeyHaptics;

+ (Class)_configurationClass;
+ (bool)areKeyHapticsEnabled;
+ (id)configurationForVisceral:(long long)arg1;

- (double)_autoDeactivationTimeout;
- (id)_feedbackWithUpdatedVolume:(id)arg1;
- (id)_keyboardConfiguration;
- (double)_lastTypedKeyTimestamp;
- (void)_playFeedbackForActionType:(long long)arg1 withCustomization:(id /* block */)arg2;
- (void)_setLastTypedKeyTimestamp:(double)arg1;
- (id)_stats_key;
- (void)actionOccurred:(long long)arg1;
- (void)commonInitWithVisceral:(long long)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCoordinateSpace:(id)arg1;
- (id)initWithCoordinateSpace:(id)arg1 visceral:(long long)arg2;
- (double)lastNonReleaseActionTimestamp;
- (void)processDidChangeLowPowerMode:(id)arg1;
- (float)scaleVolumeSlow:(float)arg1 fast:(float)arg2 timeSpan:(double)arg3;
- (void)setLastNonReleaseActionTimestamp:(double)arg1;
- (void)setUsesKeyHaptics:(bool)arg1;
- (void)setUsesKeyHapticsFromVisceral:(long long)arg1;
- (bool)usesKeyHaptics;

@end
