/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIModernTextLayoutController : _UITextLayoutController <NSTextLayoutManagerDelegate> {
    NSMutableSet * _ghostedRanges;
    NSMutableSet * _invisibleRanges;
    NSMapTable * _textCanvasViews;
    NSTextContentStorage * _textContentStorage;
    NSTextLayoutManager * _textLayoutManager;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_locationWithOffset:(long long)arg1;
- (void)_updateSelectionWithTextRange:(id)arg1 affinity:(long long)arg2 typingAttributes:(id)arg3;
- (void)addAnnotationAttribute:(id)arg1 value:(id)arg2 forRange:(id)arg3;
- (void)addGhostedRange:(id)arg1;
- (void)addInvisibleRange:(id)arg1;
- (void)addRenderingAttributes:(id)arg1 forRange:(id)arg2;
- (long long)affinityForPosition:(id)arg1;
- (id)annotatedSubstringForRange:(id)arg1;
- (id)annotationAttribute:(id)arg1 atPosition:(id)arg2;
- (id)attributedTextInRange:(id)arg1;
- (id)attributesAtPosition:(id)arg1 inDirection:(long long)arg2;
- (long long)baseWritingDirectionAtPosition:(id)arg1;
- (double)baselineOffsetForFirstGlyph;
- (id)beginningOfDocument;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })boundingRectForCharacterRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })boundingRectForRange:(id)arg1;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })characterRangeForTextRange:(id)arg1;
- (long long)comparePosition:(id)arg1 toPosition:(id)arg2;
- (id)cursorPositionAtPoint:(struct CGPoint { double x1; double x2; })arg1 inContainer:(id)arg2;
- (id)dequeueCanvasViewForTextContainer:(id)arg1;
- (id)documentRange;
- (id)emptyTextRangeAtPosition:(id)arg1;
- (id)endOfDocument;
- (void)ensureLayoutForRange:(id)arg1;
- (void)ensureLayoutForTextContainer:(id)arg1;
- (void)enumerateTextLineFragmentsInRange:(id)arg1 usingBlock:(id /* block */)arg2;
- (id)initWithTextContainer:(id)arg1;
- (id)initWithTextStorage:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })insertionRectForPosition:(id)arg1 typingAttributes:(id)arg2 placeholderAttachment:(id)arg3 textContainer:(id*)arg4;
- (void)invalidateDisplayForCharacterRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (void)invalidateLayoutForRange:(id)arg1;
- (id)nearestPositionAtPoint:(struct CGPoint { double x1; double x2; })arg1 inContainer:(id)arg2;
- (long long)offsetFromPosition:(id)arg1 toPosition:(id)arg2;
- (id)positionFromPosition:(id)arg1 offset:(long long)arg2 affinity:(long long)arg3;
- (id)positionWithOffset:(long long)arg1 affinity:(long long)arg2;
- (id)previewRendererForRange:(id)arg1 unifyRects:(bool)arg2;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })rangeOfCharacterClusterAtIndex:(unsigned long long)arg1 type:(long long)arg2;
- (void)removeAllGhostedRanges;
- (void)removeAnnotationAttribute:(id)arg1 forRange:(id)arg2;
- (void)removeInvisibleRange:(id)arg1;
- (void)removeRenderingAttributes:(id)arg1 forRange:(id)arg2;
- (void)requestTextGeometryAtPosition:(id)arg1 typingAttributes:(id)arg2 resultBlock:(id /* block */)arg3;
- (void)resetFontForExtraBulletRendering;
- (id)selectionRectsForRange:(id)arg1 fromView:(id)arg2 forContainerPassingTest:(id /* block */)arg3;
- (void)setDocumentObscured:(bool)arg1;
- (void)setUnobscuredRange:(id)arg1;
- (id)textContainerForPosition:(id)arg1;
- (id)textContainers;
- (id)textLayoutManager:(id)arg1 renderingAttributesForLink:(id)arg2 atLocation:(id)arg3 defaultAttributes:(id)arg4;
- (id)textRangeForBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inTextContainer:(id)arg2 layoutIfNeeded:(bool)arg3;
- (id)textRangeForCharacterRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)textRangeForLineEnclosingPosition:(id)arg1 effectiveAffinity:(long long)arg2;
- (id)textRangeFromPosition:(id)arg1 toPosition:(id)arg2;
- (id)textStorage;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })updateLayoutForSizeChangeOfTextContainer:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })usedRectForTextContainer:(id)arg1;
- (id)validatedPositionForPosition:(id)arg1;
- (id)validatedRangeForRange:(id)arg1;

@end
