/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIPresentationControllerDefaultVisualStyleProvider : NSObject <_UIPresentationControllerVisualStyleProviding> {
    _UIPresentationControllerNullVisualStyleProvider * _fallbackProvider;
    NSMutableDictionary * _providerByIdiom;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) _UIPresentationControllerNullVisualStyleProvider *fallbackProvider;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *providerByIdiom;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_init;
- (id)_providerForPresentationController:(id)arg1;
- (id)defaultStyleForPresentationController:(id)arg1;
- (id)fallbackProvider;
- (id)providerByIdiom;
- (void)registerVisualStyleProvider:(id)arg1 forIdiom:(long long)arg2;
- (void)setFallbackProvider:(id)arg1;
- (void)setProviderByIdiom:(id)arg1;
- (id)styleForAlertPresentationController:(id)arg1;
- (id)styleForPopoverPresentationController:(id)arg1;
- (id)styleForRootPresentationController:(id)arg1;
- (id)styleForSheetPresentationController:(id)arg1;

@end
