/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UITextLayoutPosition : UITextPosition <NSCopying> {
    long long  _affinity;
    <NSTextLocation> * _location;
}

@property (nonatomic, readonly) long long affinity;
@property (nonatomic, readonly) <NSTextLocation> *location;

+ (id)textPositionWithLocation:(id)arg1;
+ (id)textPositionWithLocation:(id)arg1 affinity:(long long)arg2;

- (void).cxx_destruct;
- (long long)affinity;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToTextLayoutPosition:(id)arg1;
- (id)location;

@end
