/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIFocusEffect : NSObject <NSCopying> {
    bool  __isDefaultEffect;
}

@property (nonatomic, readonly) bool _isDefaultEffect;

+ (id)effect;

- (bool)__isHaloEffect;
- (bool)_isDefaultEffect;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;

@end
