/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIFocusDebugger : NSObject

+ (id)_ancestryForEnvironment:(id)arg1;
+ (id)_legacy_checkFocusabilityForView:(id)arg1;
+ (id)_statusForFocusSystem:(id)arg1 scene:(id)arg2 includeFocusSystemLog:(bool)arg3 includeSceneLog:(bool)arg4;
+ (id)_verboseStatus;
+ (id)checkFocusGroupTreeForEnvironment:(id)arg1;
+ (id)checkFocusabilityForItem:(id)arg1;
+ (id)help;
+ (id)simulateFocusUpdateRequestFromEnvironment:(id)arg1;
+ (id)status;

@end
