/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIImageSymbolConfiguration : UIImageConfiguration {
    NSArray * _colors;
    struct { 
        unsigned int hasFixedPointSize : 1; 
        unsigned int usesHierarchicalColors : 1; 
        unsigned int prefersMulticolor : 1; 
        unsigned int specifiedPrefersMulticolor : 1; 
    }  _configFlags;
    double  _customFontPointSizeMultiplier;
    NSDictionary * _namedColorStyles;
    double  _pointSize;
    long long  _scale;
    NSString * _textStyle;
    long long  _weight;
}

@property (nonatomic, readonly) NSArray *_colors;
@property (nonatomic, readonly) NSDictionary *_namedColorStyles;
@property (nonatomic, readonly) double customFontPointSizeMultiplier;
@property (nonatomic, readonly) double pointSizeForScalingWithTextStyle;
@property (nonatomic, readonly) long long scale;
@property (nonatomic, readonly, copy) NSString *textStyle;
@property (nonatomic, readonly) long long weight;

+ (id)_configurationWithHierarchicalColors:(id)arg1;
+ (id)_configurationWithNamedColorStyles:(id)arg1;
+ (id)_defaultConfiguration;
+ (id)configurationPreferringMulticolor;
+ (id)configurationWithFont:(id)arg1;
+ (id)configurationWithFont:(id)arg1 scale:(long long)arg2;
+ (id)configurationWithHierarchicalColor:(id)arg1;
+ (id)configurationWithPaletteColors:(id)arg1;
+ (id)configurationWithPointSize:(double)arg1;
+ (id)configurationWithPointSize:(double)arg1 weight:(long long)arg2;
+ (id)configurationWithPointSize:(double)arg1 weight:(long long)arg2 scale:(long long)arg3;
+ (id)configurationWithScale:(long long)arg1;
+ (id)configurationWithTextStyle:(id)arg1;
+ (id)configurationWithTextStyle:(id)arg1 scale:(long long)arg2;
+ (id)configurationWithWeight:(long long)arg1;
+ (id)defaultConfiguration;
+ (bool)supportsSecureCoding;
+ (id)unspecifiedConfiguration;

- (void).cxx_destruct;
- (void)_applyConfigurationValuesTo:(id)arg1;
- (id)_colors;
- (id)_configurationByReplacingColors:(id)arg1;
- (void)_deriveGlyphSize:(long long*)arg1 weight:(long long*)arg2 pointSize:(double*)arg3;
- (bool)_hasColorConfigurationWithTintColor;
- (bool)_hasSpecifiedScale;
- (id)_hierarchicalColorForLayerLevel:(long long)arg1 traitCollection:(id)arg2;
- (id)_initWithTraitCollection:(id)arg1;
- (bool)_isUnspecified;
- (id)_namedColorStyles;
- (id)_paletteColorsWithTraitCollection:(id)arg1;
- (bool)_shouldApplyConfiguration:(id)arg1;
- (id)configurationWithoutPointSizeAndWeight;
- (id)configurationWithoutScale;
- (id)configurationWithoutTextStyle;
- (id)configurationWithoutWeight;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)customFontPointSizeMultiplier;
- (id)debugDescription;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToConfiguration:(id)arg1;
- (bool)isEquivalentToConfiguration:(id)arg1;
- (bool)isSimilarToConfiguration:(id)arg1;
- (double)pointSizeForScalingWithTextStyle;
- (long long)scale;
- (id)textStyle;
- (long long)weight;

@end
