/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardCameraBasePresentationController : UIPresentationController {
    bool  _presentingOverKeyboard;
}

@property (nonatomic) bool presentingOverKeyboard;

- (void)postNotificationsForType:(unsigned long long)arg1 forStart:(bool)arg2;
- (bool)presentingOverKeyboard;
- (void)setPresentingOverKeyboard:(bool)arg1;

@end
