/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintBlackWhiteOption : UIPrintOption {
    UISwitch * _bwswitch;
    bool  _canShowColor;
}

@property (nonatomic, retain) UISwitch *bwswitch;
@property (nonatomic) bool canShowColor;

- (void).cxx_destruct;
- (bool)blackWhite;
- (id)bwswitch;
- (bool)canShowColor;
- (void)changeBlackWhite:(id)arg1;
- (void)dealloc;
- (id)initWithPrintInfo:(id)arg1 printPanelViewController:(id)arg2;
- (id)printOptionTableViewCell;
- (void)setBlackWhite:(bool)arg1;
- (void)setBwswitch:(id)arg1;
- (void)setCanShowColor:(bool)arg1;
- (bool)shouldShow;
- (id)summary;
- (void)updateBlackWhite;

@end
