/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintFinishingTemplatesOption : NSObject <UIPrintOptionListDelegate> {
    UITableView * _finishingOptionsTableView;
    NSArray * _finishingTemplateNames;
    NSArray * _finishingTemplates;
    UITableViewCell * _finishingTemplatesCell;
    UIPrintPanelViewController * _printPanelViewController;
    NSString * _summary;
    long long  _value;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) UITableView *finishingOptionsTableView;
@property (nonatomic, retain) NSArray *finishingTemplateNames;
@property (nonatomic, retain) NSArray *finishingTemplates;
@property (nonatomic, retain) UITableViewCell *finishingTemplatesCell;
@property (readonly) unsigned long long hash;
@property (nonatomic) UIPrintPanelViewController *printPanelViewController;
@property (nonatomic, retain) NSString *summary;
@property (readonly) Class superclass;
@property (nonatomic) long long value;

- (void).cxx_destruct;
- (id)finishingOptionsTableView;
- (id)finishingTemplateNames;
- (id)finishingTemplates;
- (id)finishingTemplatesCell;
- (id)initWithTemplates:(id)arg1 finishingTemplateNames:(id)arg2 printPanelViewController:(id)arg3 finishingOptionsTableView:(id)arg4;
- (id)itemList;
- (void)listItemSelected:(id)arg1;
- (id)printPanelViewController;
- (id)selectedItem;
- (void)setFinishingOptionsTableView:(id)arg1;
- (void)setFinishingTemplateNames:(id)arg1;
- (void)setFinishingTemplates:(id)arg1;
- (void)setFinishingTemplatesCell:(id)arg1;
- (void)setPrintPanelViewController:(id)arg1;
- (void)setSummary:(id)arg1;
- (void)setValue:(long long)arg1;
- (id)summary;
- (id)title;
- (long long)value;

@end
