/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintOptionViewCellViewController : UIViewController {
    <UIPrintOptionViewDelegate> * _viewDelegate;
}

@property (nonatomic) <UIPrintOptionViewDelegate> *viewDelegate;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

- (void).cxx_destruct;

// Image: /usr/lib/libMainThreadChecker.dylib

- (void)setViewDelegate:(id)arg1;
- (id)viewDelegate;
- (void)viewDidAppear:(bool)arg1;

@end
