/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintFinishingOptionsSection : UIPrintOptionSection {
    UIPrintFinishingsOption * _finishingPrintOption;
}

@property (nonatomic, retain) UIPrintFinishingsOption *finishingPrintOption;

- (void).cxx_destruct;
- (void)didSelectPrintOptionSection;
- (id)finishingPrintOption;
- (id)initWithPrintInfo:(id)arg1 printPanelViewController:(id)arg2;
- (void)setCurrentPrinter:(id)arg1;
- (void)setFinishingPrintOption:(id)arg1;
- (void)updatePrintOptionsList;
- (void)updatePrinterInfo;

@end
