/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintMoreOptionsSection : UIPrintOptionSection {
    UIPrintAccountInfoOption * _accountInfoPrintOption;
    UIPrintBlackWhiteOption * _blackWhiteOption;
    UIPrintCopiesOption * _copiesOption;
    UIPrintImagePDFAnnotationsOption * _imagePDFAnnotationsPrintOption;
    UIPrintOrientationOption * _orientationPrintOption;
    UIPrintPageRangeOption * _pageRangeOption;
    UIPrintPaperSizeOption * _paperSizePrintOption;
    UIPrintTwoSidedOption * _twoSidedOption;
}

@property (nonatomic, retain) UIPrintAccountInfoOption *accountInfoPrintOption;
@property (nonatomic, retain) UIPrintBlackWhiteOption *blackWhiteOption;
@property (nonatomic, retain) UIPrintCopiesOption *copiesOption;
@property (nonatomic, retain) UIPrintImagePDFAnnotationsOption *imagePDFAnnotationsPrintOption;
@property (nonatomic, retain) UIPrintOrientationOption *orientationPrintOption;
@property (nonatomic, retain) UIPrintPageRangeOption *pageRangeOption;
@property (nonatomic, retain) UIPrintPaperSizeOption *paperSizePrintOption;
@property (nonatomic, retain) UIPrintTwoSidedOption *twoSidedOption;

- (void).cxx_destruct;
- (id)accountInfoPrintOption;
- (id)blackWhiteOption;
- (id)copiesOption;
- (void)dealloc;
- (id)imagePDFAnnotationsPrintOption;
- (id)initWithPrintInfo:(id)arg1 printPanelViewController:(id)arg2;
- (id)orientationPrintOption;
- (id)pageRangeOption;
- (id)paperSizePrintOption;
- (void)setAccountInfoPrintOption:(id)arg1;
- (void)setBlackWhiteOption:(id)arg1;
- (void)setCopiesOption:(id)arg1;
- (void)setCurrentPrinter:(id)arg1;
- (void)setImagePDFAnnotationsPrintOption:(id)arg1;
- (void)setOrientationPrintOption:(id)arg1;
- (void)setPageRangeOption:(id)arg1;
- (void)setPaperSizePrintOption:(id)arg1;
- (void)setTwoSidedOption:(id)arg1;
- (id)twoSidedOption;
- (void)updatePrintOptionsList;
- (void)updatePrinterInfo;

@end
