/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintStandardOptionsSection : UIPrintOptionSection {
    UIPrintPresetsOption * _presetsOption;
    UIPrinterSelectionOption * _printerSelectionOption;
}

@property (nonatomic, retain) UIPrintPresetsOption *presetsOption;
@property (nonatomic, retain) UIPrinterSelectionOption *printerSelectionOption;

- (void).cxx_destruct;
- (id)initWithPrintInfo:(id)arg1 printPanelViewController:(id)arg2;
- (id)presetsOption;
- (id)printerSelectionOption;
- (void)setCurrentPrinter:(id)arg1;
- (void)setPresetsOption:(id)arg1;
- (void)setPrinterSelectionOption:(id)arg1;
- (void)setShowContactingPrinter:(bool)arg1;
- (void)updatePrintOptionsList;
- (void)updatePrinterInfo;

@end
