/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintCopiesOption : UIPrintOption

- (id)printOptionTableViewCell;
- (bool)shouldShow;
- (void)updateCopies:(id)arg1;

@end
