/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintScaleToFitOption : UIPrintOption

- (id)printOptionTableViewCell;
- (bool)shouldShow;
- (id)summary;
- (void)updateValue:(id)arg1;

@end
