/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UISheetPresentationControllerDetent : NSObject <NSSecureCoding> {
    double  __constant;
    bool  __createdWithDeprecatedInitializer;
    NSString * __identifier;
    id /* block */  __internalBlock;
    long long  __type;
}

@property (nonatomic, readonly) double _constant;
@property (nonatomic, readonly) bool _createdWithDeprecatedInitializer;
@property (nonatomic, readonly) NSString *_identifier;
@property (nonatomic, readonly) id /* block */ _internalBlock;
@property (nonatomic, readonly) long long _type;

+ (id)_detentWithContainerViewBlock:(id /* block */)arg1;
+ (id)_detentWithIdentifier:(id)arg1 constant:(double)arg2;
+ (id)_detentWithIdentifier:(id)arg1 containerViewBlock:(id /* block */)arg2;
+ (id)_detentWithIdentifier:(id)arg1 resolutionContextBlock:(id /* block */)arg2;
+ (id)_detentWithResolutionContextBlock:(id /* block */)arg1;
+ (id)largeDetent;
+ (id)mediumDetent;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (double)_constant;
- (bool)_createdWithDeprecatedInitializer;
- (id)_identifier;
- (id /* block */)_internalBlock;
- (void)_setIdentifier:(id)arg1;
- (long long)_type;
- (double)_valueInContainerView:(id)arg1 resolutionContext:(id)arg2;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithType:(long long)arg1 identifier:(id)arg2 internalBlock:(id /* block */)arg3 constant:(double)arg4;
- (bool)isEqual:(id)arg1;

@end
