/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStatusBarLiquidDetectionItemView : UIStatusBarItemView

// Image: /usr/lib/libMainThreadChecker.dylib

- (id)accessibilityHUDRepresentation;
- (id)contentsImage;

@end
