/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITableConstants_Pad : UITableConstants_IOS

+ (id)sharedConstants;

- (struct _UITableConstantsBackgroundProperties { bool x1; id x2; id x3; bool x4; long long x5; long long x6; double x7; double x8; bool x9; id x10; double x11; struct NSDirectionalEdgeInsets { double x_12_1_1; double x_12_1_2; double x_12_1_3; double x_12_1_4; } x12; })defaultCellBackgroundPropertiesForTableViewStyle:(long long)arg1 state:(id)arg2;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })defaultLayoutMarginsForCell:(id)arg1 inTableView:(id)arg2;
- (double)defaultRowHeightForTableView:(id)arg1;
- (double)defaultRowHeightForTableView:(id)arg1 cellStyle:(long long)arg2;
- (double)minimumContentViewHeightForFont:(id)arg1 traitCollection:(id)arg2;
- (bool)supportsUserInterfaceStyles;

@end
