/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
 */

@interface AVVCContextSettings : NSObject {
    NSString * _activationDeviceUID;
    long long  _activationMode;
    bool  _announceCallsEnabled;
}

@property (nonatomic, retain) NSString *activationDeviceUID;
@property (nonatomic) long long activationMode;
@property (nonatomic) bool announceCallsEnabled;

- (id)activationDeviceUID;
- (long long)activationMode;
- (bool)announceCallsEnabled;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)initWithMode:(long long)arg1 deviceUID:(id)arg2;
- (void)setActivationDeviceUID:(id)arg1;
- (void)setActivationMode:(long long)arg1;
- (void)setAnnounceCallsEnabled:(bool)arg1;

@end
