/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
 */

@interface AVVCDuckOverride : NSObject {
    NSNumber * _duckOthers;
    NSNumber * _duckToLevel;
    NSNumber * _mixWithOthers;
}

@property (nonatomic, retain) NSNumber *duckOthers;
@property (nonatomic, retain) NSNumber *duckToLevel;
@property (nonatomic, retain) NSNumber *mixWithOthers;

- (void)dealloc;
- (id)description;
- (id)duckOthers;
- (id)duckToLevel;
- (id)initWithDuckOthers:(id)arg1 duckToLevel:(id)arg2 mixWithOthers:(id)arg3;
- (id)mixWithOthers;
- (void)setDuckOthers:(id)arg1;
- (void)setDuckToLevel:(id)arg1;
- (void)setMixWithOthers:(id)arg1;

@end
