/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSFamilyEndpointData : NSObject <NSSecureCoding> {
    NSString * _buildVersion;
    NSString * _deviceColor;
    NSString * _deviceName;
    long long  _deviceType;
    NSString * _deviceUniqueID;
}

@property (nonatomic, retain) NSString *buildVersion;
@property (nonatomic, retain) NSString *deviceColor;
@property (nonatomic, retain) NSString *deviceName;
@property (nonatomic) long long deviceType;
@property (nonatomic, retain) NSString *deviceUniqueID;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)buildVersion;
- (id)debugDescription;
- (id)deviceColor;
- (id)deviceName;
- (long long)deviceType;
- (id)deviceUniqueID;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDeviceName:(id)arg1 privateDeviceData:(id)arg2;
- (id)initWithDictionary:(id)arg1;
- (void)setBuildVersion:(id)arg1;
- (void)setDeviceColor:(id)arg1;
- (void)setDeviceName:(id)arg1;
- (void)setDeviceType:(long long)arg1;
- (void)setDeviceUniqueID:(id)arg1;

@end
