/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Network.framework/Network
 */

@interface NWURLSessionResponseConsumerDataDelegate : NSObject <NWURLSessionResponseConsumer> {
    NSURLResponse * _currentResponse;
    NWURLSessionDelegateWrapper * _delegateWrapper;
    NWURLSessionDataTask * _task;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) NSURLResponse *response;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)deliverData:(id)arg1 complete:(bool)arg2 completionHandler:(id /* block */)arg3;
- (void)deliverResponse:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)response;

@end
