/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Network.framework/Network
 */

@interface NWURLSessionDelegateWrapper : NSObject {
    id  _delegate;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    NSOperationQueue * _operationQueue;
    NSURLSession * _session;
    NSObject<OS_dispatch_queue> * _workQueue;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  lock;
}

- (void).cxx_destruct;

@end
