/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@interface MSVFrameworkDescription : NSObject {
    bool  _debug;
    NSString * _name;
    bool  _root;
    NSUUID * _uuid;
}

@property (getter=isDebug, nonatomic, readonly) bool debug;
@property (nonatomic, readonly) NSString *name;
@property (getter=isRoot, nonatomic, readonly) bool root;
@property (nonatomic, readonly) NSUUID *uuid;

- (void).cxx_destruct;
- (id)description;
- (id)initWithName:(id)arg1 uuid:(id)arg2 root:(bool)arg3 debug:(bool)arg4;
- (bool)isDebug;
- (bool)isRoot;
- (id)name;
- (id)uuid;

@end
