/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWAmbientLightSensor : NSObject {
    NSObject<OS_dispatch_queue> * _alsQueue;
    NSObject<OS_dispatch_semaphore> * _exitSemaphore;
    struct __IOHIDEventSystemClient { } * _hidSystemClient;
    int  _luxLevel;
}

@property (nonatomic, readonly) int luxLevel;

+ (void)initialize;

- (void)dealloc;
- (id)init;
- (int)luxLevel;

@end
