/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWCameraStreamingMonitorClientInfo : NSObject {
    PAAccessInterval * _accessInterval;
    bool  _cameraAccessGranted;
    struct { 
        unsigned int val[8]; 
    }  _clientAuditToken;
    bool  _streaming;
    bool  _terminated;
}

- (void)dealloc;

@end
