/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWCinematicVideoMetadataNode : BWNode {
    struct OpaqueCMBlockBuffer { } * _emptyMetadataSampleData;
    unsigned int  _localIDForAperture_BE;
    unsigned int  _localIDForCinematographyMetadata_BE;
    unsigned int  _localIDForDisparity_BE;
    unsigned int  _localIDForRenderingMetadata_BE;
    unsigned int  _localIDForStabilizationMetadata_BE;
    struct opaqueCMFormatDescription { } * _metadataFormatDescription;
    BWNodeOutput * _metadataOutput;
    BWNodeOutput * _passthruOutput;
    bool  _previousGeneratedMetadataBufferWasEmpty;
}

@property (nonatomic, readonly) BWNodeOutput *metadataOutput;
@property (nonatomic, readonly) BWNodeOutput *passthruOutput;

+ (void)initialize;

- (void)_emitMetadataWithCinematographyMetadata:(id)arg1 time:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2;
- (struct OpaqueCMBlockBuffer { }*)_emptyMetadataBlockBuffer;
- (void)configurationWithID:(long long)arg1 updatedFormat:(id)arg2 didBecomeLiveForInput:(id)arg3;
- (void)dealloc;
- (void)didReachEndOfDataForInput:(id)arg1;
- (void)didSelectFormat:(id)arg1 forInput:(id)arg2;
- (void)handleDroppedSample:(id)arg1 forInput:(id)arg2;
- (id)init;
- (id)metadataOutput;
- (id)nodeSubType;
- (id)nodeType;
- (id)passthruOutput;
- (void)renderSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 forInput:(id)arg2;

@end
