/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWDeferredBufferIntermediate : BWDeferredIntermediate {
    NSDictionary * _attributes;
    struct __CVBuffer { } * _buffer;
    unsigned long long  _bufferType;
    int  _compressionProfile;
    NSString * _metadataTag;
    NSString * _portType;
}

@property (nonatomic, readonly) NSDictionary *attributes;
@property (nonatomic, readonly) struct __CVBuffer { }*buffer;
@property (nonatomic, readonly) unsigned long long bufferType;
@property (nonatomic, readonly) int compressionProfile;
@property (nonatomic, readonly) NSString *metadataTag;
@property (nonatomic, readonly) NSString *portType;

+ (bool)supportsSecureCoding;

- (id)archive:(int*)arg1;
- (id)attributes;
- (struct __CVBuffer { }*)buffer;
- (unsigned long long)bufferType;
- (int)compressionProfile;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)fetchAndRetain:(int*)arg1;
- (int)flush;
- (id)initWithBuffer:(struct __CVBuffer { }*)arg1 tag:(id)arg2 bufferType:(unsigned long long)arg3 metadataTag:(id)arg4 portType:(id)arg5 compressionProfile:(int)arg6 URL:(id)arg7;
- (id)initWithCoder:(id)arg1;
- (id)metadataTag;
- (id)portType;
- (int)setBuffer:(struct __CVBuffer { }*)arg1;
- (int)setURL:(id)arg1 prefetchQueue:(id)arg2;

@end
