/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWDeepZoomProcessorControllerConfiguration : BWStillImageProcessorConfiguration {
    NSDictionary * _deepZoomParametersByPortType;
    BWVideoFormat * _inputFormat;
    BWVideoFormat * _outputFormat;
    int  _version;
}

@property (nonatomic, retain) BWVideoFormat *inputFormat;
@property (nonatomic, retain) BWVideoFormat *outputFormat;
@property (nonatomic) int version;

- (void)dealloc;
- (bool)doDeepZoomForSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1;
- (id)inputFormat;
- (float)maxScaleFactorForPortType:(id)arg1;
- (float)minScaleFactorForPortType:(id)arg1;
- (id)outputFormat;
- (void)setInputFormat:(id)arg1;
- (void)setOutputFormat:(id)arg1;
- (void)setSensorConfigurations:(id)arg1;
- (void)setVersion:(int)arg1;
- (int)version;

@end
