/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWFusionTrackerNode : BWInferenceNode {
    <MTLEvent> * _backpressureEvent;
    unsigned long long  _backpressureEventNumber;
    NSObject<OS_dispatch_semaphore> * _backpressureSemaphore;
    FTCinematicTracker * _cinematicTracker;
    unsigned long long  _framesSinceLastDDR;
    NSSet * _humanPosePreventionSet;
    BWVideoDepthInferenceConfiguration * _videoDepthConfiguration;
}

@property (nonatomic, readonly) BWVideoDepthInferenceConfiguration *videoDepthConfiguration;

+ (void)initialize;

- (bool)_attachISPDetectionsFromSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 toTrackingInput:(id)arg2 withFrameTimestamp:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg3;
- (void)dealloc;
- (void)handleDroppedSample:(id)arg1 forInput:(id)arg2;
- (id)initWithCaptureDevice:(id)arg1 scheduler:(id)arg2 priority:(unsigned int)arg3;
- (bool)intermediateResourceTrackingAllowedForAttachedMediaKey:(id)arg1;
- (id)nodeSubType;
- (id)nodeType;
- (void)prepareForCurrentConfigurationToBecomeLive;
- (void)renderSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 forInput:(id)arg2;
- (id)videoDepthConfiguration;
- (void)willEmitSampleBufferAlways:(struct opaqueCMSampleBuffer { }*)arg1;

@end
