/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWLearnedMattingInferenceConfiguration : BWTiledEspressoInferenceConfiguration {
    float  _mainImageDownscalingFactor;
    <MTLCommandQueue> * _metalCommandQueue;
}

@property (nonatomic) float mainImageDownscalingFactor;
@property (nonatomic, retain) <MTLCommandQueue> *metalCommandQueue;

- (void)dealloc;
- (float)mainImageDownscalingFactor;
- (id)metalCommandQueue;
- (void)setMainImageDownscalingFactor:(float)arg1;
- (void)setMetalCommandQueue:(id)arg1;

@end
