/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWRealtimeCinematographyNode : BWNode <PTCinematographyStreamDelegate> {
    float  _alphaLowLight;
    int  _alphaRampFrameCount;
    int  _autoFocusUpdateFrameDelay;
    BWFigVideoCaptureDevice * _captureDevice;
    PTCinematographyStream * _cinematographyStream;
    bool  _currentStateIsBrightEnough;
    BWNodeOutput * _detectedObjectsOutput;
    int  _framesSinceAutoFocusUpdate;
    PTGlobalCinematographyMetadataVersion1 * _globalCinematographyMetadata;
    PTGlobalVideoMetadata * _globalMetadata;
    PTGlobalRenderingMetadataVersion1 * _globalRenderingMetadata;
    PTGlobalStabilizationMetadataVersion1 * _globalStabilizationMetadata;
    PTGlobalVideoHeaderMetadataVersion1 * _globalVideoHeaderMetadata;
    bool  _globalsWereSet;
    bool  _hasAutoFocus;
    bool  _hasSeenDepth;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _lastFixedFocusRect;
    NSDictionary * _latestDetections;
    long long  _latestFocusDectionTrackID;
    int  _luxLevelThreshold;
    BWNodeOutput * _movieFileOutput;
    bool  _pastFramesWereBrightEnough;
    int  _pastFramesWereBrightEnoughPointer;
    BWNodeOutput * _previewOutput;
    struct opaqueCMSampleBuffer { } * _previousSampleBuffer;
    float  _simulatedAperture;
    int  focusMode;
}

@property (nonatomic, readonly) NSString *cinematographyModelVersionString;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) BWNodeOutput *detectedObjectsOutput;
@property (nonatomic, readonly) NSData *globalMetadata;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) BWNodeOutput *movieFileOutput;
@property (nonatomic, readonly) BWNodeOutput *previewOutput;
@property (nonatomic) float simulatedAperture;
@property (readonly) Class superclass;

+ (void)initialize;

- (void)_emitMovieFileDropForPreviousSampleBuffer;
- (void)_emitSampleBufferOnMetadataOutput:(struct opaqueCMSampleBuffer { }*)arg1 cinematographyFrame:(id)arg2;
- (void)_updateAlphaLowLightWithMetadata:(id)arg1 imageSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg2;
- (void)_updateAutoFocus:(id)arg1;
- (void)_updateGlobalMetadata:(struct opaqueCMSampleBuffer { }*)arg1;
- (id)cinematographyModelVersionString;
- (void)cinematographyStream:(id)arg1 prioritizeTrackWithId:(unsigned long long)arg2;
- (void)configurationWithID:(long long)arg1 updatedFormat:(id)arg2 didBecomeLiveForInput:(id)arg3;
- (void)dealloc;
- (id)detectedObjectsOutput;
- (void)didReachEndOfDataForInput:(id)arg1;
- (void)didSelectFormat:(id)arg1 forInput:(id)arg2;
- (id)globalMetadata;
- (void)handleDroppedSample:(id)arg1 forInput:(id)arg2;
- (id)initWithObjectMetadataIdentifiers:(id)arg1 captureDevice:(id)arg2 tuningParameters:(id)arg3 videoDepthConfiguration:(id)arg4;
- (id)movieFileOutput;
- (id)nodeSubType;
- (id)nodeType;
- (id)previewOutput;
- (void)renderSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 forInput:(id)arg2;
- (void)setSimulatedAperture:(float)arg1;
- (float)simulatedAperture;

@end
