/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWTiledEspressoInferenceConfiguration : BWInferenceConfiguration {
    bool  _forceSynchronousInference;
}

@property (nonatomic) bool forceSynchronousInference;

- (bool)forceSynchronousInference;
- (void)setForceSynchronousInference:(bool)arg1;

@end
