/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWUBInferenceControllerInput : BWStillImageProcessorInput {
    bool  _generateFaceObservations;
    bool  _generateLowResPersonInstanceMasks;
    bool  _generateLowResPersonSegmentationMask;
    bool  _generateSemanticSkinMatte;
    bool  _generateSemanticSkyMatte;
    bool  _generateSmartCameraClassifications;
    struct opaqueCMSampleBuffer { } * _inferenceImage;
    struct opaqueCMSampleBuffer { } * _propagationImage;
}

@property (nonatomic) bool generateFaceObservations;
@property (nonatomic) bool generateLowResPersonInstanceMasks;
@property (nonatomic) bool generateLowResPersonSegmentationMask;
@property (nonatomic) bool generateSemanticSkinMatte;
@property (nonatomic) bool generateSemanticSkyMatte;
@property (nonatomic) bool generateSmartCameraClassifications;
@property (nonatomic, readonly) struct opaqueCMSampleBuffer { }*inferenceImage;
@property (nonatomic, readonly) struct opaqueCMSampleBuffer { }*propagationImage;

- (void)addInferenceImage:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)addPropagationImage:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)dealloc;
- (bool)generateFaceObservations;
- (bool)generateLowResPersonInstanceMasks;
- (bool)generateLowResPersonSegmentationMask;
- (bool)generateSemanticSkinMatte;
- (bool)generateSemanticSkyMatte;
- (bool)generateSmartCameraClassifications;
- (struct opaqueCMSampleBuffer { }*)inferenceImage;
- (struct opaqueCMSampleBuffer { }*)propagationImage;
- (void)setGenerateFaceObservations:(bool)arg1;
- (void)setGenerateLowResPersonInstanceMasks:(bool)arg1;
- (void)setGenerateLowResPersonSegmentationMask:(bool)arg1;
- (void)setGenerateSemanticSkinMatte:(bool)arg1;
- (void)setGenerateSemanticSkyMatte:(bool)arg1;
- (void)setGenerateSmartCameraClassifications:(bool)arg1;

@end
