/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWVideoDepthNode : BWNode <BWInferenceFormatProvider, BWInferencePixelBufferPoolProvider> {
    <MTLEvent> * _backpressureEvent;
    struct __CVBuffer { } * _blankDisparityPixelBuffer;
    BWFigVideoCaptureDevice * _captureDevice;
    struct opaqueCMFormatDescription { } * _colorImageFormatDescription;
    BWVideoFormat * _cvsColorInputVideoFormat;
    struct opaqueCMFormatDescription { } * _depthFormatDescription;
    struct { 
        int width; 
        int height; 
    }  _depthOutputDimensions;
    BWInferenceVideoFormat * _disparityInputFormat;
    BWInferenceEngine * _inferenceEngine;
    BWInferenceScheduler * _inferenceScheduler;
    struct __CVBuffer { } * _initialDisparityPixelBuffer;
    struct __CVBuffer { } * _initialFilteredPixelBuffer;
    BWPixelBufferPool * _internalDisparityPool;
    BWVideoFormat * _internalDisparityVideoFormat;
    struct opaqueCMSampleBuffer { } * _previousDisparitySampleBuffer;
    struct __CVBuffer { } * _previousFilteredDisparityPixelBuffer;
    struct opaqueCMSampleBuffer { } * _previousFilteredDisparitySampleBuffer;
    BWInferenceVideoFormat * _primaryMediaInputFormat;
    bool  _structuredLightIsOccluded;
    bool  _videoDepthEnabled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (void)initialize;

- (void)_copyPreviousFilteredDisparityIfPossible:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)dealloc;
- (void)didSelectFormat:(id)arg1 forInput:(id)arg2 forAttachedMediaKey:(id)arg3;
- (id)initWithInferenceScheduler:(id)arg1 captureDevice:(id)arg2 cinematographyModelVersionString:(id)arg3 videoDepthConfiguration:(id)arg4;
- (id)inputFormatForAttachedMediaKey:(id)arg1;
- (id)inputInferenceVideoFormatForAttachedMediaKey:(id)arg1;
- (id)inputVideoFormatForAttachedMediaKey:(id)arg1;
- (bool)intermediateResourceTrackingAllowedForAttachedMediaKey:(id)arg1;
- (id)nodeSubType;
- (id)nodeType;
- (id)outputFormatForAttachedMediaKey:(id)arg1;
- (id)outputVideoFormatForAttachedMediaKey:(id)arg1;
- (void)prepareForCurrentConfigurationToBecomeLive;
- (id)preparedOutputPixelBufferPoolForAttachedMediaKey:(id)arg1 format:(id)arg2;
- (void)renderSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 forInput:(id)arg2;

@end
