/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface FigCaptureStillImageSinkPipelineConfiguration : FigCaptureBaseStillImageSinkPipelineConfiguration {
    int  _clientPID;
    bool  _gnrHDRSupported;
    bool  _hdrSupported;
    bool  _isIrisSupported;
    bool  _stereoFusionSupported;
    NSDictionary * _stillImageColorInfoForFramesOriginatingFromVideoStream;
    bool  _stillImageISPChromaNoiseReductionEnabled;
}

- (void)dealloc;

@end
