/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface FigCapturePreviewSinkPipelineConfiguration : NSObject {
    bool  _cinematicVideoEnabled;
    bool  _clientIsCameraOrDerivative;
    bool  _deferredPrepareEnabled;
    FigDepthDataCaptureConnectionConfiguration * _depthDataConnectionConfiguration;
    bool  _depthFromMonocularNetworkEnabled;
    bool  _displayPipeRequiresPacked10BitPixelFormatForP3Input;
    bool  _focusBlurMapForDepthFiltersEnabled;
    bool  _generatesHistogram;
    bool  _ispPreviewJitterCompensationEnabled;
    int  _maxLossyCompressionLevel;
    FigMetadataObjectCaptureConnectionConfiguration * _metadataObjectConnectionConfiguration;
    bool  _overCaptureEnabled;
    FigVideoCaptureConnectionConfiguration * _previewTimeMachineConnectionConfiguration;
    bool  _primaryCaptureRectModificationEnabled;
    bool  _remoteVideoPreview;
    FigVideoCaptureConnectionConfiguration * _sceneClassifierConnectionConfiguration;
    struct { 
        unsigned short major; 
        unsigned short minor; 
        unsigned short patch; 
    }  _sceneClassifierPipelineVersion;
    bool  _smartCameraMotionDetectionEnabled;
    int  _sourceColorSpaceProperties;
    bool  _sourceIsBravoDevice;
    bool  _sourcePixelFormatIsFullRange;
    FigVideoCaptureConnectionConfiguration * _stillImageConnectionConfiguration;
    FigVideoCaptureConnectionConfiguration * _videoDataConnectionConfiguration;
    FigVideoCaptureConnectionConfiguration * _videoPreviewSinkConnectionConfiguration;
    double  _videoStabilizationOverscan;
    FigVideoCaptureConnectionConfiguration * _videoThumbnailConnectionConfiguration;
    bool  _vitalityScoringEnabled;
}

- (void)dealloc;

@end
