/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface FigCaptureVideoDataSinkConfiguration : FigCaptureSinkConfiguration {
    bool  _derivedFromPreview;
    bool  _discardsLateVideoFrames;
    bool  _sceneStabilityMetadataEnabled;
}

@property (nonatomic) bool derivedFromPreview;
@property (nonatomic) bool discardsLateVideoFrames;
@property (nonatomic) bool sceneStabilityMetadataEnabled;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)copyXPCEncoding;
- (bool)derivedFromPreview;
- (id)description;
- (bool)discardsLateVideoFrames;
- (id)initWithXPCEncoding:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)sceneStabilityMetadataEnabled;
- (void)setDerivedFromPreview:(bool)arg1;
- (void)setDiscardsLateVideoFrames:(bool)arg1;
- (void)setSceneStabilityMetadataEnabled:(bool)arg1;
- (int)sinkType;

@end
