/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface FigCaptureCameraSourcePipeline : FigCaptureSourcePipeline {
    NSMutableDictionary * _backgroundBlurNodesBySourceDeviceType;
    BWFigVideoCaptureDevice * _captureDevice;
    struct OpaqueFigCaptureSource { } * _captureSource;
    FigCaptureSourceDepthDataFormat * _captureSourceDepthDataFormat;
    FigCaptureSourceVideoFormat * _captureSourceVideoFormat;
    NSMutableDictionary * _cinematicFramingNodesBySourceDeviceType;
    BWNodeOutput * _depthOutput;
    NSDictionary * _detectedObjectsOutputsBySourceDeviceType;
    int  _devicePosition;
    int  _deviceType;
    bool  _hardwareDepthFilteringEnabled;
    BWMultiStreamCameraSourceNode * _infraredSourceNode;
    BWMemoryPool * _memoryPool;
    unsigned int  _nextVideoCaptureOutputIndexBySourceDeviceType;
    bool  _overCapturePercentage;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _overscanRect;
    NSArray * _previewFilters;
    NSDictionary * _previewOutputsBySourceDeviceType;
    BWNodeOutput * _sourceFormatReferenceOutput;
    BWMultiStreamCameraSourceNode * _sourceNode;
    NSMutableArray * _sourceNodes;
    bool  _stillImageOutputDerivesFromVideoCaptureOutput;
    int  _stillImageOutputRetainedBufferCountOverride;
    NSDictionary * _stillImageOutputsByPortType;
    BWMultiStreamCameraSourceNode * _superWideSourceNode;
    NSMutableArray * _synchronizerNodes;
    BWMultiStreamCameraSourceNode * _telephotoSourceNode;
    bool  _useCaptureOutputForPreview;
    NSDictionary * _videoCaptureOutputsArrayBySourceDeviceType;
    NSDictionary * _visionDataOutputsBySourceDeviceType;
}

+ (void)initialize;

- (void)dealloc;

@end
