/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
 */

@interface SHSheetServiceManager : NSObject <SFShareSheetSlotManagerDelegate, SHSheetHostServiceInterface> {
    long long  _connectionState;
    <SHSheetServiceManagerDelegate> * _delegate;
    UISUIActivityViewControllerConfiguration * _hostConfiguration;
    SHSheetSession * _session;
    SFShareSheetSlotManager * _slotManager;
    bool  _updateAfterConnection;
}

@property (nonatomic, readonly) long long connectionState;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SHSheetServiceManagerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UISUIActivityViewControllerConfiguration *hostConfiguration;
@property (nonatomic, readonly) SHSheetSession *session;
@property (nonatomic, readonly) SFShareSheetSlotManager *slotManager;
@property (readonly) Class superclass;
@property (nonatomic) bool updateAfterConnection;

- (void).cxx_destruct;
- (void)_handleConnectionCompletion;
- (void)_invalidateSlotManagerIfNeeded;
- (void)_sendConfiguration:(id)arg1;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (void)connect;
- (void)connectionInterrupted;
- (long long)connectionState;
- (void)dataSourceUpdatedWithSessionConfiguration:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (void)favoriteUserDefaultsActivity:(bool)arg1 withIdentifier:(id)arg2 activityCategory:(long long)arg3;
- (id)hostConfiguration;
- (id)initWithSession:(id)arg1;
- (void)longPressShareActivityWithIdentifier:(id)arg1;
- (void)performActionActivityWithIdentifier:(id)arg1;
- (void)performActivityInHostWithUUID:(id)arg1;
- (void)performAirDropActivityInHostWithNoContentView:(bool)arg1;
- (void)performEditAction;
- (void)performExtensionActivityInHostWithBundleID:(id)arg1 request:(id)arg2;
- (void)performPersonSuggestionWithIdentifier:(id)arg1;
- (void)performShareActivityWithIdentifier:(id)arg1;
- (void)performShortcutActivityInHostWithBundleID:(id)arg1 singleUseToken:(id)arg2;
- (void)performUserDefaultsActivityWithIdentifier:(id)arg1 activityCategory:(long long)arg2;
- (void)performUserDefaultsWithFavoritesProxies:(id)arg1 suggestionProxies:(id)arg2 orderedUUIDs:(id)arg3 activityCategory:(long long)arg4;
- (void)provideFeedbackForPeopleSugestionIdentifier:(id)arg1;
- (void)removePersonSuggestionWithIdentifier:(id)arg1;
- (void)reportActivityWithInfo:(id)arg1;
- (id)session;
- (void)setConnectionState:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setHostConfiguration:(id)arg1;
- (void)setProgress:(id)arg1 withTopText:(id)arg2 bottomText:(id)arg3 forNodeWithIdentifier:(id)arg4 shouldPulse:(id)arg5 animated:(bool)arg6;
- (void)setUpdateAfterConnection:(bool)arg1;
- (id)slotManager;
- (void)toggleUserDefaultsActivityWithIdentifier:(id)arg1 activityCategory:(long long)arg2;
- (bool)updateAfterConnection;
- (void)updateAsynchronously:(bool)arg1;
- (void)updateUserDefaultsFavorites:(id)arg1 activityCategory:(long long)arg2;
- (void)willPerformInServiceActivityWithRequest:(id)arg1 completion:(id /* block */)arg2;

@end
