/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
 */

@interface SHSheetFactory : NSObject

+ (id)createAirdropViewControllerWithNoContentView:(bool)arg1 delegate:(id)arg2;
+ (id)createContentViewControllerWithSession:(id)arg1 presenter:(id)arg2;
+ (id)createMainPresenterWithContext:(id)arg1;
+ (id)createOptionsViewControllerWithContext:(id)arg1 delegate:(id)arg2;
+ (id)createUserDefaultsViewControllerWithContext:(id)arg1 delegate:(id)arg2;

@end
