/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
 */

@interface UIAirDropNode : NSObject <NSSecureCoding, SHSheetLoadableProxy> {
    _Atomic unsigned int  _bottomLabelSlotID;
    bool  _disabled;
    bool  _hasSquareImage;
    _Atomic unsigned int  _imageSlotID;
    id /* block */  _loadHandler;
    bool  _magicHead;
    _Atomic unsigned int  _mainLabelSlotID;
    NSUUID * _nodeIdentifier;
    bool  _peopleSuggestion;
    bool  _restricted;
    long long  _selectionReason;
    SDSuggestionNode * _suggestionNode;
    _Atomic unsigned int  _transportSlotID;
    bool  _wantsTwoLines;
}

@property unsigned int bottomLabelSlotID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isDisabled, nonatomic) bool disabled;
@property (nonatomic) bool hasSquareImage;
@property (readonly) unsigned long long hash;
@property unsigned int imageSlotID;
@property (nonatomic, copy) id /* block */ loadHandler;
@property (nonatomic) bool magicHead;
@property unsigned int mainLabelSlotID;
@property (nonatomic, retain) NSUUID *nodeIdentifier;
@property (getter=isPeopleSuggestion, nonatomic) bool peopleSuggestion;
@property (getter=isRestricted, nonatomic) bool restricted;
@property (nonatomic) long long selectionReason;
@property (nonatomic, retain) SDSuggestionNode *suggestionNode;
@property (readonly) Class superclass;
@property unsigned int transportSlotID;
@property (nonatomic) bool wantsTwoLines;

+ (id)nodeWithImageSlotID:(unsigned int)arg1 labelSlotID:(unsigned int)arg2 transportSlotID:(unsigned int)arg3 isPeopleSuggestion:(bool)arg4;
+ (id)nodeWithSuggestionNode:(id)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (unsigned int)bottomLabelSlotID;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasSquareImage;
- (unsigned long long)hash;
- (unsigned int)imageSlotID;
- (id)initWithCoder:(id)arg1;
- (bool)isDisabled;
- (bool)isEqual:(id)arg1;
- (bool)isPeopleSuggestion;
- (bool)isRestricted;
- (bool)load;
- (id /* block */)loadHandler;
- (bool)magicHead;
- (unsigned int)mainLabelSlotID;
- (id)nodeIdentifier;
- (long long)selectionReason;
- (void)setBottomLabelSlotID:(unsigned int)arg1;
- (void)setDisabled:(bool)arg1;
- (void)setHasSquareImage:(bool)arg1;
- (void)setImageSlotID:(unsigned int)arg1;
- (void)setLoadHandler:(id /* block */)arg1;
- (void)setMagicHead:(bool)arg1;
- (void)setMainLabelSlotID:(unsigned int)arg1;
- (void)setNodeIdentifier:(id)arg1;
- (void)setPeopleSuggestion:(bool)arg1;
- (void)setRestricted:(bool)arg1;
- (void)setSelectionReason:(long long)arg1;
- (void)setSuggestionNode:(id)arg1;
- (void)setTransportSlotID:(unsigned int)arg1;
- (void)setWantsTwoLines:(bool)arg1;
- (id)suggestionNode;
- (unsigned int)transportSlotID;
- (bool)wantsTwoLines;

@end
