/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Pasteboard.framework/Pasteboard
 */

@interface PBCalloutBarPasteButtonTag : PBPasteButtonTag {
    unsigned long long  _contentScaleLevel;
    struct CGSize { 
        double width; 
        double height; 
    }  _size;
    struct CGPoint { 
        double x; 
        double y; 
    }  _titleOrigin;
    double  _titleWidth;
    unsigned long long  _variantIndex;
}

@property (readonly) unsigned long long contentScaleLevel;
@property (readonly) struct CGSize { double x1; double x2; } size;
@property (readonly) struct CGPoint { double x1; double x2; } titleOrigin;
@property (readonly) double titleWidth;
@property (readonly) unsigned long long variantIndex;

+ (bool)supportsSecureCoding;

- (id)_acceptCalloutBarPasteButtonTagVisit:(id /* block */)arg1 systemInputAssistantPasteButtonTagVisit:(id /* block */)arg2 undoInteractionHUDIconPasteButtonTagVisit:(id /* block */)arg3 undoInteractionHUDTextPasteButtonTagVisit:(id /* block */)arg4 contextMenuPasteButtonTagVisit:(id /* block */)arg5;
- (unsigned long long)contentScaleLevel;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)grade;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithVariantIndex:(unsigned long long)arg1 size:(struct CGSize { double x1; double x2; })arg2 titleOrigin:(struct CGPoint { double x1; double x2; })arg3 titleWidth:(double)arg4 contentScaleLevel:(unsigned long long)arg5;
- (bool)isEqual:(id)arg1;
- (id)resolvedStyleForStyle:(id)arg1;
- (struct CGSize { double x1; double x2; })size;
- (struct CGPoint { double x1; double x2; })titleOrigin;
- (double)titleWidth;
- (unsigned long long)variantIndex;

@end
