/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
 */

@interface UISSlotMachine : NSObject {
    NSMutableDictionary * _cachedContents;
    CAContext * _layerContext;
    unsigned long long  _options;
    <UISSlotDrawer> * _slotDrawer;
}

@property (nonatomic, readonly) NSSet *allTags;

- (void).cxx_destruct;
- (id)allTags;
- (id)initWithSlotDrawer:(id)arg1 options:(unsigned long long)arg2;
- (id)remoteContentForLayerContextWithId:(unsigned long long)arg1 style:(id)arg2 tag:(id)arg3;
- (void)removeContentForStyle:(id)arg1 tag:(id)arg2;
- (void)removeContentsForTag:(id)arg1;

@end
