/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
 */

@interface UISSlotStyle : NSObject <NSCopying, NSSecureCoding> {
    union { 
        unsigned int all; 
        struct { 
            unsigned int accessibilityButtonShapes : 1; 
            unsigned int accessibilityContrast : 1; 
            unsigned int displayRange : 2; 
            unsigned int displayScale : 3; 
            unsigned int layoutDirection : 1; 
            unsigned int legibilityWeight : 1; 
            unsigned int preferredContentSizeCategory : 4; 
            unsigned int userInterfaceIdiom : 3; 
            unsigned int userInterfaceStyle : 1; 
        } ; 
    }  _fields;
    NSString * _localization;
    struct CGColor { } * _tintColor;
}

@property (nonatomic, readonly) unsigned long long accessibilityButtonShapes;
@property (nonatomic, readonly) unsigned long long accessibilityContrast;
@property (nonatomic, readonly) NSArray *assetAppearanceNames;
@property (nonatomic, readonly) long long assetDeviceIdiom;
@property (nonatomic, readonly) long long assetLayoutDirection;
@property (nonatomic, readonly) double assetScaleFactor;
@property (nonatomic, readonly) unsigned long long displayRange;
@property (nonatomic, readonly) unsigned char displayScale;
@property (nonatomic, readonly) const struct __CFString { }*fontContentSizeCategory;
@property (nonatomic, readonly) long long fontLegibilityWeight;
@property (nonatomic, readonly) double graphicsDisabledAlpha;
@property (nonatomic, readonly) struct CGColor { }*graphicsForegroundColor;
@property (nonatomic, readonly) bool hasAccessibilityContentSizeCategory;
@property (nonatomic, readonly) unsigned long long layoutDirection;
@property (nonatomic, readonly) unsigned long long legibilityWeight;
@property (nonatomic, readonly) NSString *localization;
@property (nonatomic, readonly) unsigned long long preferredContentSizeCategory;
@property (nonatomic, readonly) struct CGColor { }*tintColor;
@property (nonatomic, readonly) unsigned long long userInterfaceIdiom;
@property (nonatomic, readonly) unsigned long long userInterfaceStyle;

+ (bool)_colorInGamut:(struct CGColor { }*)arg1;
+ (id)slotStyleWithAccessibilityButtonShapes:(unsigned long long)arg1 accessibilityContrast:(unsigned long long)arg2 displayRange:(unsigned long long)arg3 displayScale:(unsigned char)arg4 layoutDirection:(unsigned long long)arg5 legibilityWeight:(unsigned long long)arg6 localization:(id)arg7 preferredContentSizeCategory:(unsigned long long)arg8 tintColor:(struct CGColor { }*)arg9 userInterfaceIdiom:(unsigned long long)arg10 userInterfaceStyle:(unsigned long long)arg11;
+ (id)slotStyleWithAccessibilityContrast:(unsigned long long)arg1 displayRange:(unsigned long long)arg2 displayScale:(unsigned char)arg3 layoutDirection:(unsigned long long)arg4 legibilityWeight:(unsigned long long)arg5 localization:(id)arg6 preferredContentSizeCategory:(unsigned long long)arg7 tintColor:(struct CGColor { }*)arg8 userInterfaceIdiom:(unsigned long long)arg9 userInterfaceStyle:(unsigned long long)arg10;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (unsigned long long)accessibilityButtonShapes;
- (unsigned long long)accessibilityContrast;
- (id)assetAppearanceNames;
- (long long)assetDeviceIdiom;
- (long long)assetLayoutDirection;
- (double)assetScaleFactor;
- (id)copyWithChangeBlock:(id /* block */)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (unsigned long long)displayRange;
- (unsigned char)displayScale;
- (void)encodeWithCoder:(id)arg1;
- (const struct __CFString { }*)fontContentSizeCategory;
- (long long)fontLegibilityWeight;
- (unsigned long long)gradeWithOnlyFails:(unsigned long long)arg1 allowedLocalizations:(id)arg2;
- (double)graphicsDisabledAlpha;
- (struct CGColor { }*)graphicsForegroundColor;
- (bool)hasAccessibilityContentSizeCategory;
- (unsigned long long)hash;
- (id)initWithAccessibilityButtonShapes:(unsigned long long)arg1 accessibilityContrast:(unsigned long long)arg2 displayRange:(unsigned long long)arg3 displayScale:(unsigned char)arg4 layoutDirection:(unsigned long long)arg5 legibilityWeight:(unsigned long long)arg6 localization:(id)arg7 preferredContentSizeCategory:(unsigned long long)arg8 tintColor:(struct CGColor { }*)arg9 userInterfaceIdiom:(unsigned long long)arg10 userInterfaceStyle:(unsigned long long)arg11;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(id)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned long long)layoutDirection;
- (unsigned long long)legibilityWeight;
- (id)localization;
- (unsigned long long)preferredContentSizeCategory;
- (struct CGColor { }*)tintColor;
- (unsigned long long)userInterfaceIdiom;
- (unsigned long long)userInterfaceStyle;

@end
