/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DMCUtilities.framework/DMCUtilities
 */

@interface DMCFeatureFlags : NSObject

+ (bool)hasT2;
+ (bool)isAppleInternal;
+ (bool)isBYOD3rdPartyEnabled;
+ (bool)isBYODAppleEnabled;
+ (bool)isBYODEnabled;
+ (bool)isBYODRestoreFromBackupEnabled;
+ (bool)isBYODSpyglassEnabled;
+ (bool)isClassCIdentitiesEnabled;
+ (bool)isDeviceManagementAndVPNUIEnabled;
+ (bool)isHRNEnabled;
+ (bool)isManagedRestoreEnabled;
+ (bool)isORGODeviceSubscriptionEnabled;
+ (bool)isORGOEnabled;
+ (bool)isORGOUserSubscriptionEnabled;
+ (bool)isRMDMEnabled;
+ (bool)isSecondaryAccountListUIEnabled;
+ (bool)isUAORGOEnabled;
+ (bool)isUserEnrollmentShowsManagedAccountEnabled;

@end
