/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DMCUtilities.framework/DMCUtilities
 */

@interface DMCFeatureOverrides : NSObject

+ (double)accountSignInTimeoutThresholdWithDefaultValue:(double)arg1;
+ (id)activationRecordFlagsWithFlags:(id)arg1;
+ (bool)allowAnyMAIDToSignIn;
+ (bool)boolForDefaultsKey:(id)arg1;
+ (id)depConfigurationEnrollmentURLStringWithURLString:(id)arg1;
+ (id)depDeviceSerialNumberWithValue:(id)arg1;
+ (id)depProvisionalEnrollmentURLStringWithURLString:(id)arg1;
+ (id)depRemoveEnrollmentURLStringWithURLString:(id)arg1;
+ (id)depResponseContentTypeFromContentType:(id)arg1;
+ (id)depResponseDataFromData:(id)arg1;
+ (id)enrollmentProfileWithDefaultValue:(id)arg1;
+ (double)enrollmentStepTimeoutThresholdWithDefaultValue:(double)arg1;
+ (bool)ignoreEnrollmentMode;
+ (id)modelNameWithDefaultValue:(id)arg1;
+ (id)numberForDefaultsKey:(id)arg1;
+ (id)productNameWithDefaultValue:(id)arg1;
+ (bool)sentinelExistsAtPath:(id)arg1;
+ (id)serviceDiscoveryDefaultPortWithValue:(id)arg1;
+ (id)serviceDiscoveryDomainWithValue:(id)arg1;
+ (id)serviceDiscoveryFallbackURLWithValue:(id)arg1;
+ (bool)shouldSimulateMDMCommunication;
+ (id)stringForDefaultsKey:(id)arg1;
+ (bool)useHTTPLogging;
+ (bool)useNonEphemeralWebAuthSession;

@end
