/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRAVDistantOutputDevice : MRAVOutputDevice <NSSecureCoding> {
    NSArray * _clusterComposition;
    NSDictionary * _modelSpecificInfo;
    _MRAVOutputDeviceDescriptorProtobuf * _protobuf;
    MRAVOutputDeviceSourceInfo * _sourceInfo;
}

@property (nonatomic, readonly) _MRAVOutputDeviceDescriptorProtobuf *protobuf;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)MACAddress;
- (id)airPlayGroupID;
- (id)availableBluetoothListeningModes;
- (float)batteryLevel;
- (id)bluetoothID;
- (bool)canAccessAppleMusic;
- (bool)canAccessRemoteAssets;
- (bool)canAccessiCloudMusicLibrary;
- (bool)canFetchMediaDataFromSender;
- (bool)canPlayEncryptedProgressiveDownloadAssets;
- (bool)canRelayCommunicationChannel;
- (id)clusterComposition;
- (unsigned int)clusterType;
- (unsigned long long)configuredClusterSize;
- (id)currentBluetoothListeningMode;
- (id)description;
- (id)descriptor;
- (unsigned int)deviceSubtype;
- (unsigned int)deviceType;
- (void)encodeWithCoder:(id)arg1;
- (id)firmwareVersion;
- (bool)groupContainsGroupLeader;
- (id)groupID;
- (bool)hasBatteryLevel;
- (long long)hostDeviceClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithDescriptor:(id)arg1;
- (id)initWithSkeleton:(id)arg1;
- (bool)isAddedToHomeKit;
- (bool)isAirPlayReceiverSessionActive;
- (bool)isDeviceGroupable;
- (bool)isGroupLeader;
- (bool)isGroupable;
- (bool)isLocalDevice;
- (bool)isProxyGroupPlayer;
- (bool)isRemoteControllable;
- (bool)isUsingJSONProtocol;
- (bool)isVolumeControlAvailable;
- (id)logicalDeviceID;
- (id)modelID;
- (id)modelSpecificInfo;
- (id)name;
- (bool)parentGroupContainsDiscoverableLeader;
- (id)parentGroupIdentifier;
- (bool)presentsOptimizedUserInterfaceWhenPlayingFetchedAudioOnlyAssets;
- (id)primaryID;
- (bool)producesLowFidelityAudio;
- (id)protobuf;
- (bool)requiresAuthorization;
- (id)sourceInfo;
- (bool)supportsBufferedAirPlay;
- (bool)supportsExternalScreen;
- (bool)supportsHAP;
- (bool)supportsMultiplayer;
- (bool)supportsRapportRemoteControlTransport;
- (bool)supportsSharePlayHandoff;
- (id)uid;
- (float)volume;
- (unsigned int)volumeCapabilities;

@end
