/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRSharedSettings : NSObject

@property (nonatomic, readonly) bool canHostMultiplayerStream;
@property (getter=isMultiplayerAware, nonatomic, readonly) bool multiplayerAware;
@property (getter=isMultiplayerHost, nonatomic, readonly) bool multiplayerHost;

+ (id)currentSettings;

- (bool)canHostMultiplayerStream;
- (bool)isMultiplayerAware;
- (bool)isMultiplayerHost;

@end
