/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface NSDictionary : NSObject <AFSecurityDigestibleChunksProviding, AMSHashable, AMSSecureCodingSanitizable, CARPFObject, CSCoderEncoder, CUByteCodable, INJSONSerializable, NSCopying, NSFastEnumeration, NSFetchRequestResult, NSMutableCopying, NSSecureCoding, PQLBindable>

@property (nonatomic, readonly, copy) NSArray *attributeDescriptions;
@property (readonly, copy) NSString *carpf_privateDescription;
@property (readonly, copy) NSString *carpf_shortDescription;
@property (nonatomic, readonly) NSError *cat_errorValue;
@property (readonly) unsigned long long count;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) unsigned short fileHFSFlags;
@property (nonatomic, readonly) unsigned long long fileHFSResourceForkSize;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *hashedDescription;
@property (nonatomic, readonly, copy) NSString *if_JSONStringRepresentation;
@property (nonatomic, readonly, copy) NSString *msv_compactDescription;
@property (readonly, copy) NSString *propertyDescription;
@property (readonly) Class superclass;

// Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)dictionary;
+ (id)dictionaryWithDictionary:(id)arg1;
+ (id)dictionaryWithDictionary:(id)arg1 copyItems:(bool)arg2;
+ (id)dictionaryWithObject:(id)arg1 forKey:(id)arg2;
+ (id)dictionaryWithObjects:(id)arg1 forKeys:(id)arg2;
+ (id)dictionaryWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
+ (id)dictionaryWithObjectsAndKeys:(id)arg1;
+ (id)newDictionaryWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
+ (id)sharedKeySetForKeys:(id)arg1;
+ (bool)supportsSecureCoding;

- (void)__apply:(int (*)arg1 context:(void*)arg2;
- (bool)__getValue:(id*)arg1 forKey:(id)arg2;
- (id)_cfMutableCopy;
- (unsigned long long)_cfTypeID;
- (id)allKeys;
- (id)allKeysForObject:(id)arg1;
- (id)allObjects;
- (id)allValues;
- (bool)containsKey:(id)arg1;
- (bool)containsObject:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)count;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long *x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;
- (unsigned long long)countForKey:(id)arg1;
- (unsigned long long)countForObject:(id)arg1;
- (id)description;
- (id)descriptionWithLocale:(id)arg1;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
- (void)encodeWithCoder:(id)arg1;
- (void)enumerateKeysAndObjectsUsingBlock:(id /* block */)arg1;
- (void)enumerateKeysAndObjectsWithOptions:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (void)getKeys:(id*)arg1;
- (void)getObjects:(id*)arg1;
- (void)getObjects:(id*)arg1 andKeys:(id*)arg2;
- (void)getObjects:(id*)arg1 andKeys:(id*)arg2 count:(unsigned long long)arg3;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1 copyItems:(bool)arg2;
- (id)initWithObject:(id)arg1 forKey:(id)arg2;
- (id)initWithObjects:(id)arg1 forKeys:(id)arg2;
- (id)initWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
- (id)initWithObjectsAndKeys:(id)arg1;
- (id)invertedDictionary;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToDictionary:(id)arg1;
- (bool)isNSDictionary__;
- (id)keyEnumerator;
- (id)keyOfEntryPassingTest:(id /* block */)arg1;
- (id)keyOfEntryWithOptions:(unsigned long long)arg1 passingTest:(id /* block */)arg2;
- (id)keysOfEntriesPassingTest:(id /* block */)arg1;
- (id)keysOfEntriesWithOptions:(unsigned long long)arg1 passingTest:(id /* block */)arg2;
- (id)keysSortedByValueUsingComparator:(id /* block */)arg1;
- (id)keysSortedByValueUsingSelector:(SEL)arg1;
- (id)keysSortedByValueWithOptions:(unsigned long long)arg1 usingComparator:(id /* block */)arg2;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)objectEnumerator;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectsForKeys:(id)arg1 notFoundMarker:(id)arg2;

// Image: /Developer/Library/PrivateFrameworks/DebugHierarchyFoundation.framework/DebugHierarchyFoundation

+ (id)dictionaryWithJSONData:(id)arg1 error:(id*)arg2;

- (id)generateJSONDataWithError:(id*)arg1;
- (id)generateJSONStringWithError:(id*)arg1;

// Image: /System/Library/CoreServices/RawCamera.bundle/RawCamera

- (id)keypathValueDictionary;
- (id)keypathValueDictionary:(id)arg1;
- (id)makeSerializable;

// Image: /System/Library/Frameworks/Accounts.framework/Accounts

- (id)ac_mapValues:(id /* block */)arg1;
- (id)ac_mapValuesNullable:(id /* block */)arg1;

// Image: /System/Library/Frameworks/CloudKit.framework/CloudKit

- (void)CKAssignToContainerWithID:(id)arg1;
- (id)CKCompactMap:(id /* block */)arg1;
- (id)CKCompactMapValues:(id /* block */)arg1;
- (id)CKDescriptionPropertiesWithPublic:(bool)arg1 private:(bool)arg2 shouldExpand:(bool)arg3;
- (id)CKFilter:(id /* block */)arg1;
- (id)CKFirstUrlForKeys:(id)arg1;
- (id)CKMap:(id /* block */)arg1;
- (id)CKMapKeysAndValues:(id /* block */)arg1;
- (id)CKMapValues:(id /* block */)arg1;
- (id)CKObjectForKeyCaseInsensitive:(id)arg1;
- (id)CKSingleLineDescription;

// Image: /System/Library/Frameworks/CoreServices.framework/CoreServices

- (bool)_LS_BoolForKey:(id)arg1;
- (unsigned long long)_LS_integerForKey:(id)arg1;
- (id)ls_fixupExtensionPointIdentifierKey;
- (unsigned long long)ls_hashQuery;
- (id)ls_insertExtensionPointVersion:(id)arg1;
- (id)ls_parseQueryForIdentifiers:(id)arg1;
- (id)ls_resolvePlugInKitInfoPlistWithDictionary:(id)arg1;

// Image: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight

- (void)encodeKeysAndValuesWithCSCoder:(id)arg1 filterBlock:(id /* block */)arg2;
- (void)encodeWithCSCoder:(id)arg1;

// Image: /System/Library/Frameworks/FileProvider.framework/FileProvider

- (id)fp_copyItemKeysAndValuesUnwrappedAndKeyMap:(id)arg1;
- (id)fp_copyItemKeysUnwrappedAndKeyMap:(id)arg1;
- (id)fp_filter:(id /* block */)arg1;
- (id)fp_removingObjectsNotKindOfClasses:(id)arg1;

// Image: /System/Library/Frameworks/Foundation.framework/Foundation

+ (bool)_subclassesMustBeExplicitlyMentionedWhenDecoded;
+ (id)dictionaryWithContentsOfFile:(id)arg1;
+ (id)dictionaryWithContentsOfURL:(id)arg1;
+ (id)dictionaryWithContentsOfURL:(id)arg1 error:(id*)arg2;
+ (id)newWithContentsOf:(id)arg1 immutable:(bool)arg2;
+ (id)newWithContentsOf:(id)arg1 immutable:(bool)arg2 error:(id*)arg3;
+ (bool)supportsSecureCoding;

- (id)_stringToWrite;
- (int)_web_intForKey:(id)arg1;
- (id)_web_numberForKey:(id)arg1;
- (id)_web_objectForMIMEType:(id)arg1;
- (id)_web_stringForKey:(id)arg1;
- (Class)classForCoder;
- (id)descriptionInStringsFileFormat;
- (void)encodeWithCoder:(id)arg1;
- (id)fileCreationDate;
- (bool)fileExtensionHidden;
- (id)fileGroupOwnerAccountID;
- (id)fileGroupOwnerAccountName;
- (unsigned long long)fileGroupOwnerAccountNumber;
- (unsigned int)fileHFSCreatorCode;
- (unsigned int)fileHFSTypeCode;
- (bool)fileIsAppendOnly;
- (bool)fileIsImmutable;
- (id)fileModificationDate;
- (id)fileOwnerAccountID;
- (id)fileOwnerAccountName;
- (unsigned long long)fileOwnerAccountNumber;
- (unsigned long long)filePosixPermissions;
- (unsigned long long)fileSize;
- (unsigned long long)fileSystemFileNumber;
- (long long)fileSystemNumber;
- (id)fileType;
- (id)initWithCoder:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 error:(id*)arg2;
- (id)replacementObjectForPortCoder:(id)arg1;
- (id)valueForKey:(id)arg1;
- (id)valueForKeyPath:(id)arg1;
- (bool)writeToFile:(id)arg1 atomically:(bool)arg2;
- (bool)writeToURL:(id)arg1 atomically:(bool)arg2;
- (bool)writeToURL:(id)arg1 error:(id*)arg2;

// Image: /System/Library/Frameworks/Intents.framework/Intents

+ (id)_intents_decodeWithJSONDecoder:(id)arg1 codableDescription:(id)arg2 from:(id)arg3;

- (id)_intents_encodeWithJSONEncoder:(id)arg1 codableDescription:(id)arg2;
- (id)_intents_indexingRepresentation;
- (id)descriptionAtIndent:(unsigned long long)arg1;

// Image: /System/Library/Frameworks/MapKit.framework/MapKit

- (bool)_mapkit_writeBinaryPlist:(id)arg1 atomically:(bool)arg2;

// Image: /System/Library/Frameworks/QuartzCore.framework/QuartzCore

- (id)CAMLType;
- (void*)CA_copyRenderKeyValueArray;
- (void)encodeWithCAMLWriter:(id)arg1;

// Image: /System/Library/Frameworks/SceneKit.framework/SceneKit

- (struct SCNMatrix4 { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; })SCNMatrix4Value;
- (id)SCNMutableDeepCopy;
- (struct SCNVector3 { float x1; float x2; float x3; })SCNVector3Value;
- (struct SCNVector4 { float x1; float x2; float x3; float x4; })SCNVector4Value;
- (unsigned long long)SCN_safeHash;

// Image: /System/Library/Frameworks/UserNotifications.framework/UserNotifications

- (id)un_nonEmptyCopy;
- (id)un_safeCastObjectForKey:(id)arg1 class:(Class)arg2;

// Image: /System/Library/PrivateFrameworks/AXCoreUtilities.framework/AXCoreUtilities

- (id)ax_deepMutableCopy;

// Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount

- (id)aa_dictionaryByAddingEntriesFromDictionary:(id)arg1;

// Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices

+ (id)ams_dictionaryWithEncryptionResult:(struct { id x1; id x2; id x3; })arg1;

- (id)ams_arrayUsingTransform:(id /* block */)arg1;
- (id)ams_componentsJoinedByString:(id)arg1;
- (id)ams_dictionaryByAddingEntriesFromDictionary:(id)arg1;
- (id)ams_dictionaryRemovingKeys:(id)arg1;
- (struct { id x1; id x2; id x3; })ams_encryptionResult;
- (id)ams_filterUsingTest:(id /* block */)arg1;
- (id)ams_firstKeyObjectPassingTest:(id /* block */)arg1;
- (id)ams_firstKeyPassingTest:(id /* block */)arg1;
- (id)ams_firstObjectPassingTest:(id /* block */)arg1;
- (id)ams_mapWithTransform:(id /* block */)arg1;
- (id)ams_objectForCaseInsensitiveKey:(id)arg1;
- (id)ams_objectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)ams_sanitizedForSecureCoding;
- (id)hashedDescription;

// Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices

- (id)_af_lenient:(bool)arg1 map:(id /* block */)arg2;
- (void)af_enumerateDigestibleChunksWithOptions:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (id)af_lenientMappedDictionary:(id /* block */)arg1;
- (id)af_mappedDictionary:(id /* block */)arg1;

// Image: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit

+ (id)ak_dictionaryWithResponseData:(id)arg1;
+ (id)ak_jsonDictionaryWithResponseData:(id)arg1;

- (id)_ak_truncatedTokensCopy;
- (id)ak_mapObjects:(id /* block */)arg1;
- (id)ak_mapObjectsNullable:(id /* block */)arg1;
- (id)ak_redactedCopy;
- (id)ak_toJSONString;
- (id)ak_urlQueryString;

// Image: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard

- (bool)bs_boolForKey:(id)arg1;
- (id)bs_dictionaryByAddingEntriesFromDictionary:(id)arg1;
- (void)bs_each:(id /* block */)arg1;
- (id)bs_filter:(id /* block */)arg1;
- (id)bs_safeArrayForKey:(id)arg1;
- (id)bs_safeDictionaryForKey:(id)arg1;
- (id)bs_safeNumberForKey:(id)arg1;
- (id)bs_safeObjectForKey:(id)arg1 ofType:(Class)arg2;
- (id)bs_safeStringForKey:(id)arg1;
- (id)bs_safeURLForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/CARPFoundation.framework/CARPFoundation

+ (id)carpf_shortDescription;

- (id)arrayForKey:(id)arg1;
- (id)base64EncodedDataForKey:(id)arg1;
- (bool)boolForKey:(id)arg1;
- (bool)boolForKey:(id)arg1 keyPresent:(bool*)arg2;
- (id)carpf_URLForKey:(id)arg1;
- (id)carpf_UUIDForKey:(id)arg1;
- (id)carpf_arrayForKey:(id)arg1;
- (id)carpf_base64EncodedDataForKey:(id)arg1;
- (bool)carpf_boolForKey:(id)arg1;
- (bool)carpf_boolForKey:(id)arg1 isPresent:(bool*)arg2;
- (id)carpf_calendarForKey:(id)arg1;
- (id)carpf_dataForKey:(id)arg1;
- (id)carpf_dateComponentsForKey:(id)arg1;
- (id)carpf_dateForKey:(id)arg1;
- (id)carpf_dictionaryForKey:(id)arg1;
- (id)carpf_errorForKey:(id)arg1;
- (id)carpf_mutableArrayForKey:(id)arg1;
- (id)carpf_mutableDictionaryForKey:(id)arg1;
- (id)carpf_mutableSetForKey:(id)arg1;
- (id)carpf_nullForKey:(id)arg1;
- (id)carpf_numberForKey:(id)arg1;
- (id)carpf_privateDescription;
- (id)carpf_setForKey:(id)arg1;
- (id)carpf_shortDescription;
- (id)carpf_stringForKey:(id)arg1;
- (id)carpf_timeZoneForKey:(id)arg1;
- (id)carpf_unarchivedObjectForKey:(id)arg1 ofClasses:(id)arg2;
- (id)carpf_valueForKey:(id)arg1;
- (id)dataForKey:(id)arg1;
- (id)dateForKey:(id)arg1;
- (id)dictionaryForKey:(id)arg1;
- (id)errorForKey:(id)arg1;
- (id)errorFromDataForKey:(id)arg1;
- (id)mutableArrayForKey:(id)arg1;
- (id)mutableDictionaryForKey:(id)arg1;
- (id)mutableSetForKey:(id)arg1;
- (id)nsValueForKey:(id)arg1;
- (id)nullForKey:(id)arg1;
- (id)numberForKey:(id)arg1;
- (id)predicateFromDataForKey:(id)arg1;
- (id)secureDescriptionWithBlacklistKeys:(id)arg1;
- (id)secureDescriptionWithIndent:(id)arg1 newLine:(bool)arg2 blacklistedKeys:(id)arg3;
- (id)setForKey:(id)arg1;
- (id)stringForKey:(id)arg1;
- (id)timeZoneForKey:(id)arg1;
- (id)urlForKey:(id)arg1;
- (id)uuidForKey:(id)arg1;
- (id)uuidFromStringForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture

- (bool)bw_containsBuiltInMicAsAnInput;
- (id)bw_dataSourceDictionaryForDesiredMicOrientation:(unsigned int)arg1;
- (unsigned int)bw_optimalMicPolarPattern;

// Image: /System/Library/PrivateFrameworks/CMImaging.framework/CMImaging

- (bool)boolValueForKey:(id)arg1 defaultValue:(bool)arg2 found:(bool*)arg3;
- (bool)boolValueFromArrayWithKey:(id)arg1 forIndex:(unsigned long long)arg2 defaultValue:(bool)arg3 found:(bool*)arg4;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })cgRectForKey:(id)arg1 defaultValue:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 found:(bool*)arg3;
- (float)floatValueForKey:(id)arg1 defaultValue:(float)arg2 found:(bool*)arg3;
- (float)floatValueFromArrayWithKey:(id)arg1 forIndex:(unsigned long long)arg2 defaultValue:(float)arg3 found:(bool*)arg4;
- (int)intValueForKey:(id)arg1 defaultValue:(int)arg2 found:(bool*)arg3;
- (int)intValueFromArrayWithKey:(id)arg1 forIndex:(unsigned long long)arg2 defaultValue:(int)arg3 found:(bool*)arg4;
- (void)simdInt2ValueForKey:(void *)arg1 defaultValue:(void *)arg2 found:(void *)arg3; // needs 3 arg types, found 2: id, bool*
- (void)simdInt2ValueForXKey:(void *)arg1 yKey:(void *)arg2 defaultValue:(void *)arg3 found:(void *)arg4; // needs 4 arg types, found 3: id, id, bool*
- (void)simdInt2ValueFromArraysWithXKey:(void *)arg1 yKey:(void *)arg2 forIndex:(void *)arg3 defaultValue:(void *)arg4 found:(void *)arg5; // needs 5 arg types, found 4: id, id, unsigned long long, bool*
- (void)simdInt4ValueForKey:(void *)arg1 defaultValue:(void *)arg2 found:(void *)arg3; // needs 3 arg types, found 2: id, bool*
- (void)simdUInt2ValueForKey:(void *)arg1 defaultValue:(void *)arg2 found:(void *)arg3; // needs 3 arg types, found 2: id, bool*
- (void)simdUInt2ValueForXKey:(void *)arg1 yKey:(void *)arg2 defaultValue:(void *)arg3 found:(void *)arg4; // needs 4 arg types, found 3: id, id, bool*
- (void)simdUInt2ValueFromArraysWithXKey:(void *)arg1 yKey:(void *)arg2 forIndex:(void *)arg3 defaultValue:(void *)arg4 found:(void *)arg5; // needs 5 arg types, found 4: id, id, unsigned long long, bool*
- (unsigned int)unsignedIntValueForKey:(id)arg1 defaultValue:(unsigned int)arg2 found:(bool*)arg3;
- (unsigned int)unsignedIntValueFromArrayWithKey:(id)arg1 forIndex:(unsigned long long)arg2 defaultValue:(unsigned int)arg3 found:(bool*)arg4;

// Image: /System/Library/PrivateFrameworks/Catalyst.framework/Catalyst

- (id)cat_calculateAddedObjects;
- (id)cat_calculateRemovedObjects;
- (id)cat_errorValue;
- (id)cat_uuidForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial

- (bool)matchesUID:(id)arg1;

// Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation

- (id)_cn_diff:(id)arg1;
- (void)_cn_each:(id /* block */)arg1;
- (id)_cn_filter:(id /* block */)arg1;
- (id)_cn_keysAndValues;
- (id)_cn_map:(id /* block */)arg1;
- (id)_cn_mapKeys:(id /* block */)arg1;
- (id)_cn_mapValues:(id /* block */)arg1;
- (id)_cn_objectForKey:(id)arg1 ofClass:(Class)arg2;

// Image: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness

- (unsigned long long)getKeyCategory;
- (id)getKeyCategoryRef;
- (unsigned long long)getKeyDisplayID;
- (id)getKeyDisplayIDRef;
- (unsigned long long)getKeyKeyboardID;
- (id)getKeyKeyboardIDRef;
- (id)getKeyPropertyParameter;
- (id)getKeyString;
- (id)initWithPropertyKey:(id)arg1;
- (id)initWithPropertyKey:(id)arg1 andCategory:(unsigned long long)arg2;
- (id)initWithPropertyKey:(id)arg1 andDisplay:(unsigned long long)arg2;
- (id)initWithPropertyKey:(id)arg1 display:(unsigned long long)arg2 andParameter:(id)arg3;
- (id)initWithPropertyKey:(id)arg1 keyboardID:(unsigned long long)arg2;

// Image: /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils

+ (id)createWithBytesNoCopy:(void*)arg1 length:(unsigned long long)arg2 error:(id*)arg3;

- (const char *)encodedBytesAndReturnLength:(unsigned long long*)arg1 error:(id*)arg2;
- (id)encodedDataAndReturnError:(id*)arg1;

// Image: /System/Library/PrivateFrameworks/DMCUtilities.framework/DMCUtilities

+ (id)DMCDictionaryFromFile:(id)arg1;
+ (id)DMCShortenedArray:(id)arg1;
+ (id)DMCShortenedData:(id)arg1;
+ (id)DMCShortenedDictionary:(id)arg1;
+ (id)DMCShortenedObject:(id)arg1;

- (id)DMCShortenedPlistDescription;
- (bool)DMCWriteToBinaryFile:(id)arg1;

// Image: /System/Library/PrivateFrameworks/DataMigration.framework/DataMigration

+ (id)dmlmr_buildVersionKey;
+ (id)dmlmr_lastMigrationResultsWithSuccess:(bool)arg1 buildVersion:(id)arg2;
+ (id)dmlmr_successKey;

- (id)dmlmr_buildVersion;
- (id)dmlmr_success;

// Image: /System/Library/PrivateFrameworks/ExtensionFoundation.framework/ExtensionFoundation

- (id)_EX_arrayForKey:(id)arg1;
- (bool)_EX_boolForKey:(id)arg1;
- (bool)_EX_boolForKey:(id)arg1 defaultValue:(bool)arg2;
- (id)_EX_dictionaryByRemovingObjectForKey:(id)arg1;
- (id)_EX_dictionaryBySettingObject:(id)arg1 forKey:(id)arg2;
- (id)_EX_dictionaryBySettingValuesForKeysWithDictionary:(id)arg1;
- (id)_EX_dictionaryForKey:(id)arg1;
- (id)_EX_objectForKey:(id)arg1 ofClass:(Class)arg2;
- (id)_EX_requiredHostEntitlementsForExtensionPointIdentifier:(id)arg1;
- (id)_EX_stringForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/FTServices.framework/FTServices

- (id)_FTFilteredDictionaryForAPS;

// Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices

+ (id)_geo_dictionaryFromXPCObject:(id)arg1;
+ (id)_geo_replyDictionaryForError:(id)arg1 key:(id)arg2;

- (id)_geo_errorForKey:(id)arg1;
- (id)_geo_newXPCObject;
- (id)_placeOrCurrentLocation:(bool*)arg1;

// Image: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation

+ (id)dictionaryWithKeyArray:(id)arg1 defaultValue:(id)arg2;
+ (id)dictionaryWithPlistData:(id)arg1;

- (id)__imDeepCopy;
- (id)__imDictionaryByFilteringWithBlock:(id /* block */)arg1;
- (bool)__imIsMutable;
- (id)_arrayForKey:(id)arg1;
- (id)_dataForKey:(id)arg1;
- (id)_dictionaryForKey:(id)arg1;
- (id)_numberForKey:(id)arg1;
- (id)_stringForKey:(id)arg1;
- (id)dictionaryFromChanges:(id)arg1;
- (unsigned short)fileHFSFlags;
- (unsigned long long)fileHFSResourceForkSize;
- (id)keysOfChangedEntriesComparedTo:(id)arg1;
- (id)plistData;

// Image: /System/Library/PrivateFrameworks/IconFoundation.framework/IconFoundation

- (id)_IF_arrayForKey:(id)arg1;
- (id)_IF_arrayForKeys:(id)arg1;
- (bool)_IF_boolForKey:(id)arg1;
- (bool)_IF_boolForKey:(id)arg1 defaultValue:(bool)arg2;
- (bool)_IF_boolForKeys:(id)arg1;
- (bool)_IF_boolForKeys:(id)arg1 defaultValue:(bool)arg2;
- (id)_IF_dataForKey:(id)arg1;
- (id)_IF_dictionaryAddingEntriesFromDictionary:(id)arg1;
- (id)_IF_dictionaryForKey:(id)arg1;
- (id)_IF_dictionaryForKeys:(id)arg1;
- (id)_IF_numberForKey:(id)arg1;
- (id)_IF_numberForKeys:(id)arg1;
- (id)_IF_objectOfClass:(Class)arg1 forKey:(id)arg2;
- (id)_IF_objectOfClass:(Class)arg1 forKeys:(id)arg2;
- (id)_IF_stringForKey:(id)arg1;
- (id)_IF_stringForKeys:(id)arg1;

// Image: /System/Library/PrivateFrameworks/IconServices.framework/IconServices

- (id)_IS_resourceNamed:(id)arg1;

// Image: /System/Library/PrivateFrameworks/IntentsFoundation.framework/IntentsFoundation

+ (id)if_dictionaryWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3 uniquingKeysWith:(id /* block */)arg4;
+ (id)if_dictionaryWithObjects:(id)arg1 forKeys:(id)arg2 uniquingKeysWith:(id /* block */)arg3;

- (id)if_JSONStringRepresentation;
- (id)if_compactMap:(id /* block */)arg1;
- (id)if_dictionaryByAddingEntriesFromDictionary:(id)arg1;
- (id)if_dictionaryWithNonEmptyValues;

// Image: /System/Library/PrivateFrameworks/IntlPreferences.framework/IntlPreferences

- (id)invertedDictionary;

// Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration

+ (id)MCDictionaryFromFile:(id)arg1;
+ (id)MCShortenedArray:(id)arg1;
+ (id)MCShortenedData:(id)arg1;
+ (id)MCShortenedDictionary:(id)arg1;
+ (id)MCShortenedObject:(id)arg1;

- (id)MCDeepCopy;
- (id)MCDeepCopyWithZone:(struct _NSZone { }*)arg1;
- (id)MCDictionaryAdditiveDeltaToCreateDictionary:(id)arg1;
- (id)MCDictionarySubtractiveDeltaToCreateDictionary:(id)arg1;
- (id)MCDictionaryWithLeafValuesSetToValue:(id)arg1;
- (id)MCInsertedKeysFromDictionary:(id)arg1 withNewLeafValue:(id)arg2;
- (id)MCMutableDeepCopy;
- (id)MCMutableDeepCopyWithZone:(struct _NSZone { }*)arg1;
- (id)MCRemovedKeysFromDictionary:(id)arg1;
- (id)MCRetainOptionalNonZeroLengthStringKey:(id)arg1 errorDomain:(id)arg2 invalidDataCode:(long long)arg3 invalidDataErrorString:(id)arg4 outError:(id*)arg5;
- (id)MCRetainOptionalObjectKey:(id)arg1 type:(Class)arg2 errorDomain:(id)arg3 invalidDataCode:(long long)arg4 invalidDataErrorString:(id)arg5 outError:(id*)arg6;
- (id)MCRetainRequiredNonZeroLengthStringKey:(id)arg1 errorDomain:(id)arg2 missingDataCode:(long long)arg3 missingDataErrorString:(id)arg4 invalidDataCode:(long long)arg5 invalidDataErrorString:(id)arg6 outError:(id*)arg7;
- (id)MCRetainRequiredObjectKey:(id)arg1 type:(Class)arg2 errorDomain:(id)arg3 missingDataCode:(long long)arg4 missingDataErrorString:(id)arg5 invalidDataCode:(long long)arg6 invalidDataErrorString:(id)arg7 outError:(id*)arg8;
- (id)MCShortenedPlistDescription;
- (bool)MCWriteToBinaryFile:(id)arg1;
- (bool)MCWriteToBinaryFile:(id)arg1 atomically:(bool)arg2;

// Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote

- (bool)MR_isEqualToNowPlayingInfo:(id)arg1;

// Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices

+ (id)msv_dictionaryWithContentsOfBase64EncodedJSONString:(id)arg1 error:(id*)arg2;
+ (id)msv_dictionaryWithContentsOfJSON:(id)arg1 error:(id*)arg2;

- (id)msv_compactDescription;
- (id)msv_compactMap:(id /* block */)arg1;
- (id)msv_compactMapValues:(id /* block */)arg1;
- (void)msv_enumerateKeysAndObjectsOrderedByKeyComparator:(id /* block */)arg1 usingBlock:(id /* block */)arg2;
- (void)msv_enumerateKeysAndObjectsOrderedByKeyDescriptors:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)msv_enumerateKeysAndObjectsOrderedByKeySelector:(SEL)arg1 usingBlock:(id /* block */)arg2;
- (id)msv_filter:(id /* block */)arg1;
- (id)msv_firstWhere:(id /* block */)arg1;
- (id)msv_flatMap:(id /* block */)arg1;
- (id)msv_map:(id /* block */)arg1;
- (id)msv_mapValues:(id /* block */)arg1;
- (bool)msv_reduceIntoBool:(bool)arg1 by:(id /* block */)arg2;
- (double)msv_reduceIntoCGFloat:(double)arg1 by:(id /* block */)arg2;
- (double)msv_reduceIntoDouble:(double)arg1 by:(id /* block */)arg2;
- (float)msv_reduceIntoFloat:(float)arg1 by:(id /* block */)arg2;
- (int)msv_reduceIntoInt32:(int)arg1 by:(id /* block */)arg2;
- (long long)msv_reduceIntoInt64:(long long)arg1 by:(id /* block */)arg2;
- (long long)msv_reduceIntoInt:(long long)arg1 by:(id /* block */)arg2;
- (id)msv_reduceIntoObject:(id)arg1 by:(id /* block */)arg2;
- (unsigned int)msv_reduceIntoUInt32:(unsigned int)arg1 by:(id /* block */)arg2;
- (unsigned long long)msv_reduceIntoUInt64:(unsigned long long)arg1 by:(id /* block */)arg2;
- (unsigned long long)msv_reduceIntoUInt:(unsigned long long)arg1 by:(id /* block */)arg2;

// Image: /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation

+ (id)MI_dictionaryWithContentsOfURL:(id)arg1 options:(unsigned long long)arg2 error:(id*)arg3;

- (bool)MI_writeAtomicallyToURLMatchingCurrentFileMetadata:(id)arg1 format:(unsigned long long)arg2 error:(id*)arg3;
- (bool)MI_writeToURL:(id)arg1 format:(unsigned long long)arg2 options:(unsigned long long)arg3 error:(id*)arg4;

// Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation

+ (id)_serverStringDictionaryForDistance:(double)arg1 validDistance:(double)arg2 destination:(id)arg3 spoken:(bool)arg4;
+ (id)_serverStringDictionaryForMapItem:(id)arg1;

// Image: /System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit

- (id)dictionaryChanging:(id)arg1 to:(id)arg2;

// Image: /System/Library/PrivateFrameworks/ProactiveEventTracker.framework/ProactiveEventTracker

- (id)pet_arrayForKey:(id)arg1;
- (id)pet_dictForKey:(id)arg1;
- (id)pet_numForKey:(id)arg1;
- (id)pet_objectForKey:(id)arg1 class:(Class)arg2;
- (id)pet_strForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices

- (id)entriesToStringWithIndent:(int)arg1 debug:(bool)arg2;

// Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects

- (id)_sa_mappedDictionaryWithBlock:(id /* block */)arg1;

// Image: /System/Library/PrivateFrameworks/SetupAssistant.framework/SetupAssistant

- (id)bySeedProgramManager_valueForAssetAudienceKey;
- (id)bySeedProgramManager_valueForProgramKey;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

- (bool)_boolForKey:(id)arg1;
- (id)_ui_attributesForDictionaryContainingUIStringDrawingKeys;
- (bool)_ui_dictionaryContainsUIStringDrawingKeys;
- (int)_web_messageLineNumber;
- (id)_web_messageSourceURL;
- (id)_web_messageText;
- (int)_web_messageType;

// Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy

- (id)_webkit_arrayForKey:(id)arg1;
- (bool)_webkit_boolForKey:(id)arg1;
- (id)_webkit_numberForKey:(id)arg1;
- (id)_webkit_objectForMIMEType:(id)arg1;
- (id)_webkit_stringForKey:(id)arg1;

// Image: /usr/lib/libprequelite.dylib

- (void)sqliteBind:(struct sqlite3_stmt { }*)arg1 index:(int)arg2;

// Image: /usr/lib/swift/libswiftFoundation.dylib

- (id)__swiftInitWithDictionary_NSDictionary:(id)arg1;
- (id)__swift_objectForKeyedSubscript:(id)arg1;

@end
