/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContextKitExtraction.framework/ContextKitExtraction
 */

@interface CKContextUserActivity : NSObject <NSSecureCoding> {
    NSString * _bundleIdentifier;
    bool  _generatedActivity;
    NSNumber * _numberOfOccurrences;
    double  _recordedTimeIntervalSince1970;
    NSUserActivity * _userActivity;
    NSData * _userActivityData;
    NSUUID * _uuid;
}

@property (nonatomic, copy) NSString *bundleIdentifier;
@property (nonatomic) NSDate *entryDate;
@property (getter=isGeneratedActivity, nonatomic) bool generatedActivity;
@property (nonatomic, copy) NSNumber *numberOfOccurrences;
@property (nonatomic, readonly) NSUserActivity *userActivity;
@property (nonatomic, readonly) NSUUID *uuid;

+ (id)_establishServiceConnection;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)bundleIdentifier;
- (id)description;
- (void)donate;
- (void)encodeWithCoder:(id)arg1;
- (id)entryDate;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithUserActivity:(id)arg1;
- (bool)isGeneratedActivity;
- (id)numberOfOccurrences;
- (void)prepareForDonationWithCompletionHandler:(id /* block */)arg1;
- (void)setBundleIdentifier:(id)arg1;
- (void)setEntryDate:(id)arg1;
- (void)setGeneratedActivity:(bool)arg1;
- (void)setNumberOfOccurrences:(id)arg1;
- (id)userActivity;
- (id)uuid;

@end
