/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContextKitExtraction.framework/ContextKitExtraction
 */

@interface CKContextContentProvider : NSObject

- (void)extractUsingExecutor:(id)arg1;
- (void)extractUsingExecutor:(id)arg1 withOptions:(unsigned long long)arg2;
- (double)timeout;

@end
