/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSArchivedSurveyStep : CLSObject {
    long long  _type;
    long long  _version;
}

@property (nonatomic, readonly) long long type;
@property (nonatomic, readonly) long long version;

+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setType:(long long)arg1;
- (void)setVersion:(long long)arg1;
- (long long)type;
- (long long)version;

@end
