/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices
 */

@interface RBSAppNapPreventSuppressedCPUGrant : RBSGrant

+ (id)grant;

@end
