/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices
 */

@interface RBSCPUAccessGrant : RBSGrant {
    unsigned char  _role;
}

@property (nonatomic, readonly) unsigned char role;

+ (id)grant;
+ (id)grantUserInitiated;
+ (id)grantWithRole:(unsigned char)arg1;
+ (id)grantWithUserInteractivity;
+ (id)grantWithUserInteractivityAndFocus;

- (id)description;
- (void)encodeWithRBSXPCCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithRBSXPCCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned char)role;

@end
