/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices
 */

@interface RBSJetsamPriorityGrant : RBSGrant {
    unsigned long long  _band;
}

@property (nonatomic, readonly) unsigned long long band;

+ (id)grantWithBackgroundPriority;
+ (id)grantWithBand:(unsigned long long)arg1;
+ (id)grantWithForegroundPriority;
+ (bool)supportsRBSXPCSecureCoding;

- (unsigned long long)band;
- (id)description;
- (void)encodeWithRBSXPCCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithRBSXPCCoder:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
