/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices
 */

@interface RBSTagAttribute : RBSAttribute {
    NSString * _tag;
}

@property (nonatomic, readonly, copy) NSString *tag;

+ (id)attributeWithTag:(id)arg1;

- (void).cxx_destruct;
- (id)description;
- (void)encodeWithRBSXPCCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithRBSXPCCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)tag;

@end
