/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNDataMapperConfiguration : NSObject {
    NSObject<OS_tcc_identity> * _assumedIdentity;
    CNContactsEnvironment * _environment;
    CNManagedConfiguration * _managedConfiguration;
}

@property (nonatomic, retain) NSObject<OS_tcc_identity> *assumedIdentity;
@property (nonatomic, retain) CNContactsEnvironment *environment;
@property (nonatomic, retain) CNManagedConfiguration *managedConfiguration;

- (void).cxx_destruct;
- (id)assumedIdentity;
- (id)description;
- (id)environment;
- (id)initWithContactStoreConfiguration:(id)arg1;
- (id)managedConfiguration;
- (void)setAssumedIdentity:(id)arg1;
- (void)setEnvironment:(id)arg1;
- (void)setManagedConfiguration:(id)arg1;

@end
