/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtCE10FoundationCSo20NSNotificationCenter13Notifications : _TtCs12_SwiftObject {
    void buffer;
    void center;
    void lock;
    void observer;
    void pending;
}

@end
