/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface ANCSchemaANCServerEvent : SISchemaTopLevelUnionType {
    ANCSchemaANCServerEventMetadata * _eventMetadata;
    bool  _hasEventMetadata;
    bool  _hasUserResponseEvaluated;
    ANCSchemaANCServerUserResponseEvaluated * _userResponseEvaluated;
    unsigned long long  _whichEvent_Type;
}

@property (nonatomic, retain) ANCSchemaANCServerEventMetadata *eventMetadata;
@property (nonatomic) bool hasEventMetadata;
@property (nonatomic) bool hasUserResponseEvaluated;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) ANCSchemaANCServerUserResponseEvaluated *userResponseEvaluated;
@property (nonatomic, readonly) unsigned long long whichEvent_Type;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)eventMetadata;
- (int)getAnyEventType;
- (bool)hasEventMetadata;
- (bool)hasUserResponseEvaluated;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)qualifiedMessageName;
- (bool)readFrom:(id)arg1;
- (void)setEventMetadata:(id)arg1;
- (void)setHasEventMetadata:(bool)arg1;
- (void)setHasUserResponseEvaluated:(bool)arg1;
- (void)setUserResponseEvaluated:(id)arg1;
- (id)userResponseEvaluated;
- (unsigned long long)whichEvent_Type;
- (void)writeTo:(id)arg1;

@end
