/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface ASRSchemaASRFinalResultGenerated : SISchemaInstrumentationMessage {
    NSArray * _correctPartialResultIndexLists;
    NSArray * _tokenSilenceStartTimeInNsLists;
}

@property (nonatomic, copy) NSArray *correctPartialResultIndexLists;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, copy) NSArray *tokenSilenceStartTimeInNsLists;

- (void).cxx_destruct;
- (void)addCorrectPartialResultIndexList:(int)arg1;
- (void)addTokenSilenceStartTimeInNsList:(unsigned long long)arg1;
- (void)clearCorrectPartialResultIndexList;
- (void)clearTokenSilenceStartTimeInNsList;
- (int)correctPartialResultIndexListAtIndex:(unsigned long long)arg1;
- (unsigned long long)correctPartialResultIndexListCount;
- (id)correctPartialResultIndexLists;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setCorrectPartialResultIndexLists:(id)arg1;
- (void)setTokenSilenceStartTimeInNsLists:(id)arg1;
- (unsigned long long)tokenSilenceStartTimeInNsListAtIndex:(unsigned long long)arg1;
- (unsigned long long)tokenSilenceStartTimeInNsListCount;
- (id)tokenSilenceStartTimeInNsLists;
- (void)writeTo:(id)arg1;

@end
