/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface DODMLASRSchemaDODMLASRPersonalizationExperimentEnded : SISchemaInstrumentationMessage {
    NSArray * _audioFileResults;
    NSString * _datapackVersion;
    int  _experimentStatusCode;
    struct { 
        unsigned int numAudioFilesAvailable : 1; 
        unsigned int numAudioFilesSelected : 1; 
        unsigned int experimentStatusCode : 1; 
    }  _has;
    bool  _hasDatapackVersion;
    bool  _hasPersonalizedLanguageModelMetrics;
    unsigned int  _numAudioFilesAvailable;
    unsigned int  _numAudioFilesSelected;
    DODMLASRSchemaDODMLASRPersonalizedLanguageModelMetrics * _personalizedLanguageModelMetrics;
}

@property (nonatomic, copy) NSArray *audioFileResults;
@property (nonatomic, copy) NSString *datapackVersion;
@property (nonatomic) int experimentStatusCode;
@property (nonatomic) bool hasDatapackVersion;
@property (nonatomic) bool hasExperimentStatusCode;
@property (nonatomic) bool hasNumAudioFilesAvailable;
@property (nonatomic) bool hasNumAudioFilesSelected;
@property (nonatomic) bool hasPersonalizedLanguageModelMetrics;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) unsigned int numAudioFilesAvailable;
@property (nonatomic) unsigned int numAudioFilesSelected;
@property (nonatomic, retain) DODMLASRSchemaDODMLASRPersonalizedLanguageModelMetrics *personalizedLanguageModelMetrics;

- (void).cxx_destruct;
- (void)addAudioFileResults:(id)arg1;
- (id)audioFileResults;
- (id)audioFileResultsAtIndex:(unsigned long long)arg1;
- (unsigned long long)audioFileResultsCount;
- (void)clearAudioFileResults;
- (id)datapackVersion;
- (id)dictionaryRepresentation;
- (int)experimentStatusCode;
- (bool)hasDatapackVersion;
- (bool)hasExperimentStatusCode;
- (bool)hasNumAudioFilesAvailable;
- (bool)hasNumAudioFilesSelected;
- (bool)hasPersonalizedLanguageModelMetrics;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (unsigned int)numAudioFilesAvailable;
- (unsigned int)numAudioFilesSelected;
- (id)personalizedLanguageModelMetrics;
- (bool)readFrom:(id)arg1;
- (void)setAudioFileResults:(id)arg1;
- (void)setDatapackVersion:(id)arg1;
- (void)setExperimentStatusCode:(int)arg1;
- (void)setHasDatapackVersion:(bool)arg1;
- (void)setHasExperimentStatusCode:(bool)arg1;
- (void)setHasNumAudioFilesAvailable:(bool)arg1;
- (void)setHasNumAudioFilesSelected:(bool)arg1;
- (void)setHasPersonalizedLanguageModelMetrics:(bool)arg1;
- (void)setNumAudioFilesAvailable:(unsigned int)arg1;
- (void)setNumAudioFilesSelected:(unsigned int)arg1;
- (void)setPersonalizedLanguageModelMetrics:(id)arg1;
- (void)writeTo:(id)arg1;

@end
