/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface FLOWSchemaFLOWMediaPlayerContext : SISchemaInstrumentationMessage {
    NSArray * _activeSubscriptions;
    int  _appleMusicVoicePreviewOfferNotShown;
    int  _appleMusicVoiceUserSubscriptionState;
    struct { 
        unsigned int taskType : 1; 
        unsigned int mediaType : 1; 
        unsigned int isWholeHouseAudio : 1; 
        unsigned int isMusicSubscriber : 1; 
        unsigned int appleMusicVoiceUserSubscriptionState : 1; 
        unsigned int appleMusicVoicePreviewOfferNotShown : 1; 
    }  _has;
    bool  _hasWholeHouseAudioDestinationContext;
    bool  _isMusicSubscriber;
    bool  _isWholeHouseAudio;
    int  _mediaType;
    int  _taskType;
    FLOWSchemaFLOWholeHouseAudioDestinationContext * _wholeHouseAudioDestinationContext;
}

@property (nonatomic, copy) NSArray *activeSubscriptions;
@property (nonatomic) int appleMusicVoicePreviewOfferNotShown;
@property (nonatomic) int appleMusicVoiceUserSubscriptionState;
@property (nonatomic) bool hasAppleMusicVoicePreviewOfferNotShown;
@property (nonatomic) bool hasAppleMusicVoiceUserSubscriptionState;
@property (nonatomic) bool hasIsMusicSubscriber;
@property (nonatomic) bool hasIsWholeHouseAudio;
@property (nonatomic) bool hasMediaType;
@property (nonatomic) bool hasTaskType;
@property (nonatomic) bool hasWholeHouseAudioDestinationContext;
@property (nonatomic) bool isMusicSubscriber;
@property (nonatomic) bool isWholeHouseAudio;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) int mediaType;
@property (nonatomic) int taskType;
@property (nonatomic, retain) FLOWSchemaFLOWholeHouseAudioDestinationContext *wholeHouseAudioDestinationContext;

- (void).cxx_destruct;
- (id)activeSubscriptions;
- (int)activeSubscriptionsAtIndex:(unsigned long long)arg1;
- (unsigned long long)activeSubscriptionsCount;
- (void)addActiveSubscriptions:(int)arg1;
- (int)appleMusicVoicePreviewOfferNotShown;
- (int)appleMusicVoiceUserSubscriptionState;
- (void)clearActiveSubscriptions;
- (id)dictionaryRepresentation;
- (bool)hasAppleMusicVoicePreviewOfferNotShown;
- (bool)hasAppleMusicVoiceUserSubscriptionState;
- (bool)hasIsMusicSubscriber;
- (bool)hasIsWholeHouseAudio;
- (bool)hasMediaType;
- (bool)hasTaskType;
- (bool)hasWholeHouseAudioDestinationContext;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isMusicSubscriber;
- (bool)isWholeHouseAudio;
- (id)jsonData;
- (int)mediaType;
- (bool)readFrom:(id)arg1;
- (void)setActiveSubscriptions:(id)arg1;
- (void)setAppleMusicVoicePreviewOfferNotShown:(int)arg1;
- (void)setAppleMusicVoiceUserSubscriptionState:(int)arg1;
- (void)setHasAppleMusicVoicePreviewOfferNotShown:(bool)arg1;
- (void)setHasAppleMusicVoiceUserSubscriptionState:(bool)arg1;
- (void)setHasIsMusicSubscriber:(bool)arg1;
- (void)setHasIsWholeHouseAudio:(bool)arg1;
- (void)setHasMediaType:(bool)arg1;
- (void)setHasTaskType:(bool)arg1;
- (void)setHasWholeHouseAudioDestinationContext:(bool)arg1;
- (void)setIsMusicSubscriber:(bool)arg1;
- (void)setIsWholeHouseAudio:(bool)arg1;
- (void)setMediaType:(int)arg1;
- (void)setTaskType:(int)arg1;
- (void)setWholeHouseAudioDestinationContext:(id)arg1;
- (int)taskType;
- (id)wholeHouseAudioDestinationContext;
- (void)writeTo:(id)arg1;

@end
