/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface ORCHSchemaORCHDeviceDynamicContext : SISchemaInstrumentationMessage {
    struct { 
        unsigned int thermalState : 1; 
    }  _has;
    int  _thermalState;
}

@property (nonatomic) bool hasThermalState;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) int thermalState;

- (id)dictionaryRepresentation;
- (bool)hasThermalState;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setHasThermalState:(bool)arg1;
- (void)setThermalState:(int)arg1;
- (int)thermalState;
- (void)writeTo:(id)arg1;

@end
