/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface PLUSSchemaPLUSClientEvent : SISchemaTopLevelUnionType {
    PLUSSchemaPLUSContactGroundTruthGenerated * _contactGroundTruthGenerated;
    PLUSSchemaPLUSContactSuggesterQueryContext * _contactSuggesterQueryContext;
    PLUSSchemaPLUSContactSuggesterRequestMetadataReported * _contactSuggesterRequestMetadataReported;
    PLUSSchemaPLUSContactSuggesterSuggestionMetadataReported * _contactSuggesterSuggestionMetadataReported;
    PLUSSchemaPLUSContactSuggestionGenerated * _contactSuggestionGenerated;
    PLUSSchemaPLUSContactSuggestionOutcomeReported * _contactSuggestionOutcomeReported;
    PLUSSchemaPLUSClientEventMetadata * _eventMetadata;
    bool  _hasContactGroundTruthGenerated;
    bool  _hasContactSuggesterQueryContext;
    bool  _hasContactSuggesterRequestMetadataReported;
    bool  _hasContactSuggesterSuggestionMetadataReported;
    bool  _hasContactSuggestionGenerated;
    bool  _hasContactSuggestionOutcomeReported;
    bool  _hasEventMetadata;
    bool  _hasInferencePluginInvocationContext;
    bool  _hasPhoneCallMetadataExtracted;
    bool  _hasUsoGraphTier1;
    PLUSSchemaPLUSInferencePluginInvocationContext * _inferencePluginInvocationContext;
    PLUSSchemaPLUSPhoneCallMetadataExtracted * _phoneCallMetadataExtracted;
    PLUSSchemaPLUSUSOGraphTier1 * _usoGraphTier1;
    unsigned long long  _whichEvent_Type;
}

@property (nonatomic, retain) PLUSSchemaPLUSContactGroundTruthGenerated *contactGroundTruthGenerated;
@property (nonatomic, retain) PLUSSchemaPLUSContactSuggesterQueryContext *contactSuggesterQueryContext;
@property (nonatomic, retain) PLUSSchemaPLUSContactSuggesterRequestMetadataReported *contactSuggesterRequestMetadataReported;
@property (nonatomic, retain) PLUSSchemaPLUSContactSuggesterSuggestionMetadataReported *contactSuggesterSuggestionMetadataReported;
@property (nonatomic, retain) PLUSSchemaPLUSContactSuggestionGenerated *contactSuggestionGenerated;
@property (nonatomic, retain) PLUSSchemaPLUSContactSuggestionOutcomeReported *contactSuggestionOutcomeReported;
@property (nonatomic, retain) PLUSSchemaPLUSClientEventMetadata *eventMetadata;
@property (nonatomic) bool hasContactGroundTruthGenerated;
@property (nonatomic) bool hasContactSuggesterQueryContext;
@property (nonatomic) bool hasContactSuggesterRequestMetadataReported;
@property (nonatomic) bool hasContactSuggesterSuggestionMetadataReported;
@property (nonatomic) bool hasContactSuggestionGenerated;
@property (nonatomic) bool hasContactSuggestionOutcomeReported;
@property (nonatomic) bool hasEventMetadata;
@property (nonatomic) bool hasInferencePluginInvocationContext;
@property (nonatomic) bool hasPhoneCallMetadataExtracted;
@property (nonatomic) bool hasUsoGraphTier1;
@property (nonatomic, retain) PLUSSchemaPLUSInferencePluginInvocationContext *inferencePluginInvocationContext;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) PLUSSchemaPLUSPhoneCallMetadataExtracted *phoneCallMetadataExtracted;
@property (nonatomic, retain) PLUSSchemaPLUSUSOGraphTier1 *usoGraphTier1;
@property (nonatomic, readonly) unsigned long long whichEvent_Type;

- (void).cxx_destruct;
- (id)contactGroundTruthGenerated;
- (id)contactSuggesterQueryContext;
- (id)contactSuggesterRequestMetadataReported;
- (id)contactSuggesterSuggestionMetadataReported;
- (id)contactSuggestionGenerated;
- (id)contactSuggestionOutcomeReported;
- (id)dictionaryRepresentation;
- (id)eventMetadata;
- (int)getAnyEventType;
- (bool)hasContactGroundTruthGenerated;
- (bool)hasContactSuggesterQueryContext;
- (bool)hasContactSuggesterRequestMetadataReported;
- (bool)hasContactSuggesterSuggestionMetadataReported;
- (bool)hasContactSuggestionGenerated;
- (bool)hasContactSuggestionOutcomeReported;
- (bool)hasEventMetadata;
- (bool)hasInferencePluginInvocationContext;
- (bool)hasPhoneCallMetadataExtracted;
- (bool)hasUsoGraphTier1;
- (unsigned long long)hash;
- (id)inferencePluginInvocationContext;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)phoneCallMetadataExtracted;
- (id)qualifiedMessageName;
- (bool)readFrom:(id)arg1;
- (void)setContactGroundTruthGenerated:(id)arg1;
- (void)setContactSuggesterQueryContext:(id)arg1;
- (void)setContactSuggesterRequestMetadataReported:(id)arg1;
- (void)setContactSuggesterSuggestionMetadataReported:(id)arg1;
- (void)setContactSuggestionGenerated:(id)arg1;
- (void)setContactSuggestionOutcomeReported:(id)arg1;
- (void)setEventMetadata:(id)arg1;
- (void)setHasContactGroundTruthGenerated:(bool)arg1;
- (void)setHasContactSuggesterQueryContext:(bool)arg1;
- (void)setHasContactSuggesterRequestMetadataReported:(bool)arg1;
- (void)setHasContactSuggesterSuggestionMetadataReported:(bool)arg1;
- (void)setHasContactSuggestionGenerated:(bool)arg1;
- (void)setHasContactSuggestionOutcomeReported:(bool)arg1;
- (void)setHasEventMetadata:(bool)arg1;
- (void)setHasInferencePluginInvocationContext:(bool)arg1;
- (void)setHasPhoneCallMetadataExtracted:(bool)arg1;
- (void)setHasUsoGraphTier1:(bool)arg1;
- (void)setInferencePluginInvocationContext:(id)arg1;
- (void)setPhoneCallMetadataExtracted:(id)arg1;
- (void)setUsoGraphTier1:(id)arg1;
- (id)usoGraphTier1;
- (unsigned long long)whichEvent_Type;
- (void)writeTo:(id)arg1;

@end
