/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface TTSSchemaTTSSpeechEnded : SISchemaInstrumentationMessage {
    struct { 
        unsigned int synthesizedAudioDurationInSecond : 1; 
        unsigned int synthesisLatencyInSecond : 1; 
        unsigned int synthesisRealTimeFactor : 1; 
        unsigned int promptCount : 1; 
    }  _has;
    unsigned int  _promptCount;
    float  _synthesisLatencyInSecond;
    float  _synthesisRealTimeFactor;
    float  _synthesizedAudioDurationInSecond;
}

@property (nonatomic) bool hasPromptCount;
@property (nonatomic) bool hasSynthesisLatencyInSecond;
@property (nonatomic) bool hasSynthesisRealTimeFactor;
@property (nonatomic) bool hasSynthesizedAudioDurationInSecond;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) unsigned int promptCount;
@property (nonatomic) float synthesisLatencyInSecond;
@property (nonatomic) float synthesisRealTimeFactor;
@property (nonatomic) float synthesizedAudioDurationInSecond;

- (id)dictionaryRepresentation;
- (bool)hasPromptCount;
- (bool)hasSynthesisLatencyInSecond;
- (bool)hasSynthesisRealTimeFactor;
- (bool)hasSynthesizedAudioDurationInSecond;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (unsigned int)promptCount;
- (bool)readFrom:(id)arg1;
- (void)setHasPromptCount:(bool)arg1;
- (void)setHasSynthesisLatencyInSecond:(bool)arg1;
- (void)setHasSynthesisRealTimeFactor:(bool)arg1;
- (void)setHasSynthesizedAudioDurationInSecond:(bool)arg1;
- (void)setPromptCount:(unsigned int)arg1;
- (void)setSynthesisLatencyInSecond:(float)arg1;
- (void)setSynthesisRealTimeFactor:(float)arg1;
- (void)setSynthesizedAudioDurationInSecond:(float)arg1;
- (float)synthesisLatencyInSecond;
- (float)synthesisRealTimeFactor;
- (float)synthesizedAudioDurationInSecond;
- (void)writeTo:(id)arg1;

@end
