/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface HomeControlAnalysisPETCoreBehaviorAnalysisEvent : PBCodable <NSCopying> {
    NSString * _accessoryUUID;
    NSString * _associatedAccessoryUUIDs;
    NSString * _characteristicType;
    NSString * _eventStreamTitle;
    struct { 
        unsigned int homeOccupancy : 1; 
    }  _has;
    unsigned int  _homeOccupancy;
    NSString * _homeUUID;
    NSString * _homekitSource;
    NSString * _microlocation;
    NSString * _sceneUUID;
    NSString * _serviceType;
    NSString * _serviceUUID;
    double  _timestamp;
    NSString * _value;
}

@property (nonatomic, retain) NSString *accessoryUUID;
@property (nonatomic, retain) NSString *associatedAccessoryUUIDs;
@property (nonatomic, retain) NSString *characteristicType;
@property (nonatomic, retain) NSString *eventStreamTitle;
@property (nonatomic, readonly) bool hasAccessoryUUID;
@property (nonatomic, readonly) bool hasAssociatedAccessoryUUIDs;
@property (nonatomic, readonly) bool hasCharacteristicType;
@property (nonatomic, readonly) bool hasEventStreamTitle;
@property (nonatomic) bool hasHomeOccupancy;
@property (nonatomic, readonly) bool hasHomeUUID;
@property (nonatomic, readonly) bool hasHomekitSource;
@property (nonatomic, readonly) bool hasMicrolocation;
@property (nonatomic, readonly) bool hasSceneUUID;
@property (nonatomic, readonly) bool hasServiceType;
@property (nonatomic, readonly) bool hasServiceUUID;
@property (nonatomic, readonly) bool hasValue;
@property (nonatomic) unsigned int homeOccupancy;
@property (nonatomic, retain) NSString *homeUUID;
@property (nonatomic, retain) NSString *homekitSource;
@property (nonatomic, retain) NSString *microlocation;
@property (nonatomic, retain) NSString *sceneUUID;
@property (nonatomic, retain) NSString *serviceType;
@property (nonatomic, retain) NSString *serviceUUID;
@property (nonatomic) double timestamp;
@property (nonatomic, retain) NSString *value;

- (void).cxx_destruct;
- (id)accessoryUUID;
- (id)associatedAccessoryUUIDs;
- (id)characteristicType;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)eventStreamTitle;
- (bool)hasAccessoryUUID;
- (bool)hasAssociatedAccessoryUUIDs;
- (bool)hasCharacteristicType;
- (bool)hasEventStreamTitle;
- (bool)hasHomeOccupancy;
- (bool)hasHomeUUID;
- (bool)hasHomekitSource;
- (bool)hasMicrolocation;
- (bool)hasSceneUUID;
- (bool)hasServiceType;
- (bool)hasServiceUUID;
- (bool)hasValue;
- (unsigned long long)hash;
- (unsigned int)homeOccupancy;
- (id)homeUUID;
- (id)homekitSource;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)microlocation;
- (bool)readFrom:(id)arg1;
- (id)sceneUUID;
- (id)serviceType;
- (id)serviceUUID;
- (void)setAccessoryUUID:(id)arg1;
- (void)setAssociatedAccessoryUUIDs:(id)arg1;
- (void)setCharacteristicType:(id)arg1;
- (void)setEventStreamTitle:(id)arg1;
- (void)setHasHomeOccupancy:(bool)arg1;
- (void)setHomeOccupancy:(unsigned int)arg1;
- (void)setHomeUUID:(id)arg1;
- (void)setHomekitSource:(id)arg1;
- (void)setMicrolocation:(id)arg1;
- (void)setSceneUUID:(id)arg1;
- (void)setServiceType:(id)arg1;
- (void)setServiceUUID:(id)arg1;
- (void)setTimestamp:(double)arg1;
- (void)setValue:(id)arg1;
- (double)timestamp;
- (id)value;
- (void)writeTo:(id)arg1;

@end
