/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CABasicAnimation : CAPropertyAnimation

@property (retain) id byValue;
@property double endAngle;
@property (retain) id fromValue;
@property bool roundsToInteger;
@property double startAngle;
@property (retain) id toValue;

// Image: /System/Library/Frameworks/QuartzCore.framework/QuartzCore

- (void)CA_prepareRenderValue;
- (void*)_copyRenderAnimationForLayer:(id)arg1;
- (bool)_setCARenderAnimation:(void*)arg1 layer:(id)arg2;
- (double)_timeFunction:(double)arg1;
- (void)applyForTime:(double)arg1 presentationObject:(id)arg2 modelObject:(id)arg3;
- (id)byValue;
- (double)endAngle;
- (id)fromValue;
- (bool)roundsToInteger;
- (void)setByValue:(id)arg1;
- (void)setEndAngle:(double)arg1;
- (void)setFromValue:(id)arg1;
- (void)setRoundsToInteger:(bool)arg1;
- (void)setStartAngle:(double)arg1;
- (void)setToValue:(id)arg1;
- (double)startAngle;
- (id)toValue;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (id)normalizedAnimationWithKeyPath:(id)arg1 fromValue:(id)arg2 toValue:(id)arg3;

@end
