/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaExperience.framework/MediaExperience
 */

@interface MXSystemController : NSObject {
    bool  mAppWantsVolumeChanges;
    bool  mCanBeNowPlayingApp;
    int  mClientPID;
    NSString * mDisplayID;
    bool  mHasEntitlementForPIDInheritance;
    NSMutableDictionary * mNotificationsSubscribedTo;
    int  mPIDToInheritAppStateFrom;
    NSString * mRemoteDeviceID;
}

@property (nonatomic, readonly) bool isSomeoneRecording;
@property (nonatomic, readonly) bool phoneCallExists;
@property (nonatomic, readonly) bool someLongFormVideoClientIsActiveOverAirPlayVideo;
@property (nonatomic, readonly) bool someLongFormVideoClientIsPlaying;
@property (nonatomic, readonly) bool someLongFormVideoClientIsPlayingOverAirPlayVideo;
@property (nonatomic, readonly) bool someSharePlayCapableCallSessionIsActive;

+ (void)dumpInfoOfMXSystemControllers;
+ (bool)getCanBeNowPlayingAppForPID:(int)arg1;
+ (int)getPIDForAnyAppThatWantsVolumeChanges;
+ (int)getPIDToInheritAppStateFromForPID:(int)arg1;
+ (void)notifyAll:(id)arg1 payload:(id)arg2 dontPostIfSuspended:(bool)arg3;
+ (void)notifyAll:(id)arg1 payload:(id)arg2 dontPostIfSuspended:(bool)arg3 remoteDeviceID:(id)arg4;
+ (void)updateMXSystemControllerList;

- (void)applyCanBeNowPlayingApp:(const void*)arg1;
- (int)applyPIDToInheritAppStateFrom:(const void*)arg1;
- (int)copyAttributeForKey:(id)arg1 withValueOut:(void*)arg2;
- (void)dealloc;
- (id)getDisplayID;
- (id)info;
- (id)initWithPID:(int)arg1;
- (id)initWithPID:(int)arg1 remoteDeviceID:(id)arg2;
- (bool)isSomeoneRecording;
- (bool)phoneCallExists;
- (int)setAttributeForKey:(id)arg1 andValue:(const void*)arg2;
- (bool)someLongFormVideoClientIsActiveOverAirPlayVideo;
- (bool)someLongFormVideoClientIsPlaying;
- (bool)someLongFormVideoClientIsPlayingOverAirPlayVideo;
- (bool)someSharePlayCapableCallSessionIsActive;

@end
