/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNEnvironmentTestDouble : CNEnvironment

@property (getter=isCommLimitsEnabled) bool commLimitsEnabled;
@property (copy) NSString *defaultCountryCode;
@property (retain) <CNEntitlementVerification> *entitlementVerifier;
@property (retain) <CNFileManager> *fileManager;
@property (getter=isInternalBuild) bool internalBuild;
@property (retain) <CNLocalizationServices> *localizationServices;
@property (copy) NSString *mainBundleIdentifier;
@property (retain) <CNMetricsReporter> *metricsReporter;
@property (retain) NSNotificationCenter *notificationCenter;
@property (retain) <CNSchedulerProvider> *schedulerProvider;
@property (retain) <CNTimeProvider> *timeProvider;
@property (retain) CNUserDefaults *userDefaults;

// Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation

- (void)setCommLimitsEnabled:(bool)arg1;
- (void)setDefaultCountryCode:(id)arg1;
- (void)setEntitlementVerifier:(id)arg1;
- (void)setFileManager:(id)arg1;
- (void)setInternalBuild:(bool)arg1;
- (void)setLocalizationServices:(id)arg1;
- (void)setMainBundleIdentifier:(id)arg1;
- (void)setNotificationCenter:(id)arg1;
- (void)setSchedulerProvider:(id)arg1;
- (void)setTimeProvider:(id)arg1;
- (void)setUserDefaults:(id)arg1;

// Image: /System/Library/PrivateFrameworks/ContactsMetrics.framework/ContactsMetrics

- (void)setMetricsReporter:(id)arg1;

@end
