/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEONetworkDefaultsLocalProxy : NSObject <GEOPListStateCapturing, _GEONetworkDefaultsServerProxy> {
    <_GEONetworkDefaultsServerProxyDelegate> * _delegate;
    geo_isolater * _isolation;
    NSDate * _lastNetworkFailure;
    unsigned long long  _stateCaptureHandle;
    NSMutableArray * _updateCompletionHandlers;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <_GEONetworkDefaultsServerProxyDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_callCompletionHandlersWithError:(id)arg1;
- (void)_processNetworkDefaultsResponse:(id)arg1 data:(id)arg2 error:(id)arg3 request:(id)arg4;
- (void)_updateNetworkDefaults;
- (void)_updateWithNewConfig:(id)arg1 request:(id)arg2 response:(id)arg3;
- (id)_urlRequestForNetworkDefaults;
- (id)captureStatePlistWithHints:(struct os_state_hints_s { unsigned int x1; char *x2; unsigned int x3; unsigned int x4; }*)arg1;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)updateNetworkDefaults:(id /* block */)arg1;
- (void)updateNetworkDefaultsWithReason:(unsigned long long)arg1 completionHandler:(id /* block */)arg2;

@end
