/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOETAServiceResponseSummary : PBCodable <NSCopying> {
    struct { 
        unsigned int has_responseUuid : 1; 
        unsigned int has_status : 1; 
        unsigned int has_resultsApplied : 1; 
    }  _flags;
    struct GEOSessionID { 
        unsigned long long _high; 
        unsigned long long _low; 
    }  _responseUuid;
    bool  _resultsApplied;
    NSMutableArray * _routeInfos;
    int  _status;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)jsonRepresentation;
- (bool)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end
