/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOMapFeatureRoadFinder : GEOMapFeatureAccessFinder {
    bool  _flipNegativeTravelDirectionRoads;
    GEOMapFeatureIntersectedRoadFinder * _intersectedRoadFinder;
    GEOTileLoader * _tileLoader;
    bool  _visitDoubleTravelDirectionRoadsTwice;
}

@property (nonatomic) bool flipNegativeTravelDirectionRoads;
@property (nonatomic) bool visitDoubleTravelDirectionRoadsTwice;

- (void).cxx_destruct;
- (void)_findConnectedSegmentsFromRoad:(id)arg1 muid:(unsigned long long)arg2 handler:(id /* block */)arg3 completionHandler:(id /* block */)arg4;
- (void)_recursivelyFindRoadSegmentsWithMuid:(unsigned long long)arg1 segments:(id)arg2 directionality:(unsigned long long)arg3 completionHandler:(id /* block */)arg4;
- (id)findRoadWithID:(unsigned long long)arg1 handler:(id /* block */)arg2 completionHandler:(id /* block */)arg3;
- (id)findRoadWithMuid:(unsigned long long)arg1 nearCoordinate:(struct { double x1; double x2; })arg2 handler:(id /* block */)arg3 completionHandler:(id /* block */)arg4;
- (id)findRoadsNear:(struct { double x1; double x2; })arg1 radius:(double)arg2 handler:(id /* block */)arg3 completionHandler:(id /* block */)arg4;
- (bool)flipNegativeTravelDirectionRoads;
- (id)initWithTileLoader:(id)arg1;
- (void)setFlipNegativeTravelDirectionRoads:(bool)arg1;
- (void)setVisitDoubleTravelDirectionRoadsTwice:(bool)arg1;
- (bool)visitDoubleTravelDirectionRoadsTwice;

@end
