/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSearchSectionList : NSObject {
    NSArray * _searchSections;
}

@property (nonatomic, readonly) NSArray *searchSections;

- (void).cxx_destruct;
- (id)init;
- (id)initWithSearchSectionList:(id)arg1 mapsResults:(id)arg2;
- (id)initWithSearchSections:(id)arg1;
- (id)searchSections;

@end
