/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreML.framework/CoreML
 */

@interface MLCompiler : NSObject

+ (id)_compileSpecificationAtURL:(id)arg1 toURL:(id)arg2 compiledModelName:(id)arg3 options:(id)arg4 error:(id*)arg5;
+ (id)compileModelAtURL:(id)arg1 toURL:(id)arg2 options:(id)arg3 error:(id*)arg4;
+ (id)compileSpecification:(void*)arg1 toArchive:(void*)arg2 options:(id)arg3 error:(id*)arg4;
+ (id)compileSpecificationAtURL:(id)arg1 toURL:(id)arg2 options:(id)arg3 error:(id*)arg4;
+ (id)compiledVersionForModelAtURL:(id)arg1 options:(id)arg2 error:(id*)arg3;
+ (id)compiledVersionForSpecification:(void*)arg1 options:(id)arg2 error:(id*)arg3;
+ (id)compiledVersionForSpecificationAtURL:(id)arg1 options:(id)arg2 error:(id*)arg3;
+ (id)contentsOfDirectoryAtURL:(id)arg1 error:(id*)arg2;
+ (bool)encryptCompiledModelAtURL:(id)arg1 options:(id)arg2 error:(id*)arg3;
+ (bool)encryptFileAtURL:(id)arg1 options:(id)arg2 error:(id*)arg3;
+ (bool)fingerprintSpecificationAtURL:(id)arg1 toArchive:(void*)arg2 error:(id*)arg3;
+ (bool)storeEncryptionInfoInCompiledArchive:(void*)arg1 options:(id)arg2 error:(id*)arg3;
+ (id)versionInfo;

@end
