/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreML.framework/CoreML
 */

@interface MLModelTypeRegistry : NSObject

+ (id)sharedInstance;

- (Class)classForCompilingModelType:(int)arg1;
- (Class)classForLoadingModelType:(int)arg1;
- (Class)classForLoadingModelType:(int)arg1 isUpdatable:(bool)arg2 trainWithMLCompute:(bool)arg3;
- (id)init;
- (Class)loadNeuralNetworkClass:(bool)arg1 trainWithMLCompute:(bool)arg2;

@end
