/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreML.framework/CoreML
 */

@interface MLModel : NSObject <MLModeling> {
    MLModelConfiguration * _configuration;
    MLFairPlayDecryptSession * _decryptSession;
    MLModelMetadata * _metadata;
    MLModelDescription * _modelDescription;
    MLPredictionEvent * _predictionEvent;
}

@property (nonatomic, retain) MLModelConfiguration *configuration;
@property (nonatomic, retain) MLFairPlayDecryptSession *decryptSession;
@property (readonly) MLModelMetadata *metadata;
@property (nonatomic, retain) MLModelDescription *modelDescription;
@property (nonatomic, retain) MLPredictionEvent *predictionEvent;

+ (id)_compileModelAtURL:(id)arg1 options:(id)arg2 error:(id*)arg3;
+ (id)compileModelAtURL:(id)arg1 error:(id*)arg2;
+ (id)compileModelWithoutAutoreleaseAtURL:(id)arg1 options:(id)arg2 error:(id*)arg3;
+ (void)loadContentsOfURL:(id)arg1 configuration:(id)arg2 completionHandler:(id /* block */)arg3;
+ (id)modelWithContentsOfURL:(id)arg1 configuration:(id)arg2 error:(id*)arg3;
+ (id)modelWithContentsOfURL:(id)arg1 error:(id*)arg2;
+ (id)predictionsFromLoopingOverBatch:(id)arg1 model:(id)arg2 options:(id)arg3 error:(id*)arg4;
+ (id)predictionsFromSubbatchingBatch:(id)arg1 maxSubbatchLength:(long long)arg2 predictionBlock:(id /* block */)arg3 options:(id)arg4 error:(id*)arg5;
+ (bool)serializeInterfaceAndMetadata:(void*)arg1 toArchive:(void*)arg2 error:(id*)arg3;

- (void).cxx_destruct;
- (id)configuration;
- (id)debugQuickLookObject;
- (id)decryptSession;
- (id)description;
- (id)executionSchedule;
- (id)initDescriptionOnlyWithSpecification:(void*)arg1 configuration:(id)arg2 error:(id*)arg3;
- (id)initInterfaceAndMetadataWithCompiledArchive:(void*)arg1 error:(id*)arg2;
- (id)initWithConfiguration:(id)arg1;
- (id)initWithDescription:(id)arg1;
- (id)initWithDescription:(id)arg1 configuration:(id)arg2;
- (id)initWithName:(id)arg1 inputDescription:(id)arg2 outputDescription:(id)arg3 orderedInputFeatureNames:(id)arg4 orderedOutputFeatureNames:(id)arg5 configuration:(id)arg6;
- (id)metadata;
- (id)modelDescription;
- (id)modelPath;
- (id)objectBoundingBoxOutputDescription;
- (id)parameterValueForKey:(id)arg1 error:(id*)arg2;
- (id)pipelineOfPostVisionFeaturePrintModelsFromPipeline:(id)arg1;
- (id)predictionEvent;
- (id)predictionFromFeatures:(id)arg1 error:(id*)arg2;
- (id)predictionFromFeatures:(id)arg1 options:(id)arg2 error:(id*)arg3;
- (id)predictionsFromBatch:(id)arg1 error:(id*)arg2;
- (id)predictionsFromBatch:(id)arg1 options:(id)arg2 error:(id*)arg3;
- (void)setConfiguration:(id)arg1;
- (void)setDecryptSession:(id)arg1;
- (void)setModelDescription:(id)arg1;
- (void)setModelPath:(id)arg1 modelName:(id)arg2;
- (void)setPredictionEvent:(id)arg1;
- (id)vectorizeInput:(id)arg1 error:(id*)arg2;
- (id)visionFeaturePrintInfo;

@end
